var WALKTHROUGHS_CHEMISTRY = {
  "2022": [
    {
      num: 1,
      label: "Q1: Water Hardness (Volumetric Analysis)",
      q: "A student compared total hardness values of a water supply before and after passing through a laboratory deioniser, using edta titration with 25.0 cm3 water samples.\n\nBalanced equation: M2+ + H2Y2- -> MY2- + 2H+\n\nOn average, 9.2 cm3 less of the 0.010 M edta solution was required for the deionised water than for the original hard water.\n\n(a)(i) Identify the two ions (M2+) that most commonly cause hardness.\n(a)(ii) Explain the term total hardness.\n(b)(i) Name a suitable indicator for this titration.\n(b)(ii) What colour change is observed at the end point?\n(c)(i) What pH does the buffer solution maintain?\n(c)(ii) Why is it important to maintain this pH?\n(d) Describe the correct procedure for preparing a burette for this titration.\n(e) Calculate:\n(i) the number of moles of edta in 9.2 cm3 of a 0.010 M solution,\n(ii) the number of moles of M2+ that reacted with this edta,\n(iii) the moles of M2+ removed per litre of original hard water,\n(iv) the total hardness removed in g/L of CaCO3 and in p.p.m. CaCO3.",
      a: "(a)(i) Calcium (Ca2+) and magnesium (Mg2+) ions.\n(a)(ii) Total hardness is the sum of all permanent and temporary hardness, due to the total dissolved Ca2+ and Mg2+ ions.\n\n(b)(i) Solochrome Black (Eriochrome Black T).\n(b)(ii) Wine-red (pink) to blue.\n\n(c)(i) pH 10 (accept 9-11).\n(c)(ii) To ensure a sharp end point; the MY2- complex is stable only at high pH for calcium and magnesium; ensures only Ca2+ and Mg2+ react with edta.\n\n(d) Clamp vertically. Fill above the zero mark. Fill the nozzle below the tap before adjusting to the initial mark. Use a clean dry funnel (remove before reading). Ensure no air bubbles. Read the bottom of the meniscus at eye level.\n\n(e)(i) 9.2 x 0.010 / 1000 = 9.2 x 10^-5 moles edta.\n(e)(ii) M2+:edta = 1:1 from the equation, so 9.2 x 10^-5 moles M2+.\n(e)(iii) Multiply by 40 (to convert 25 cm3 to 1 litre): 9.2 x 10^-5 x 40 = 3.68 x 10^-3 moles per litre.\n(e)(iv) Multiply by Mr of CaCO3 (100): 3.68 x 10^-3 x 100 = 0.368 g/L. Then x 1000 for p.p.m.: 368 p.p.m. CaCO3.\n\nWhy: The M2+:edta ratio is 1:1 from the balanced equation. To go from 25 cm3 to 1 L, multiply by 40. For p.p.m., 1 g/L = 1000 p.p.m."
    },
    {
      num: 2,
      label: "Q2: Organic Preparations & Recrystallisation",
      q: "(a) Draw a labelled diagram for the preparation and collection over water of pure ethene gas. State one way of avoiding (i) a suck-back of cold water, (ii) a fire.\n\n(b) Ethene was bubbled through reagents. What colour change is observed with:\n(i) dilute acidified KMnO4?\n(ii) bromine water?\n(iii) Name the organic reaction type with bromine.\n(iv) Identify an organic product of the reaction with bromine solution.\n\n(c) Recrystallisation of benzoic acid (impurities: KCl and charcoal):\n(i) Identify substances collected at locations X, Y and Z in the two filtration stages.\n(ii) What steps maximise yield between the first and second filtrations?\n(iii) After the second filtration?\n(iv) How does the melting point of recrystallised benzoic acid differ from impure?",
      a: "(a) Diagram: horizontal test tube with glass wool soaked in ethanol, aluminium oxide (Al2O3) catalyst near the centre, heat source (Bunsen) under the catalyst, delivery tube leading to collection over water. Ethanol and catalyst must be labelled.\n(i) Avoid suck-back: loosen stopper or remove delivery tube from water before cooling/removing heat.\n(ii) Avoid fire: keep ethene gas and flame separate; ensure apparatus is sealed; close ethanol container after setup.\n\n(b)(i) Purple decolourises to colourless.\n(b)(ii) Brown/orange decolourises to colourless.\n(b)(iii) Addition reaction.\n(b)(iv) 1,2-dibromoethane (BrCH2CH2Br) or 2-bromoethanol.\n\n(c)(i) X = charcoal (carbon). Y = benzoic acid. Z = potassium chloride (KCl) and/or water.\n(c)(ii) Evaporate some water / cool the solution / allow time for crystals to form.\n(c)(iii) Wash crystals with ice-cold water; dry the crystals.\n(c)(iv) Recrystallised sample has a higher melting point and a sharper (narrower) melting point range, closer to 122 degrees C.\n\nWhy: KMnO4 and bromine water both test for unsaturation (the C=C double bond). Decolourisation confirms ethene is unsaturated. Recrystallisation removes impurities, which always lower and broaden the melting point."
    },
    {
      num: 3,
      label: "Q3: Rates of Reaction (H2O2 Decomposition)",
      q: "The rate of decomposition of hydrogen peroxide using MnO2 (0.5 g, fine powder) as catalyst was investigated. 25.0 cm3 of H2O2 decomposed and the volume of oxygen was monitored.\n\nData: Time (min): 0, 1, 3, 5, 8, 10, 12, 14, 16. Volume O2 (cm3): 0, 30, 66, 88, 104, 109, 111, 112, 112.\n\n(a) Write a balanced equation for the decomposition of H2O2.\n(b) Give one risk associated with hydrogen peroxide and how to manage it.\n(c) Plot a volume vs time graph. Use the graph to find:\n(i) the time for the reaction to be complete,\n(ii) the average rate over the first 4.0 minutes,\n(iii) the instantaneous rate at 4.0 minutes.\n(d) Sketch and label curves for:\n(i) half the concentration of H2O2 with 0.5 g catalyst,\n(ii) same concentration with 0.6 g catalyst.\nJustify the shape of each curve.",
      a: "(a) 2H2O2 -> 2H2O + O2.\n\n(b) Risk: corrosive (burns skin), or acts as an oxidiser (can cause fire). Manage: wear PPE (gloves, eye protection); store in cool, ventilated area; use dilute solutions; store small quantities away from incompatible substances.\n\n(c)(i) Reaction complete at approximately 13-14 minutes (where curve levels off at 112 cm3).\n(c)(ii) Read volume at 4 min from graph (approx. 78 cm3). Average rate = 78/4 = 19.5 cm3 O2 per minute.\n(c)(iii) Draw a tangent to the curve at 4 minutes. Read two points from the tangent line. Slope = rise/run. Approximately 9.8 cm3 O2 per minute (acceptable range: 8.8-12.2). A tangent must be drawn on the graph.\n\n(d)(i) Half concentration: curve starts at origin, rises less steeply than original, levels off at approximately 56 cm3 (half the final volume). Justification: yield (volume of O2) depends on initial concentration -- half the moles of H2O2 produces half the O2.\n(d)(ii) 0.6 g catalyst: curve starts at origin, initially as steep or steeper than the original, but levels off at the same 112 cm3. Justification: more catalyst = greater surface area (more active sites) = faster initial rate, but same yield because catalyst amount does not affect yield -- the same amount of H2O2 is used.\n\nWhy: Average rate = total change / total time. Instantaneous rate = slope of tangent at that point. A catalyst affects rate but not yield."
    },
    {
      num: 4,
      label: "Q4: Short Questions (Mixed Topics)",
      q: "Answer eight of the following:\n(a) Explain Dobereiner's triads using the set {Li, Na, K}.\n(b) Why is a photon emitted when an electron drops to a lower energy level (Balmer series)?\n(c) Why is the 2nd ionisation energy of lithium significantly larger than the 1st?\n(d) What colour is observed in a flame test for (i) lithium, (ii) copper?\n(e) State Avogadro's law.\n(f) A diamond of 1098 carats contains 18.3 moles of carbon. Calculate the mass of one carat in grams.\n(g) What reagents confirm the presence of nitrate ions in solution?\n(h) Identify a substance added to drinking water for (i) flocculation, (ii) fluoridation.\n(i) What elements are the products of electrolysis of aqueous KI using inert electrodes?\n(j) Which has the strongest C-C bonding: ethane, ethene, ethyne, or benzene?\n(k) Calculate the average daily dose (mg) when a person took 0.146 moles of aspirin (Mr = 180) over 365 days.\n(l) A: Write balanced equations for the dissociation of carbonic acid in water. OR B: What distinguishes molecular crystals from other types?",
      a: "(a) Li, Na, K have similar chemical properties. The atomic mass of Na (23) is the average of Li (7) and K (39): (7+39)/2 = 23. This pattern of triads was Dobereiner's contribution to developing the periodic table.\n\n(b) The electron in the outer (higher) energy level has more energy. Moving to a lower level, it loses energy, which is emitted as a photon of light. E = hf.\n\n(c) The second electron comes from a full (closed) inner shell (1s), much closer to the nucleus, with less shielding. Also, removing an electron from a positive ion (Li+) requires more energy than from a neutral atom.\n\n(d)(i) Lithium: red (crimson). (ii) Copper: blue-green.\n\n(e) Equal volumes of all gases, at the same temperature and pressure, contain the same number of molecules.\n\n(f) Mass of carbon = 18.3 x 12 = 219.6 g. One carat = 219.6 / 1098 = 0.2 g.\n\n(g) Aluminium foil (or Devarda's alloy) and sodium hydroxide solution. Heat gently. Ammonia gas produced turns moist red litmus blue.\n\n(h)(i) Aluminium sulfate (alum). (ii) Hydrofluorosilicic acid (H2SiF6) or sodium fluoride.\n\n(i) Hydrogen at the cathode, iodine at the anode.\n\n(j) Ethyne -- the triple bond gives the strongest carbon-to-carbon bonding.\n\n(k) Total mass = 0.146 x 180 = 26.28 g = 26280 mg. Daily dose = 26280 / 365 = 72 mg.\n\n(l) A: H2CO3 -> H+ + HCO3-; then HCO3- -> H+ + CO32-.\nB: Molecular crystals are held together by weak intermolecular forces (van der Waals), unlike ionic (electrostatic), covalent (shared electrons throughout), or metallic (delocalised electrons) crystals."
    },
    {
      num: 5,
      label: "Q5: Atomic Structure & Radioactivity",
      q: "(a) Rutherford's gold foil experiment (c. 1909): Most alpha particles passed straight through, a small number deflected at large angles, a very tiny number rebounded back.\n(i) Based on Thomson's model, which observation was most unexpected?\n(ii) What did Rutherford conclude about atomic structure?\n\n(b) Define (i) isotopes, (ii) relative atomic mass.\n\n(c) Write the s, p electron configuration for calcium in its ground state. How many (i) main energy levels, (ii) orbitals are occupied? Predict how calcium behaves in a chemical reaction.\n\n(d)(i) Define radioactivity.\n(ii) Complete the nuclear equation for alpha decay of Rn-222.\n(iii) Why can't lead (Pb) be changed to gold (Au) by chemical reactions?",
      a: "(a)(i) The very tiny number that rebounded back along their original paths was most unexpected. Thomson's plum pudding model (uniform positive charge) could not explain particles bouncing back.\n(a)(ii) The atom is mostly empty space with a tiny, dense, positively charged nucleus at the centre, containing most of the mass.\n\n(b)(i) Isotopes: atoms of the same element with the same atomic number but different mass numbers (different numbers of neutrons).\n(b)(ii) Relative atomic mass: the average mass of the isotopes of an element, weighted by their natural abundances, relative to 1/12 the mass of a carbon-12 atom.\n\n(c) Configuration: 1s2 2s2 2p6 3s2 3p6 4s2.\n(i) 4 main energy levels (shells) occupied.\n(ii) 10 orbitals occupied (1 + 1 + 3 + 1 + 3 + 1 = 10).\nCalcium will lose its 2 outer electrons (4s2) to achieve a stable noble gas configuration (argon), forming Ca2+ ions. It acts as a reducing agent.\n\n(d)(i) Radioactivity: the spontaneous disintegration (breaking up) of unstable nuclei with the emission of radiation.\n(d)(ii) Rn-222 -> Po-218 + He-4. The daughter element is polonium-218 (86 - 2 = 84 protons).\n(d)(iii) Chemical reactions involve only rearrangements of electrons in the outer shells. Changing lead to gold requires changing the number of protons in the nucleus, which is a nuclear change, not a chemical one.\n\nWhy: Rutherford's experiment disproved the plum pudding model. Only a tiny, dense, positively charged nucleus could cause alpha particles to rebound. Chemical reactions cannot change elements because they do not affect the nucleus."
    },
    {
      num: 6,
      label: "Q6: Fuels, Hydrocarbons & Thermochemistry",
      q: "(a) Compare petrol (light gasoline/naphtha) and diesel (gas oil) in terms of:\n(i) average molecular mass, (ii) boiling point.\n\n(b)(i) Explain the term octane number.\nGive the IUPAC name and draw the structure of the alkane with octane number:\n(ii) zero, (iii) 100.\n(iv) What structural feature gives the 100-octane alkane its high octane number?\n\n(c) Hydrogen fuel cells. Equation: H2(g) + 1/2 O2(g) -> H2O(l). Steam reforming: CH4(g) + H2O(g) -> CO(g) + 3H2(g), dH = +206.2 kJ.\n(i) Why doesn't elemental H2 occur naturally on Earth as a fuel?\n(ii) Give a major source of H2 other than steam reforming.\n(iii) Define heat of reaction.\n(iv) Why is the same energy released in a fuel cell as when H2 is burned?\n(v) Calculate the heat of formation of methane using: Hf(steam) = -241.8, Hf(CO) = -110.5 kJ/mol.",
      a: "(a)(i) Diesel has a higher average molecular mass than petrol.\n(a)(ii) Diesel has a higher boiling point than petrol.\n\n(b)(i) Octane number: a measure of how smoothly a fuel burns without knocking (premature auto-ignition), on a scale of 0 to 100.\n(b)(ii) Octane number 0: heptane (CH3(CH2)5CH3) -- a straight-chain alkane.\n(b)(iii) Octane number 100: 2,2,4-trimethylpentane (isooctane) -- a branched alkane.\n(b)(iv) Branching -- the highly branched structure resists auto-ignition and burns more smoothly.\n\n(c)(i) H2 is too reactive; it readily combines with oxygen and other elements, so free H2 does not accumulate in the atmosphere.\n(c)(ii) Electrolysis of water.\n(c)(iii) Heat of reaction: the heat change when the amounts of reactants shown in a balanced equation react completely.\n(c)(iv) Same reactants (H2 + O2) and same products (H2O) in both processes. By Hess's law, the enthalpy change depends only on the initial and final states, not the pathway.\n(c)(v) Rearrange: CH4(g) + H2O(g) -> CO(g) + 3H2(g). dH = Hf(products) - Hf(reactants). 206.2 = [-110.5 + 0] - [Hf(CH4) + (-241.8)]. 206.2 = -110.5 - Hf(CH4) + 241.8. 206.2 = 131.3 - Hf(CH4). Hf(CH4) = 131.3 - 206.2 = -74.9 kJ/mol.\n\nWhy: Hess's law states total enthalpy change is independent of the route. Whether H2 burns in a flame or reacts in a fuel cell, the overall reaction H2 + O2 -> H2O releases the same energy."
    },
    {
      num: 7,
      label: "Q7: Chemical Equilibrium",
      q: "CO(g) + 2H2(g) <=> CH3OH(g), dH = -94.4 kJ/mol.\n5.0 moles CO and 10.0 moles H2 in a 5.0 L container at 250 degrees C with catalyst. 25% conversion of CO to methanol at equilibrium.\n\n(a) Explain chemical equilibrium in terms of (i) rates of reaction, (ii) concentrations.\n(b)(i) Write the expression for Kc.\n(b)(ii) Calculate the value of Kc.\n(c) The same equilibrium is reached with two different catalysts. What is the advantage of a catalyst?\n(d)(i) State Le Chatelier's principle.\n(d)(ii) How is the yield of methanol affected when more CO is added and equilibrium re-establishes?",
      a: "(a)(i) At equilibrium, the rate of the forward reaction equals the rate of the reverse reaction.\n(a)(ii) At equilibrium, the concentrations of all reactants and products remain constant (though not necessarily equal).\n\n(b)(i) Kc = [CH3OH] / ([CO][H2]^2)\n(b)(ii) 25% of 5.0 mol CO reacts = 1.25 mol. H2 used = 2 x 1.25 = 2.5 mol.\nAt equilibrium: CO = 3.75 mol, H2 = 7.5 mol, CH3OH = 1.25 mol.\nConcentrations (divide by 5.0 L): [CO] = 0.75 M, [H2] = 1.5 M, [CH3OH] = 0.25 M.\nKc = 0.25 / (0.75 x 1.5^2) = 0.25 / (0.75 x 2.25) = 0.25 / 1.6875 = 0.148.\n\n(c) A catalyst speeds up both the forward and reverse reactions equally, so equilibrium is reached faster. It does not change the position of equilibrium or the value of Kc. The advantage is reaching equilibrium more quickly.\n\n(d)(i) Le Chatelier's principle: if a system at equilibrium is subjected to a change in conditions (concentration, temperature, or pressure), the equilibrium will shift in the direction that tends to oppose (partially counteract) the change.\n(d)(ii) Adding more CO increases [CO]. The system shifts to the right (towards products) to partially reduce [CO]. The yield of methanol increases.\n\nWhy: Kc only changes with temperature. Changing concentration or adding a catalyst does not change Kc. Le Chatelier's principle predicts the direction of the shift when conditions change."
    }
  ],
  "2023": [
    {
      num: 1,
      label: "Q1: Volumetric Analysis (Fe2+/KMnO4 Titration)",
      q: "(a) State two properties that make (NH4)2SO4.FeSO4.6H2O suitable as a primary standard.\n\n(b)(i) Describe how to prepare exactly 250 cm3 of a standard solution from 9.31 g of (NH4)2SO4.FeSO4.6H2O on a clock glass.\n(b)(ii) Why was dilute sulfuric acid added during preparation?\n\nBalanced equation: MnO4- + 5Fe2+ + 8H+ -> Mn2+ + 5Fe3+ + 4H2O\nMean titre: 22.6 cm3 of KMnO4 to react with 25.0 cm3 of Fe2+ solution.\n\n(c)(i) How was the end point of each titration detected?\n(c)(ii) What would be observed if insufficient acid was present? Explain.\n\n(d) Calculate:\n(i) concentration of (NH4)2SO4.FeSO4.6H2O in mol/L,\n(ii) moles of Fe2+ in 25.0 cm3,\n(iii) moles of KMnO4 reduced,\n(iv) concentration of KMnO4 in mol/L.",
      a: "(a) Any two of: pure, solid, soluble, stable on storage, not hygroscopic (does not absorb water), not easily air-oxidised, high molecular mass, readily available, low toxicity.\n\n(b)(i) Dissolve in a beaker containing dilute sulfuric acid. Add rinsings of the clock glass to the beaker. Transfer to a 250 cm3 volumetric flask using a funnel. Add rinsings of beaker, funnel, and glass rod to the flask. Add deionised water carefully near the mark using a dropper until the bottom of the meniscus is on the mark. Stopper and invert several times to mix.\n(b)(ii) To prevent air oxidation of Fe2+ to Fe3+, and to prevent hydrolysis of Fe2+ ions.\n\n(c)(i) The first faint permanent pink colour remains in the conical flask (KMnO4 is self-indicating).\n(c)(ii) A brown precipitate (solid) would form. This is MnO2 -- in insufficient acid, Mn7+ is reduced to Mn4+ (forming MnO2) instead of Mn2+.\n\n(d)(i) Mr = 392. Mass per litre = 9.31 x 4 = 37.24 g/L. Concentration = 37.24 / 392 = 0.095 mol/L.\n(d)(ii) 0.095 x 25.0/1000 = 0.002375 moles Fe2+ in 25.0 cm3.\n(d)(iii) Fe2+:KMnO4 = 5:1. So 0.002375 / 5 = 0.000475 moles KMnO4.\n(d)(iv) 0.000475 x 1000/22.6 = 0.021 M KMnO4.\n\nWhy: This is a self-indicating titration -- purple KMnO4 acts as its own indicator. The first permanent pink shows all Fe2+ has reacted. The 5:1 mole ratio from the equation is essential for the calculation."
    },
    {
      num: 2,
      label: "Q2: Organic Preparations (Ethyne)",
      q: "(a)(i) Draw a labelled diagram for the preparation of ethyne from calcium carbide reacting with water, and collection of the gas over water in test tubes.\n(a)(ii) Why is the first test tube of gas less pure than the others?\n\n(b)(i) What was observed when bromine solution was added to ethyne?\n(b)(ii) What was observed when acidified KMnO4 was added?\n(b)(iii) What information do these test results give about ethyne?\n\n(c)(i) How would you confirm ethyne is flammable?\n(c)(ii) Describe the flame observed when ethyne burns in air.\n(c)(iii) Write a balanced equation for combustion of ethyne in excess oxygen.\n(c)(iv) How does the oxyacetylene welding flame differ from burning in air?\n\n(d) Calculate the maximum volume of ethyne (at RTP, molar volume 24.0 L) from 2.0 g of calcium carbide that is 80% pure.\nEquation: CaC2 + 2H2O -> C2H2 + Ca(OH)2.",
      a: "(a)(i) Diagram: flask or bottle containing calcium carbide (CaC2), with water added via a dropping funnel or tap funnel. Delivery tube leads to a water trough where gas is collected in inverted test tubes over water. Label calcium carbide and water.\n(a)(ii) The first test tube contains air (oxygen, nitrogen) that was already present in the apparatus.\n\n(b)(i) Brown/orange colour decolourises to colourless.\n(b)(ii) Purple/pink colour decolourises to colourless.\n(b)(iii) Ethyne is unsaturated -- it contains a multiple bond (triple bond) and undergoes addition reactions.\n\n(c)(i) Insert a lighting taper into (or hold over) the mouth of the test tube.\n(c)(ii) Bright (luminous), yellow, sooty/smoky flame.\n(c)(iii) 2C2H2 + 5O2 -> 4CO2 + 2H2O.\n(c)(iv) The oxyacetylene flame is hotter, cleaner (no soot), less bright, and blue.\n\n(d) Mr of CaC2 = 64. Pure CaC2 = 80% of 2.0 g = 1.6 g. Moles CaC2 = 1.6/64 = 0.025. From the equation, 1 mol CaC2 produces 1 mol C2H2. Volume = 0.025 x 24.0 = 0.6 litres.\n\nWhy: Ethyne (C2H2) has a high carbon-to-hydrogen ratio, so it burns with a very smoky flame in air (incomplete combustion). In pure oxygen, combustion is complete, giving a much hotter blue flame suitable for welding."
    },
    {
      num: 3,
      label: "Q3: Heat of Reaction (Neutralisation)",
      q: "A student measured the heat of reaction for:\nHCl(aq) + NaOH(aq) -> NaCl(aq) + H2O(l)\n\nUsing a polystyrene cup, 50 cm3 of 1.0 M HCl was mixed with 50 cm3 of 1.0 M NaOH (both at room temperature). The temperature rose by 6.8 K then began to fall slowly.\n\n(a) Define heat of reaction.\n(b) State (i) one advantage, (ii) one disadvantage of using a 50 cm3 burette to measure and add the base.\n(c)(i) Why did the temperature rise?\n(c)(ii) Why did it then begin to fall gradually?\n(c)(iii) Explain the advantage of using polystyrene rather than glass.\n(d) Calculate:\n(i) moles of HCl neutralised,\n(ii) heat produced in kJ (density of NaCl solution = 1.0 g/cm3, specific heat capacity = 4.2 kJ/kg/K),\n(iii) dH in kJ/mol.\n(e)(i) Why does using 1.0 M solutions instead of 0.1 M give more accurate results?\n(e)(ii) Why would the same temperature rise (6.8 K) occur with 150 cm3 of each 1.0 M solution?",
      a: "(a) Heat of reaction: the heat change (energy released or absorbed) when the amounts of reactants shown in a balanced equation react completely.\n\n(b)(i) Advantage: accurate volume measurement.\n(b)(ii) Disadvantage: slow to add -- allows heat loss to surroundings.\n\n(c)(i) The reaction is exothermic -- heat is given out when acid neutralises base.\n(c)(ii) Heat loss to the surroundings, since the polystyrene cup is not a perfect insulator and the solution is hotter than the room.\n(c)(iii) Polystyrene is a much better insulator than glass (lower heat capacity). Glass absorbs significant heat and would need its heat capacity factored into the calculation.\n\n(d)(i) Moles HCl = 50 x 1.0 / 1000 = 0.05 moles.\n(d)(ii) Total solution mass = 100 cm3 x 1.0 g/cm3 = 100 g = 0.1 kg. Heat = mcdT = 0.1 x 4.2 x 6.8 = 2.856 kJ.\n(d)(iii) dH = -2.856 / 0.05 = -57.1 kJ/mol (accept -57.1 to -58 kJ/mol). The negative sign is essential for an exothermic reaction.\n\n(e)(i) The 1.0 M solutions produce a bigger temperature rise (6.8 K vs about 0.68 K), so the percentage error in reading the thermometer is much smaller.\n(e)(ii) Three times more heat is produced (three times more moles react), but three times more solution absorbs that heat (three times the mass). The ratio heat/mass is the same, so dT is the same.\n\nWhy: dH must be negative for exothermic reactions. The temperature rise is independent of volume for the same concentration, because both heat produced and heat capacity scale linearly with volume."
    },
    {
      num: 4,
      label: "Q4: Short Questions (Mixed Topics)",
      q: "Answer eight of the following:\n(a) Define (i) atomic number, (ii) mass number.\n(b) Write the formula for the simplest compound of gallium (valency 3) with (i) nitrogen, (ii) oxygen.\n(c) Predict the two possible shapes of molecule ABn where n = 2.\n(d) Identify the energy change: X+(g) -> X2+(g) + e-.\n(e) What is diffusion?\n(f) In a mass spectrometer, identify the processes at stages 2 and 4.\n(g) 25.0 cm3 of 0.12 M solution diluted to 30.0 cm3. Find the new concentration.\n(h) What is an enzyme?\n(i) Draw the structure of propane-1,2,3-triol (glycerol) showing all atoms and bonds.\n(j) Give the oxidation number of sulfur in (i) SO4 2-, (ii) Na2S4O6.\n(k) Calculate the minimum number of molecules of 2-methoxybenzoic acid (Mr = 152) in a 250 g jar of manuka honey, certified to contain at least 1 x 10^-3 g per kg.\n(l) A: Balanced equation(s) for limestone as a scrubber for SO2. OR B: Explain why metallic crystals conduct electricity.",
      a: "(a)(i) Atomic number: the number of protons in the nucleus of an atom.\n(a)(ii) Mass number: the total number of protons and neutrons in the nucleus.\n\n(b)(i) GaN. (ii) Ga2O3.\n\n(c) V-shape (bent/angular) and linear.\n\n(d) Second ionisation energy.\n\n(e) Diffusion: the spreading (movement) of a substance from a region of high concentration to a region of low concentration.\n\n(f) Stage 2: ionisation. Stage 4: separation (by magnetic field based on mass/charge ratio).\n\n(g) C1V1 = C2V2. 25.0 x 0.12 = 30.0 x M. M = 0.1 M.\n\n(h) An enzyme is a biological catalyst -- a protein that alters the rate of a biochemical reaction.\n\n(i) Three carbon chain, each C bonded to H atoms and an OH group: HOCH2-CHOH-CH2OH with all atoms and bonds shown explicitly.\n\n(j)(i) Sulfur in SO4 2-: +6 (VI).\n(j)(ii) In Na2S4O6: average oxidation number = +2.5 (two S at +2, two S at +3).\n\n(k) Mass per kg = 1 x 10^-3 g. Moles per kg = 0.001/152 = 6.6 x 10^-6. Molecules per kg = 6.6 x 10^-6 x 6.0 x 10^23 = 3.96 x 10^18. Per 250 g jar (1/4 kg) = 3.96 x 10^18 / 4 = approx 1 x 10^18 molecules (to 1 significant figure).\n\n(l) A: CaCO3 + SO2 -> CaSO3 + CO2 (balanced, with correct formulae).\nB: Valence electrons in metals are delocalised -- free to move through the lattice of positive metal ions, carrying an electric current.\n\nWhy: For dilution, use C1V1 = C2V2. For oxidation numbers, the sum of all oxidation numbers must equal the overall charge of the ion or molecule."
    },
    {
      num: 5,
      label: "Q5: Atomic Theory & Electronegativity",
      q: "(a)(i) How did Thomson account for atoms being electrically neutral?\n(a)(ii) State one piece of evidence for the existence of energy levels in atoms.\n(a)(iii) State two limitations of Bohr's atomic theory that led to its modification.\n(a)(iv) Define an atomic orbital.\n(a)(v) Write the s, p, d electron configuration for bromine in its ground state.\n\n(b) Electronegativity trends (graph given for Period 2 and Group 17):\n(b)(i) Define electronegativity.\n(b)(ii) Account for the increase in electronegativity across the second period.\n(b)(iii) Explain why electronegativity decreases down Group 17.\n(b)(iv) Predict the type of bonding in BrCl.\n(b)(v) Which atom in an O-F bond in OF2 has the partial negative charge? Justify.",
      a: "(a)(i) Thomson's plum pudding model: negative electrons are embedded in a sphere of positive matter, with equal positive and negative charges, making the atom neutral.\n(a)(ii) Atomic line spectra (e.g. Balmer series of hydrogen) / flame tests / ionisation energies of elements.\n(a)(iii) Any two: only works for hydrogen (and He+ ion), not for multi-electron atoms; does not account for wave-particle duality of the electron; does not explain sublevels or orbitals; does not explain splitting of spectral lines (high-resolution spectra); Heisenberg uncertainty principle not included.\n(a)(iv) A region of space (volume) around the nucleus of an atom where there is a high probability of finding an electron.\n(a)(v) 1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p5.\n\n(b)(i) Electronegativity: a number expressing the relative attraction of an atom (nucleus) for a shared pair of electrons in a covalent bond.\n(b)(ii) Across Period 2: nuclear charge (number of protons) increases while shielding remains roughly constant, so effective nuclear charge increases, attracting bonding electrons more strongly.\n(b)(iii) Down Group 17: atomic radius increases, more electron shells mean more shielding, so despite increasing nuclear charge, the attraction for bonding electrons decreases.\n(b)(iv) Polar covalent bonding (both are non-metals, but with different electronegativities).\n(b)(v) Fluorine has the partial negative charge (delta-). Fluorine is more electronegative than oxygen, so it attracts the shared pair of electrons more strongly.\n\nWhy: All electronegativity trends are driven by effective nuclear charge. Across a period: more protons, same shielding. Down a group: more shells provide additional shielding despite more protons."
    },
    {
      num: 6,
      label: "Q6: Alkanes & Thermochemistry",
      q: "(a)(i) What is a hydrocarbon?\n(a)(ii) Why are alkanes described as saturated?\n\n(b) Pentane and 2-methylbutane are structural isomers of C5H12. Give the IUPAC name and draw the structure of the other isomer.\n\n(c) C15H32 was catalytically cracked into 2-methylbutane, but-1-ene, and one other molecule. What is the molecular formula of the third molecule?\n\n(d) Calculate the heat of combustion of C15H32.\nC15H32(l) + 23O2(g) -> 15CO2(g) + 16H2O(l)\nHf values: C15H32 = -428.8, CO2 = -393.5, H2O = -285.8 kJ/mol.\n\n(e)(i) What difference in molecular formula between successive alkanes accounts for the near-linear trend in heats of combustion?\n(e)(ii) Estimate the difference in dH of combustion between successive alkanes from the graph.",
      a: "(a)(i) A hydrocarbon is a compound containing only carbon and hydrogen atoms.\n(a)(ii) Saturated means all carbon-carbon bonds are single bonds -- no C=C double bonds or triple bonds.\n\n(b) 2,2-dimethylpropane (neopentane). Structure: a central carbon atom bonded to four CH3 groups, i.e. C(CH3)4.\n\n(c) Balancing atoms: C15H32 -> C5H12 + C4H8 + CxHy. Carbon: 15 = 5 + 4 + x, so x = 6. Hydrogen: 32 = 12 + 8 + y, so y = 12. The third molecule is C6H12.\n\n(d) dH combustion = [15(-393.5) + 16(-285.8)] - [-428.8] = [-5902.5 + (-4572.8)] - [-428.8] = -10475.3 + 428.8 = -10046.5 kJ/mol.\n\n(e)(i) Each successive member differs by one CH2 group (one extra carbon and two extra hydrogens).\n(e)(ii) Approximately 650 kJ/mol difference between successive members.\n\nWhy: In catalytic cracking, total atoms must balance. The near-linear trend in heats of combustion occurs because each additional CH2 group contributes approximately the same amount of energy when burned."
    },
    {
      num: 7,
      label: "Q7: Acids, Bases & Water Treatment",
      q: "(a)(i) Define an acid (Bronsted-Lowry theory).\n(a)(ii) What is a strong acid?\n(a)(iii) Identify the conjugate base of HOCl.\n(a)(iv) Identify the conjugate acid of HSO4-.\n\n(b) Calculate the pH (to 1 d.p.) of:\n(i) 0.04 M sulfuric acid (strong, dibasic),\n(ii) 0.04 M chloric(I) acid (Ka = 3.0 x 10^-8).\n\n(c)(i) Identify two processes that remove suspended solids in water treatment.\n(c)(ii) 1.24 g of suspended solids collected from 800 cm3 of water. Calculate concentration in p.p.m.\n\n(d)(i) Write a balanced equation for aluminium sulfate reacting with sodium phosphate (Na3PO4) to form insoluble AlPO4 and soluble Na2SO4.\n(d)(ii) Describe how to test for the nitrate ion in aqueous solution.",
      a: "(a)(i) An acid is a proton (H+) donor.\n(a)(ii) A strong acid is one that is fully dissociated (completely ionised) in aqueous solution.\n(a)(iii) Conjugate base of HOCl: OCl-.\n(a)(iv) Conjugate acid of HSO4-: H2SO4.\n\n(b)(i) H2SO4 is dibasic (donates 2 H+): [H+] = 2 x 0.04 = 0.08 M. pH = -log(0.08) = 1.1.\n(b)(ii) Ka = [H+][OCl-]/[HOCl] = x^2/0.04 = 3.0 x 10^-8. x^2 = 1.2 x 10^-9. x = 3.46 x 10^-5 M. pH = -log(3.46 x 10^-5) = 4.5.\n\n(c)(i) Flocculation (using aluminium sulfate to clump particles) and filtration (through sand beds).\n(c)(ii) 1.24 g in 800 cm3. Concentration = 1.24/0.8 = 1.55 g/L = 1550 mg/L = 1550 p.p.m.\n\n(d)(i) Al2(SO4)3 + 2Na3PO4 -> 2AlPO4 + 3Na2SO4.\n(d)(ii) Add sodium hydroxide solution and aluminium foil (or Devarda's alloy) to the sample in a test tube. Heat gently. If nitrate ions are present, ammonia gas is produced. Test with damp red litmus paper held over the test tube -- it turns blue.\n\nWhy: Strong acids fully dissociate, so [H+] is calculated directly from concentration and basicity. Weak acids only partially dissociate -- use the Ka expression, assuming [H+] = [A-] = x."
    },
    {
      num: 8,
      label: "Q8: Organic Reaction Scheme",
      q: "A reaction scheme shows conversions between ethanol, ethene, poly(ethene), ethane, chloroethane and other products. Conversions labelled A through E.\n\n(a)(i) What is an elimination reaction?\n(a)(ii) Identify the elimination reaction in the scheme.\n\n(b) The same reactant and metal catalyst are used in conversions B and E.\nIdentify (i) the reactant, (ii) a suitable metal catalyst.\n\n(c)(i) Draw two repeating units of poly(ethene).\n(c)(ii) How does the geometry around carbon atoms change during polymerisation (conversion C)?\n\n(d)(i) Identify the inorganic product of conversion A.\n(d)(ii) Traces of butane are formed during conversion A. Explain how this is evidence for the mechanism.",
      a: "(a)(i) An elimination reaction is one in which atoms or groups are removed from adjacent atoms in a molecule, resulting in the formation of a double bond and a small molecule (e.g. H2O or HCl).\n(a)(ii) The dehydration of ethanol to form ethene is the elimination reaction (removal of H2O).\n\n(b)(i) Hydrogen gas (H2).\n(b)(ii) Nickel (Ni), or platinum (Pt), or palladium (Pd).\n\n(c)(i) Two repeating units of poly(ethene): -CH2-CH2-CH2-CH2- (with continuation bonds at each end).\n(c)(ii) Changes from trigonal planar (120 degrees, around each C in C=C) to tetrahedral (109.5 degrees) as the double bond opens to form single bonds during polymerisation.\n\n(d)(i) Water (H2O) -- produced during the dehydration of ethanol to ethene.\n(d)(ii) Butane (C4H10) forms when two ethyl radicals (C2H5*) combine during the termination step: C2H5* + *C2H5 -> C4H10. This can only occur if free radicals exist as reaction intermediates, providing evidence for a free radical mechanism.\n\nWhy: Free radical substitution has three stages: initiation (radical formation by UV/heat), propagation (chain reaction), and termination (radicals combine). The unexpected by-product butane proves radicals were present."
    },
    {
      num: 9,
      label: "Q9: Electrochemistry",
      q: "Questions on electrochemical cells, electrode potentials, and redox reactions.",
      a: "Key points for 2023:\n- Oxidation = loss of electrons (occurs at the anode). Reduction = gain of electrons (occurs at the cathode). Remember: AN OX, RED CAT.\n- In electrolytic cells: anode is positive, cathode is negative (external power source forces non-spontaneous reaction).\n- In galvanic (voltaic) cells: anode is negative, cathode is positive (spontaneous reaction generates electricity).\n- Standard electrode potential: measured relative to the standard hydrogen electrode (SHE), under standard conditions (1 M, 1 atm, 25 degrees C).\n- More negative electrode potential = more easily oxidised = better reducing agent.\n- Cell EMF = E(cathode) - E(anode).\n- Electrochemical series: metals listed in order of electrode potential. Metals above hydrogen are oxidised more easily.\n\nWhy: OIL RIG (Oxidation Is Loss, Reduction Is Gain) and AN OX RED CAT (Anode Oxidation, Reduction Cathode) are essential mnemonics. The electrochemical series predicts which reactions are spontaneous."
    },
    {
      num: 10,
      label: "Q10: Chemical Bonding & Shapes",
      q: "Questions on types of chemical bonding, molecular shapes (VSEPR), and intermolecular forces.",
      a: "Key points for 2023:\n- Ionic bonding: transfer of electrons from metal to non-metal. Strong electrostatic attraction between oppositely charged ions.\n- Covalent bonding: sharing of electron pairs between non-metals. Polar if atoms have different electronegativities.\n- VSEPR theory: molecular shape depends on the number of electron pairs around the central atom.\n  2 bonding pairs, 0 lone pairs = linear (180 degrees)\n  3 bonding pairs, 0 lone pairs = trigonal planar (120 degrees)\n  4 bonding pairs, 0 lone pairs = tetrahedral (109.5 degrees)\n  3 bonding pairs, 1 lone pair = pyramidal (107 degrees)\n  2 bonding pairs, 2 lone pairs = V-shape/bent (104.5 degrees)\n- Intermolecular forces (weakest to strongest): van der Waals < dipole-dipole < hydrogen bonding.\n- Hydrogen bonding occurs when H is bonded directly to F, O, or N.\n- Intermolecular forces determine physical properties (boiling point, solubility).\n\nWhy: Molecular shape determines polarity, which determines intermolecular forces, which determine physical properties. Lone pairs repel more strongly than bonding pairs, compressing bond angles."
    },
    {
      num: 11,
      label: "Q11: Environmental & Industrial Chemistry",
      q: "Questions on water treatment, sewage treatment, and atmospheric chemistry.",
      a: "Key points for 2023:\n- Water treatment stages: screening, settling/sedimentation, flocculation (aluminium sulfate added), filtration (sand beds), chlorination (kills bacteria), fluoridation (dental health), pH adjustment (lime).\n- Sewage treatment: primary (physical -- screening and settling), secondary (biological -- activated sludge with aerobic bacteria), tertiary (chemical -- remove phosphates using aluminium sulfate).\n- Acid rain: caused by SO2 (from burning sulfur-containing fossil fuels) and NOx (from high-temperature combustion). SO2 + H2O -> H2SO3. Damages buildings, lakes, forests.\n- Greenhouse effect: CO2, CH4, N2O and water vapour absorb and re-emit infrared radiation, trapping heat.\n- Ozone layer: O3 in the stratosphere absorbs UV radiation. CFCs release chlorine radicals (Cl*) which catalytically destroy ozone: Cl* + O3 -> ClO* + O2, then ClO* + O -> Cl* + O2.\n- BOD (biochemical oxygen demand): amount of dissolved oxygen consumed by microorganisms in decomposing organic matter. High BOD = polluted water.\n\nWhy: Environmental chemistry links to real-world applications. The key distinction is between water treatment (making water safe to drink) and sewage treatment (cleaning wastewater before discharge)."
    }
  ],
  "2024": [
    {
      num: 1,
      label: "Q1: Volumetric Analysis (Vinegar Titration)",
      q: "A student determined the concentration of ethanoic acid in vinegar. A 10.0 cm3 portion was diluted to exactly 50.0 cm3. The diluted vinegar was titrated against 0.09 M NaOH in a conical flask.\n\nMean titre: 12.4 cm3 of diluted vinegar to neutralise 25.0 cm3 of NaOH.\nEquation: CH3COOH + NaOH -> CH3COONa + H2O\n\n(a)(i) Name the apparatus to measure 10.0 cm3 of vinegar accurately.\n(a)(ii) How was this apparatus rinsed before use?\n(a)(iii) Describe how to dilute 10.0 cm3 of vinegar to exactly 50.0 cm3.\n\n(b)(i) Calculate the volume of undiluted vinegar needed to neutralise 25.0 cm3 of NaOH.\n(b)(ii) What is the advantage of diluting the vinegar before titration?\n\n(c)(i) Name a suitable indicator.\n(c)(ii) State the colour change at the end point.\n\n(d) Calculate:\n(i) moles of NaOH in 25.0 cm3,\n(ii) moles of ethanoic acid per cm3 of diluted vinegar,\n(iii) concentration of ethanoic acid in the original vinegar in mol/L,\n(iv) concentration in % (w/v).",
      a: "(a)(i) Pipette (or burette).\n(a)(ii) Rinse first with deionised water, then with vinegar.\n(a)(iii) Add 10.0 cm3 of original vinegar to a 50 cm3 volumetric flask. Add deionised water to bring the bottom of the meniscus to the 50 cm3 mark.\n\n(b)(i) Dilution factor = 50/10 = 5. Volume of undiluted vinegar = 12.4 / 5 = 2.48 cm3 (accept 2.5).\n(b)(ii) Diluting gives a larger volume to measure, which reduces the percentage error and gives a more accurate result.\n\n(c)(i) Phenolphthalein.\n(c)(ii) Pink to colourless (the NaOH in the flask starts pink with phenolphthalein; when enough acid is added, it turns colourless).\n\n(d)(i) Moles NaOH = 0.09 x 25.0/1000 = 0.00225 moles.\n(d)(ii) 1:1 mole ratio. Moles CH3COOH per cm3 of diluted vinegar = 0.00225/12.4 = 0.000181 mol/cm3.\n(d)(iii) Per litre of diluted vinegar: 0.000181 x 1000 = 0.181 M. Original vinegar (x5): 0.181 x 5 = 0.91 M.\n(d)(iv) Mr of CH3COOH = 60. Concentration in g/L = 0.91 x 60 = 54.6 g/L. As % (w/v) = 54.6/10 = 5.46% (divide by 10 because %(w/v) = g per 100 cm3).\n\nWhy: The vinegar was diluted 5-fold before titration, so multiply the final concentration by 5 to get the original concentration. For %(w/v): convert mol/L to g/L using Mr, then divide by 10 for g/100 cm3."
    },
    {
      num: 2,
      label: "Q2: Organic Chemistry (Recrystallisation, Ethanal, Soap)",
      q: "(a) Recrystallisation of benzoic acid using water:\n(i) Why is water a suitable solvent?\n(ii) What is the purpose of the hot filtration?\n(iii) Why use fluted filter paper in a warm funnel for the hot filtration?\n(iv) Why is the second filtration only carried out after sufficient cooling?\n(v) What observation shows the recrystallised benzoic acid is pure?\n\n(b) Testing ethanal for easy oxidation:\n(i) Identify the reagent(s).\n(ii) State the colour change.\n(iii) Identify the organic product.\n(iv) Write a half equation for the reduction of the inorganic reagent.\n\n(c) Preparation of soap:\n(i) Identify the reactants.\n(ii) Identify the solvent.\n(iii) Name the co-product and draw its molecular structure (all atoms and bonds).",
      a: "(a)(i) Benzoic acid has low solubility in cold water but high solubility in hot water -- ideal for recrystallisation.\n(a)(ii) To remove insoluble impurities (e.g. charcoal, dirt).\n(a)(iii) Fluted paper has increased surface area for faster filtration. The warm funnel keeps the solution hot, preventing benzoic acid from crystallising in the funnel and increasing yield.\n(a)(iv) To allow maximum crystallisation of pure benzoic acid, maximising yield.\n(a)(v) Sharp melting point over a narrow range, close to the correct value (122 degrees C).\n\n(b)(i) Acidified KMnO4, OR Fehling's solution (A and B), OR Tollen's reagent.\n(b)(ii) KMnO4: purple/pink to colourless. Fehling's: blue to red. Tollen's: colourless to silver mirror.\n(b)(iii) Ethanoic acid (CH3COOH) -- the aldehyde is oxidised to the carboxylic acid.\n(b)(iv) KMnO4: Mn7+ + 5e- -> Mn2+. Fehling's: Cu2+ + e- -> Cu+. Tollen's: Ag+ + e- -> Ag.\n\n(c)(i) Fat (oil/triglyceride, e.g. glyceryl tristearate) AND sodium hydroxide (or KOH).\n(c)(ii) Ethanol.\n(c)(iii) Propane-1,2,3-triol (glycerol). Structure: HOCH2-CHOH-CH2OH -- three-carbon chain with an OH group on each carbon, all H atoms and bonds shown.\n\nWhy: Recrystallisation works because solubility increases with temperature. Ethanal is an aldehyde -- easily oxidised to ethanoic acid. Soap-making (saponification) is the alkaline hydrolysis of a fat/oil into soap and glycerol."
    },
    {
      num: 3,
      label: "Q3: Rates of Reaction (Na2S2O3 + HCl)",
      q: "Na2S2O3 + 2HCl -> 2NaCl + SO2 + S + H2O\n\nInvestigating the effect of concentration on rate. For each run, 100 cm3 of Na2S2O3 mixed with 10 cm3 of 3 M HCl. Time measured for the same mass of sulfur to precipitate. Rate = 1/time.\n\nData: Concentration (M): 0.10, 0.09, 0.08, 0.07, 0.06, 0.05, 0.04, 0.03.\nTime (s): 50, 56, 63, 72, 84, 100, 125, 168.\n\n(a)(i) Describe a method to know when the same mass of sulfur has precipitated in each run.\n(a)(ii) How would you prepare 100 cm3 of 0.09 M from 0.10 M Na2S2O3?\n\n(b)(i) Complete the rate values (1/time) to 3 decimal places.\n(b)(ii) Draw a graph of rate vs concentration on graph paper.\n(b)(iii) What can be concluded from the graph?\n\n(c)(i) Use the graph to estimate the rate at 0.015 M.\n(c)(ii) Calculate the time for sulfur to precipitate at this rate.\n\n(d) Effect of temperature (times: T1 = 40 s, T2 = 10 s, T3 = 25 s):\n(i) Describe a suitable method for heating and measuring temperature.\n(ii) Which temperature was highest? Justify.",
      a: "(a)(i) Place an X (a marked cross) under the flask/beaker. Start the timer when the reactants are mixed. Measure the time until the X is no longer visible through the precipitated sulfur. Using the same X each time ensures the same mass of sulfur has precipitated.\n(a)(ii) Measure 90 cm3 of 0.10 M Na2S2O3 and add 10 cm3 of deionised water to make 100 cm3. Check: C1V1 = C2V2: 0.10 x 90 = 0.09 x 100.\n\n(b)(i) Rate values: 0.016, 0.014, 0.012, 0.010, 0.008, 0.006.\n(b)(ii) Plot rate on y-axis and concentration on x-axis. Label both axes with units. Plot all 8 points. Draw a line of best fit (should be a straight line through or near the origin).\n(b)(iii) Rate is directly proportional to concentration (a straight line through the origin shows a first-order relationship).\n\n(c)(i) From the graph, at 0.015 M: rate is approximately 0.003 s^-1.\n(c)(ii) Time = 1/rate = 1/0.003 = 333 seconds (approximately 5.5 minutes).\n\n(d)(i) Use a water bath (beaker of warm water heated by a hotplate or Bunsen burner). Place both reactant solutions in the water bath to reach the desired temperature. Use a thermometer in the reaction mixture to measure the temperature.\n(d)(ii) T2 was the highest temperature. Justification: T2 had the shortest time (10 s), meaning the fastest rate. Higher temperature = more kinetic energy = more effective collisions = faster reaction.\n\nWhy: Rate is proportional to concentration for a first-order reaction. The disappearing-X method is a classic way to measure reaction rate by keeping the endpoint consistent. Higher temperature always increases rate because molecules have more kinetic energy."
    },
    {
      num: 4,
      label: "Q4: Short Questions (Mixed Topics)",
      q: "Answer eight of the following:\n(a) How many (i) protons, (ii) neutrons are in helium-3?\n(b) Identify two reagents to test for phosphate ions in solution.\n(c) State two reasons why real gases deviate from ideal behaviour.\n(d) Two identical flasks at same T and P: one has He, one has 2.4 g of O2. Calculate mass of He.\n(e) Standard units of (i) first ionisation energy, (ii) BOD.\n(f) Name three homologous series containing a carbonyl group.\n(g)(i) Why are oxygenates added to petrol? (ii) Identify a suitable oxygenate.\n(h) Purpose of aluminium sulfate in (i) water treatment, (ii) tertiary sewage treatment.\n(i) Write a balanced half equation for the cathode reaction in electrolysis of aqueous Na2SO4.\n(j) Explain the fundamental principle of chromatography.\n(k) Calculate % yield when 2412.3 g of benzocaine (Mr = 165) was obtained from a theoretical yield of 21.5 moles.\n(l) A: Three chemical species formed when CO2 dissolves in pure water. OR B: Contributions of Lawrence Bragg and Dorothy Hodgkin to crystallography.",
      a: "(a)(i) 2 protons. (ii) 1 neutron (mass number 3 - atomic number 2 = 1).\n\n(b) Ammonium molybdate and nitric acid. A yellow precipitate confirms phosphate.\n\n(c) Any two: gas particles have volume (not zero-volume point masses); intermolecular forces exist between particles; collisions are not perfectly elastic.\n\n(d) Same T, P, and volume = same number of moles (Avogadro's law). Moles O2 = 2.4/32 = 0.075 mol. Mass He = 0.075 x 4 = 0.3 g.\n\n(e)(i) kJ mol^-1. (ii) ppm (or mg/L).\n\n(f) Any three of: aldehydes, ketones, carboxylic acids, esters.\n\n(g)(i) To increase the octane number, reducing auto-ignition (knocking) and giving smoother combustion.\n(g)(ii) Ethanol, or MTBE (methyl tert-butyl ether).\n\n(h)(i) Water treatment: to cause flocculation (small suspended particles clump together for easier removal).\n(h)(ii) Tertiary sewage treatment: to remove phosphate ions (forms insoluble aluminium phosphate).\n\n(i) 2H2O + 2e- -> H2 + 2OH- (water is reduced at the cathode to produce hydrogen gas).\n\n(j) Chromatography separates substances based on their different affinities for a mobile phase and a stationary phase. Components with greater affinity for the stationary phase move more slowly.\n\n(k) Mr = 165. Theoretical mass = 21.5 x 165 = 3547.5 g. % yield = (2412.3/3547.5) x 100 = 68%.\n\n(l) A: H2CO3, HCO3-, CO32-, H+ (any three species).\nB: (i) Lawrence Bragg: developed X-ray crystallography technique (Bragg's law). (ii) Dorothy Hodgkin: used X-ray crystallography to determine the structures of important biomolecules (penicillin, insulin, vitamin B12).\n\nWhy: Avogadro's law is key for part (d): equal volumes at same T and P contain equal moles. For percentage yield, compare actual yield (in grams) to theoretical yield (moles x Mr)."
    },
    {
      num: 5,
      label: "Q5: Atomic Structure (Bohr, Orbitals, Ionisation Energy)",
      q: "(a)(i) Explain what is meant by the term energy level.\n(a)(ii) Distinguish between the ground state and excited states of the electron in hydrogen.\n(a)(iii) What happens when an electron moves from an excited state to its ground state?\n(a)(iv) Name the instrument used to examine the line spectrum of an element.\n\n(b)(i) Explain how the Heisenberg uncertainty principle applies to an electron in an atom.\n(b)(ii) Write the full s, p electron configuration for neon in its ground state, including the number of electrons in each orbital.\n(b)(iii) Distinguish between an energy sublevel and an atomic orbital by reference to neon's configuration.\n(b)(iv) Why is neon chemically unreactive? (Reference its electron configuration.)\n(b)(v) How do the successive ionisation energies of neon provide evidence for energy levels?\n(b)(vi) Draw the shape of a p orbital.",
      a: "(a)(i) An energy level is a fixed (quantised) amount of energy that an electron in an atom may have. Electrons can only exist at these specific energy values, not between them.\n(a)(ii) Ground state: the electron occupies its lowest available energy level. Excited state: the electron has absorbed energy and moved to a higher energy level.\n(a)(iii) The electron releases energy as a photon of light. The energy (and therefore frequency/wavelength) of the photon equals the difference between the two energy levels (E = hf). This produces a spectral line.\n(a)(iv) Spectroscope (or spectrometer/diffraction grating).\n\n(b)(i) It is impossible to simultaneously know both the exact position and exact momentum (velocity) of an electron. We can only describe the probability of finding an electron in a region of space (an orbital).\n(b)(ii) 1s2 2s2 2p6. Showing orbitals: 1s2 2s2 2px2 2py2 2pz2.\n(b)(iii) An energy sublevel (e.g. 2p) is a set of orbitals of equal energy within a main energy level. An atomic orbital (e.g. 2px) is a single region of space within that sublevel, holding a maximum of 2 electrons. The 2p sublevel contains three orbitals (2px, 2py, 2pz).\n(b)(iv) Neon has a complete outer shell (2s2 2p6 = 8 electrons filling the second energy level). It has no tendency to gain, lose, or share electrons, making it chemically unreactive.\n(b)(v) The first 8 ionisation energies increase gradually (removing electrons from the n=2 level). Then there is a very large jump for the 9th ionisation energy (removing an electron from the n=1 level, much closer to the nucleus). This sudden jump provides direct evidence for distinct energy levels.\n(b)(vi) A p orbital is dumbbell-shaped: two lobes on either side of the nucleus, with a node at the nucleus.\n\nWhy: Bohr's model explained hydrogen's line spectrum but failed for multi-electron atoms. Modern quantum theory replaces fixed orbits with probability-based orbitals. Successive ionisation energies reveal how electrons are arranged in shells."
    },
    {
      num: 6,
      label: "Q6: Alkanes, Isomers & Thermochemistry",
      q: "Hydrocarbon A (in the naphtha fraction from crude oil) is converted to hydrocarbon B.\n\n(a)(i) What property does A share with other naphtha hydrocarbons?\n(a)(ii) Give the IUPAC names of compounds A and B.\n(a)(iii) Why are A and B called saturated alkanes?\n\n(b)(i) Name the process that converts A to B.\n(b)(ii) Why is this conversion carried out?\n\n(c) Catalytic cracking of compound A produces methylpropane and compound C.\n(i) Draw the molecular structure of methylpropane (all atoms and bonds).\n(ii) Name three possible isomers of compound C and draw their structures.\n\n(d)(i) Calculate the heat of combustion of compound A:\nCH3(CH2)6CH3(l) + 12.5O2(g) -> 8CO2(g) + 9H2O(l)\nHf: A = -250.3, CO2 = -393.5, H2O = -285.8 kJ/mol.\n(d)(ii) Calculate the heat of reaction for converting A to B, given Hf(B) = -260.5 kJ/mol.",
      a: "(a)(i) Similar boiling point range / similar molecular mass / liquid at room temperature.\n(a)(ii) A = octane. B = 2,2,4-trimethylpentane (isooctane).\n(a)(iii) All carbon-carbon bonds are single bonds -- there are no C=C double bonds or triple bonds.\n\n(b)(i) Isomerisation (or reforming/catalytic reforming).\n(b)(ii) To increase the octane number of the fuel. Branched-chain alkanes burn more smoothly (less knocking) than straight-chain alkanes.\n\n(c) A is octane (C8H18). C8H18 -> C4H10 (methylpropane) + C4H8 (compound C).\n(c)(i) Methylpropane: CH3-CH(CH3)-CH3, with all H atoms and bonds drawn.\n(c)(ii) C4H8 isomers (any three): but-1-ene (CH2=CHCH2CH3), but-2-ene (CH3CH=CHCH3), 2-methylpropene (CH2=C(CH3)2), cyclobutane. Draw each with all atoms and bonds.\n\n(d)(i) dH combustion = [8(-393.5) + 9(-285.8)] - [-250.3] = [-3148.0 + (-2572.2)] + 250.3 = -5720.2 + 250.3 = -5469.9 kJ/mol.\n(d)(ii) dH = Hf(B) - Hf(A) = -260.5 - (-250.3) = -260.5 + 250.3 = -10.2 kJ/mol (slightly exothermic).\n\nWhy: Isomerisation converts straight-chain to branched alkanes without changing the molecular formula. For conversions, dH = Hf(products) - Hf(reactants). The small negative value means the branched isomer is slightly more stable."
    },
    {
      num: 7,
      label: "Q7: Chemical Equilibrium",
      q: "4.0 moles of steam and 1.0 mole of CO mixed at temperature T in a container of fixed volume V.\nH2O(g) + CO(g) <=> H2(g) + CO2(g), dH = -38.8 kJ/mol\n\n(a)(i) Explain what is meant by chemical equilibrium.\n(a)(ii) Write an expression for Kc.\n(a)(iii) At equilibrium, there are 0.8 moles of H2. Calculate Kc.\n\n(b)(i) Starting with 2.5 moles each of steam and CO at the same T: explain why Kc does not change.\n(b)(ii) Calculate the mass of CO2 at equilibrium in this case.\n\n(c)(i) Effect of decreasing pressure on % conversion of steam to H2? Justify.\n(c)(ii) How could Kc be increased? Justify.\n(c)(iii) Effect of using a catalyst on Kc at temperature T? Justify.",
      a: "(a)(i) Chemical equilibrium: in a reversible reaction, the state where the rate of the forward reaction equals the rate of the reverse reaction, and the concentrations of all reactants and products remain constant.\n(a)(ii) Kc = [H2][CO2] / ([H2O][CO])\n(a)(iii) At equilibrium: H2 = 0.8 mol, CO2 = 0.8 mol (1:1 ratio). H2O = 4.0 - 0.8 = 3.2 mol. CO = 1.0 - 0.8 = 0.2 mol.\nKc = (0.8/V)(0.8/V) / ((3.2/V)(0.2/V)) = (0.8 x 0.8)/(3.2 x 0.2) = 0.64/0.64 = 1.0.\n(Note: V cancels because equal moles of gas on each side.)\n\n(b)(i) Kc depends only on temperature. Since the temperature is unchanged (still T), Kc stays at 1.0.\n(b)(ii) Let x mol of H2 and CO2 form. Kc = x^2/((2.5-x)(2.5-x)) = (x/(2.5-x))^2 = 1.0. So x/(2.5-x) = 1. Therefore x = 2.5 - x, giving 2x = 2.5, x = 1.25. Mass CO2 = 1.25 x 44 = 55 g.\n\n(c)(i) No effect on percentage conversion. There are 2 moles of gas on each side (1 mol H2O + 1 mol CO = 1 mol H2 + 1 mol CO2), so changing pressure does not shift the equilibrium.\n(c)(ii) Decrease the temperature. The forward reaction is exothermic (dH = -38.8 kJ). By Le Chatelier's principle, lowering the temperature favours the exothermic (forward) direction, increasing [products] relative to [reactants], thus increasing Kc.\n(c)(iii) A catalyst has no effect on Kc. A catalyst speeds up both forward and reverse reactions equally, so equilibrium is reached faster, but the equilibrium position (and Kc) remain unchanged.\n\nWhy: Kc is a constant at a given temperature. When equal moles of gas appear on both sides, the volume V cancels in the Kc expression, and pressure changes have no effect. Only temperature changes can alter Kc."
    },
    {
      num: 8,
      label: "Q8: Organic Reaction Mechanisms (Free Radical, PVC)",
      q: "Reaction scheme: ethene -> ethane (reaction A, hydrogenation), ethane + Cl2/UV -> chloroethane (reaction B), and a separate pathway: ethene -> compound X -> compound Y -> PVC.\n\n(a) How does the geometry around carbon atoms change during reaction A?\n\n(b) Reaction B (ethane + Cl2, UV light):\n(i) Is it addition, substitution, or elimination?\n(ii) Describe the mechanism for reaction B.\n(iii) How does trace C4H10 provide evidence for this mechanism?\n(iv) State one other piece of evidence.\n\n(c) PVC synthesis (ethene -> X -> Y -> PVC):\n(i) IUPAC name for compound X.\n(ii) Name the inorganic compound eliminated to form Y.\n(iii) Draw the structure of Y.\n(iv) Draw two repeating units of PVC.",
      a: "(a) Changes from trigonal planar (120 degrees around each carbon in the C=C double bond) to tetrahedral (109.5 degrees around each carbon in the C-C single bond).\n\n(b)(i) Substitution reaction (free radical substitution).\n(b)(ii) Mechanism:\nInitiation: Cl2 -> 2Cl* (UV light causes homolytic fission of the Cl-Cl bond, forming two chlorine free radicals).\nPropagation (chain reaction):\nStep 1: Cl* + C2H6 -> HCl + C2H5* (chlorine radical abstracts a hydrogen atom from ethane, forming an ethyl radical).\nStep 2: C2H5* + Cl2 -> C2H5Cl + Cl* (ethyl radical reacts with a Cl2 molecule, regenerating a chlorine radical).\nTermination: two radicals combine, e.g. Cl* + Cl* -> Cl2, or C2H5* + Cl* -> C2H5Cl, or C2H5* + C2H5* -> C4H10.\n(b)(iii) Butane (C4H10) can only form when two ethyl radicals (C2H5*) combine: C2H5* + C2H5* -> C4H10. This proves that free radicals exist as intermediates during the reaction.\n(b)(iv) The reaction only occurs in the presence of UV light (or sunlight), not in the dark. This shows that energy is needed to break the Cl-Cl bond homolytically in the initiation step.\n\n(c)(i) 1,2-dichloroethane (ClCH2CH2Cl).\n(c)(ii) Hydrogen chloride (HCl) is eliminated.\n(c)(iii) Chloroethene (vinyl chloride): CH2=CHCl.\n(c)(iv) PVC: -CH2-CHCl-CH2-CHCl- (two repeating units, with Cl attached to alternate carbon atoms).\n\nWhy: Free radical substitution requires UV light for initiation. The three stages (initiation, propagation, termination) explain all observations. The trace of butane from two ethyl radicals combining is classic evidence for free radical intermediates."
    },
    {
      num: 9,
      label: "Q9: Acids, Bases & pH",
      q: "Questions on acid-base definitions, conjugate pairs, pH calculations, and buffer solutions.",
      a: "Key points for 2024:\n- Bronsted-Lowry acid: proton (H+) donor. Base: proton (H+) acceptor.\n- Strong acid: fully dissociated in water. Weak acid: partially dissociated (equilibrium with undissociated form).\n- pH = -log[H+]. For strong acids: [H+] = concentration x number of acidic H atoms.\n- For weak acids: Ka = [H+][A-]/[HA]. Let [H+] = x, so Ka = x^2/c (where c = initial acid concentration). Solve for x.\n- Conjugate acid-base pairs differ by one proton (H+).\n- Kw = [H+][OH-] = 1.0 x 10^-14 at 25 degrees C. For pure water at 25 degrees C: pH = 7.\n- Buffer solution: resists pH changes when small amounts of acid or base are added. Made from a weak acid and its salt (conjugate base), or a weak base and its salt.\n\nWhy: Strong vs weak acid is the most important distinction. Strong acids: calculate [H+] directly. Weak acids: must use Ka. A buffer works because added H+ reacts with the conjugate base, and added OH- reacts with the weak acid."
    },
    {
      num: 10,
      label: "Q10: Periodic Table & Trends",
      q: "Questions on trends in ionisation energy, electronegativity, and atomic radius across periods and down groups.",
      a: "Key points for 2024:\n- First ionisation energy: the minimum energy required to remove the most loosely bound electron from a neutral gaseous atom in its ground state.\n- Across a period (left to right): ionisation energy generally increases. More protons (higher nuclear charge) with similar shielding gives greater effective nuclear charge, holding electrons more tightly.\n- Down a group: ionisation energy decreases. More electron shells mean greater shielding and larger atomic radius, so the outer electron is further from the nucleus and easier to remove.\n- Anomalies in Period 2: Be (1s2 2s2) > B (1s2 2s2 2p1) because the 2p electron is easier to remove than a 2s electron. N (half-filled 2p3) > O (2p4) because removing a paired electron from O is easier than removing from the stable half-filled 2p subshell of N.\n- Electronegativity follows the same trend as ionisation energy (increases across, decreases down).\n- Atomic radius decreases across a period and increases down a group.\n\nWhy: All periodic trends are ultimately governed by effective nuclear charge (protons minus shielding). Understanding this one concept explains ionisation energy, electronegativity, and atomic radius trends together."
    },
    {
      num: 11,
      label: "Q11: Applied & Environmental Chemistry",
      q: "Questions covering water treatment, industrial processes, and environmental chemistry topics.",
      a: "Key points for 2024:\n- Water treatment: screening, sedimentation, flocculation (aluminium sulfate causes small particles to aggregate), filtration (sand/gravel beds), chlorination (kills microorganisms), fluoridation (sodium fluoride or H2SiF6 for dental health), pH adjustment.\n- Sewage treatment: primary (physical removal of solids by screening and settling), secondary (biological treatment using activated sludge -- aerobic bacteria break down organic matter), tertiary (chemical removal of phosphates using aluminium sulfate to precipitate AlPO4).\n- Contact process for sulfuric acid: burn sulfur to get SO2, catalytic oxidation to SO3 (V2O5 catalyst, 450 degrees C, 1-2 atm), dissolve SO3 in concentrated H2SO4 to form oleum, dilute with water.\n- Haber process for ammonia: N2 + 3H2 <=> 2NH3, iron catalyst, 450 degrees C, 200 atm. Compromise: moderate temperature gives reasonable rate and yield.\n- Greenhouse effect, acid rain, ozone depletion -- know the chemistry, causes, and effects.\n- BOD (biochemical oxygen demand): mass of dissolved O2 consumed per litre by microorganisms over 5 days at 20 degrees C. Higher BOD = more organic pollution.\n\nWhy: Industrial processes balance thermodynamics (favourable yield) with kinetics (reasonable rate). The Haber process is the classic example: low temperature favours yield but is too slow, so a compromise temperature with a catalyst is used."
    }
  ]
};
