// LC English Walkthroughs Data (auto-generated)
var WALKTHROUGHS_ENGLISH = {
  "2022": [
    // ===== PAPER 1: COMPREHENDING (40 marks) =====
    // Theme: POWERFUL VOICES
    // 2022 format: Answer ONE question (either A or B) on ONE text only
    // NOTE: 2022 had reduced marks (P1: 140 total, Comprehending: 40, Composing: 100)
    {num:1, label:"P1: Text 1 - A Young Poet's Powerful Voice (Q A)",
     q:"TEXT 1 - A YOUNG POET'S POWERFUL VOICE\nAdapted from a feature article by Meadhbh McGrath entitled 'Poet. Fashion icon. Future president?' about Amanda Gorman.\n\nThe text describes how Amanda Gorman, the youngest inaugural poet in US history, captivated audiences at Joe Biden's inauguration with her poem 'The Hill We Climb'. Dressed in a sunshine yellow coat and scarlet satin headband, she delivered a mesmerising reading addressing national unity and reconciliation. The poem reckoned with America's pain while looking optimistically to the future. The inauguration showed how poetry can bring people together. Gorman gained 2 million Instagram followers overnight and her books hit numbers 1 and 2 on Amazon's bestseller list. She became the first poet to perform at the Super Bowl.\n\nQuestion A (40 marks)\n\n(i) Based on your reading of Text 1, identify four reasons why Amanda Gorman's reading of 'The Hill We Climb' attracted so much attention. Support your answer with reference to the text. (15)\n\n(ii) Select two examples of the writer's use of language in Text 1 that you found effective in engaging your interest. Explain your choices with reference to the text. (15)\n\n(iii) Based on your reading of Text 1, do you think Amanda Gorman is an admirable person? Give reasons for your answer with reference to the text. (10)",
     a:"MARKING CRITERIA (40 marks total):\nAll tasks assessed using P/C/L/M criteria:\n- Clarity of Purpose (P): 30% - Clear engagement with the set task\n- Coherence of Delivery (C): 30% - Sustained appropriate response\n- Efficiency of Language Use (L): 30% - Appropriate language management\n- Accuracy of Mechanics (M): 10% - Spelling and grammar accuracy\n\nQ A(i) - 15 marks: Four reasons Gorman attracted attention:\n- Youngest inaugural poet in US history - historic significance\n- Striking visual impact: 'sunshine yellow coat and scarlet satin headband'\n- Mesmerising five-minute reading - quality of performance\n- Poem addressed national unity at a pivotal moment in US history\n- Captured mood of a country reeling from 'pandemic, stark political divisions and domestic terrorism'\n- Poetry shown to bring people together by 'interrogating and articulating our shared feelings, fears and insecurities'\n- Catapulted to global fame: 2 million new Instagram followers, bestseller lists\n- First poet to perform at the Super Bowl\nStudents should identify FOUR distinct reasons and support each with textual reference.\n\nQ A(ii) - 15 marks: Effective language examples:\n- Vivid imagery: 'sunshine yellow coat and scarlet satin headband' - visual impact\n- Contrast/juxtaposition: 'never-ending shade' vs 'light' - captures the poem's message\n- Powerful verbs: 'stole the show', 'catapulted', 'reeling' - dynamic and engaging\n- Listing for cumulative effect: 'pandemic, stark political divisions and domestic terrorism'\n- Metaphor: poetry 'interrogating and articulating our shared feelings'\nMust select TWO examples and explain WHY each is effective - don't just identify the technique.\n\nQ A(iii) - 10 marks: Personal response with textual support.\nAdmirable qualities: youth, courage, talent, social awareness, ability to unite people.\nSupport with specific details from the text.\n\nApproach: In 2022, you only answer ONE question (A or B) on ONE text. Budget 40 minutes for comprehending. Use direct quotation. For (ii), focus on HOW the language works, not just WHAT it says."},
    {num:2, label:"P1: Text 1 - A Young Poet's Powerful Voice (Q B)",
     q:"TEXT 1 - A YOUNG POET'S POWERFUL VOICE\n\nQuestion B (40 marks)\n\nA functional writing task inspired by the theme of Text 1 and the idea of powerful voices. Students may be asked to write a speech, article, blog post, or personal essay connected to poetry, public speaking, or the power of language.\n\n(Refer to the full exam paper for exact wording of Question B on Text 1.)",
     a:"MARKING CRITERIA (40 marks total):\nAssessed using P/C/L/M criteria:\n- Clarity of Purpose (P): 30% (12 marks)\n- Coherence of Delivery (C): 30% (12 marks)\n- Efficiency of Language Use (L): 30% (12 marks)\n- Accuracy of Mechanics (M): 10% (4 marks)\n\nKey points for Question B:\n- Identify the FORMAT required and write in the correct register\n- Draw on ideas from Text 1 but add your own material\n- If writing a speech: direct address, rhetorical devices, persuasive tone\n- If writing an article: headline, engaging opening, balanced perspective\n- If writing a personal essay: reflective, introspective, anecdotal\n- Sustain the register throughout the piece\n\nApproach: This is a FUNCTIONAL WRITING task. The format matters as much as the content. Show you can write in a specific register for a specific audience and purpose."},
    {num:3, label:"P1: Text 2 (Q A & Q B)",
     q:"TEXT 2 - (Theme: POWERFUL VOICES)\n\nThe second text on the theme of Powerful Voices.\n\nQuestion A (40 marks):\nThree comprehension-style questions testing understanding, language analysis, and personal response. Typically 15 + 15 + 10 marks.\n\nQuestion B (40 marks):\nA functional writing task related to the theme of Text 2.\n\n(Refer to the full exam paper for the specific text and questions.)",
     a:"MARKING CRITERIA (40 marks total for either Q A or Q B):\n\nGeneral approach for Question A on any text:\n- Read the text at least twice before answering\n- Identify key themes, arguments, and stylistic features\n- Use direct quotation and close reference to the text\n- Answer ALL parts of each sub-question\n- Allocate time based on marks: 15-mark questions need more development than 10-mark ones\n\nGeneral approach for Question B:\n- Identify the FORMAT required (speech, article, letter, blog, report, etc.)\n- Write in the correct REGISTER for that format\n- Draw on ideas from the text as a springboard\n- Add your own ideas, examples, and perspectives\n- Sustain the format throughout\n\nApproach: In 2022, remember you only answer ONE question total in comprehending. Choose the text and question type (A or B) you feel most confident about."},
    {num:4, label:"P1: Text 3 (Q A & Q B)",
     q:"TEXT 3 - (Theme: POWERFUL VOICES)\n\nThe third text on the theme of Powerful Voices.\n\nQuestion A (40 marks):\nThree comprehension-style questions. Typically 15 + 15 + 10 marks.\n\nQuestion B (40 marks):\nA functional writing task related to the theme of Text 3.\n\n(Refer to the full exam paper for the specific text and questions.)",
     a:"MARKING CRITERIA (40 marks total):\nSame P/C/L/M criteria as other questions.\n\nApproach: Same principles as Text 1 and Text 2. Choose ONE question (A or B) on ONE text only."},
    // ===== PAPER 1: COMPOSING (100 marks) =====
    {num:5, label:"P1: Composing - All 7 Options",
     q:"SECTION II - COMPOSING (100 marks)\nTheme: POWERFUL VOICES\n\nWrite a composition on any ONE of the following. Each composition is connected to the theme of Powerful Voices.\n\n1. Write a personal essay about a voice - a person, a song, a speech, a poem - that has had a powerful impact on you.\n\n2. Write a short story in which a character finds the courage to use their voice in a moment of crisis.\n\n3. Write a discursive essay on the topic: 'In today's world, actions speak louder than words.'\n\n4. Write a descriptive piece inspired by the title: 'The Speech That Changed Everything.'\n\n5. Write an argumentative essay on the topic: 'Social media has given everyone a powerful voice - and that is not always a good thing.'\n\n6. Write a narrative essay exploring the idea that 'the most powerful voices are often the quietest.'\n\n7. Write a composition in response to the title: 'Silence.'\n\n(Note: Refer to the full exam paper for exact wording of all 7 options.)",
     a:"MARKING CRITERIA (100 marks total):\n- Clarity of Purpose (P): 30 marks\n- Coherence of Delivery (C): 30 marks\n- Efficiency of Language Use (L): 30 marks\n- Accuracy of Mechanics (M): 10 marks\n\nAdvice by composition type:\n\nPersonal Essay (Option 1):\n- Reflective, introspective tone\n- Use specific anecdotes and personal experience\n- Move between narrative moments and reflective insights\n- Show genuine emotional engagement\n\nShort Story (Option 2):\n- Strong opening hook\n- Developed characters with believable motivations\n- Clear plot arc: setup, rising action, climax, resolution\n- Show don't tell - use dialogue, imagery, sensory detail\n- Effective ending that resonates\n\nDiscursive Essay (Option 3):\n- Explore multiple perspectives fairly\n- Use evidence and examples to support points\n- Balanced argument with clear structure\n- Arrive at a nuanced, thoughtful conclusion\n\nDescriptive (Option 4):\n- Rich sensory language (sight, sound, touch, smell, taste)\n- Create atmosphere and mood\n- Use imagery, metaphor, simile\n- Focus on specific, vivid details\n\nArgumentative (Option 5):\n- Take a clear position from the outset\n- Use evidence and reasoning to persuade\n- Address counter-arguments and rebut them\n- Build to a strong, convincing conclusion\n\nNarrative (Option 6):\n- Compelling storytelling with developed characters\n- Show the quiet power through specific scenes\n- Use contrast between loud and quiet effectively\n\nOpen/Creative (Option 7):\n- Interpret the title creatively\n- Could be narrative, descriptive, reflective, or a combination\n- Show originality of thought\n\nApproach: Spend 5 minutes planning before writing. Choose the option that plays to your strengths. Aim for 3-4 pages minimum. Quality of language matters as much as content. Strong openings and closings are essential."},
    // ===== PAPER 2 (Total: 140 marks in 2022) =====
    // 2022 special format: Answer in any TWO of three sections. Each section = 70 marks.
    // N.B. Shakespeare was NOT compulsory in 2022
    {num:6, label:"P2: Single Text - All Options",
     q:"SECTION I - THE SINGLE TEXT (70 marks)\nAnswer ONE question from this section.\n\nPrescribed Texts for 2022:\nA. All the Light We Cannot See - Anthony Doerr\nB. A Doll's House - Henrik Ibsen\nC. Othello - William Shakespeare\nD. Frankenstein - Mary Shelley\nE. The Picture of Dorian Gray - Oscar Wilde\n\nA. ALL THE LIGHT WE CANNOT SEE - Anthony Doerr\n(i) 'The consequences of Werner Pfennig's passion for science and technology in Anthony Doerr's novel are both fascinating and disturbing.' Discuss the reasons why you agree or disagree. Develop your discussion with reference to the text.\nOR\n(ii) Discuss the narrative purposes served by Doerr's inclusion of the story of the diamond, the Sea of Flames, in his novel. Develop your discussion with reference to the text.\n\nB. A DOLL'S HOUSE - Henrik Ibsen\n(i) 'Various aspects of Ibsen's exploration of deception and delusion in his play, A Doll's House, are both fascinating and disturbing.' Discuss the reasons why you agree or disagree.\nOR\n(ii) Discuss the reasons why our knowledge of Nora Helmer's backstory, involving the loan, enables us to better understand various aspects of Ibsen's play.\n\nC. OTHELLO - William Shakespeare\n(i) 'Various aspects of the relationship between Iago and Emilia in Shakespeare's play, Othello, are both fascinating and disturbing.' Discuss.\nOR\n(ii) Discuss the reasons why our knowledge of Othello's status as an outsider enables us to better understand various aspects of Shakespeare's play.\n\nD. FRANKENSTEIN - Mary Shelley\n(i) and (ii) options available - see full paper.\n\nE. THE PICTURE OF DORIAN GRAY - Oscar Wilde\n(i) and (ii) options available - see full paper.",
     a:"MARKING CRITERIA (70 marks total):\n- Clarity of Purpose (P): 21 marks\n- Coherence of Delivery (C): 21 marks\n- Efficiency of Language Use (L): 21 marks\n- Accuracy of Mechanics (M): 7 marks\n\nGuidance by text:\n\nAll the Light We Cannot See:\n- Q(i) Werner's passion: Fascinating - his genius with radios, his curiosity. Disturbing - technology used for Nazi purposes, tracking resistance fighters, moral compromise. The tension between innocent scientific curiosity and its weaponisation.\n- Q(ii) Sea of Flames diamond: Creates suspense and mystery, connects characters (Marie-Laure's father, von Rumpel), symbolises greed vs selflessness, explores the curse narrative, raises questions about value and sacrifice.\n\nA Doll's House:\n- Q(i) Deception and delusion: Nora's secret loan, her performance of the 'doll' role, Torvald's delusion about their marriage, Krogstad's blackmail, Dr Rank's hidden feelings. Fascinating how the layers unravel; disturbing in what they reveal about power and gender.\n- Q(ii) Nora's backstory (the loan): Reveals her resourcefulness, her sacrifice for Torvald, the impossible position of women, explains her desperate behaviour, makes the final confrontation more powerful.\n\nOthello:\n- Q(i) Iago and Emilia: Their dysfunctional marriage, Emilia's subservience then defiance, Iago's contempt for women, the handkerchief theft, Emilia's final courageous truth-telling. Fascinating in its complexity; disturbing in its toxicity.\n- Q(ii) Othello as outsider: His race and religion in Venice, his need to prove himself, vulnerability to Iago's manipulation, insecurity about Desdemona, the tragedy of belonging and not belonging.\n\nApproach: Answer the SPECIFIC question. Use direct quotation and close textual reference. For 'fascinating and disturbing' questions, address BOTH elements. Structure: Introduction, 3-4 developed body paragraphs, Conclusion. Show personal engagement throughout."},
    // ===== PAPER 2: COMPARATIVE STUDY =====
    {num:7, label:"P2: Comparative Study",
     q:"SECTION II - THE COMPARATIVE STUDY (70 marks)\n\nAnswer ONE question from this section.\n\nCandidates compare texts under one mode of comparison:\n- Theme or Issue\n- Literary Genre\n- Cultural Context\n\nN.B. In 2022, candidates were NOT required to answer on Shakespearean Drama.\n\nThe question requires comparison of at least TWO texts from the prescribed comparative texts list.\n\n(Refer to the full exam paper for the specific comparative question set in 2022.)",
     a:"MARKING CRITERIA (70 marks total):\n- Clarity of Purpose (P): 21 marks\n- Coherence of Delivery (C): 21 marks\n- Efficiency of Language Use (L): 21 marks\n- Accuracy of Mechanics (M): 7 marks\n\nKey approach for Comparative Study:\n- You MUST compare - don't write separate essays on each text\n- Use linking phrases throughout: 'Similarly...', 'In contrast...', 'Both texts...', 'Unlike...', 'While X explores..., Y presents...'\n- Address the specific mode of comparison (Theme/Genre/Cultural Context)\n- Refer to at least TWO texts with specific examples, scenes, and quotations\n\nFor Theme or Issue:\n- Identify how the theme is explored differently/similarly across texts\n- Discuss characters, events, and outcomes in relation to the theme\n- Consider what each text reveals about the theme\n\nFor Literary Genre:\n- Compare narrative techniques, structure, style, point of view\n- Discuss use of imagery, symbolism, dramatic techniques\n- Consider how genre conventions are used or subverted\n\nFor Cultural Context:\n- Compare the social, historical, and cultural worlds depicted\n- How do characters navigate their cultural contexts?\n- What values, norms, and power structures shape the characters' lives?\n\nApproach: Plan which texts and which specific moments you will compare before writing. The most common mistake is writing about texts separately rather than comparing them. Every paragraph should mention at least two texts."},
    // ===== PAPER 2: POETRY =====
    {num:8, label:"P2: Poetry - Unseen Poem",
     q:"SECTION III - POETRY (70 marks)\n\nPart A: UNSEEN POEM (20 marks)\n\nAn unseen poem is printed on the paper. Candidates answer questions testing:\n- Understanding of the poem's theme, subject, or mood\n- Analysis of specific images, techniques, or language choices\n- Personal response to the poem\n\nTypical questions:\n(i) What is the central theme or mood of this poem? Explain with reference to the poem. (10)\n(ii) Choose two images or techniques that you found striking and explain why they are effective. (10)\n\n(Refer to the full exam paper for the specific unseen poem and questions.)",
     a:"MARKING CRITERIA (20 marks total):\nAssessed using P/C/L/M criteria.\n\nApproach for Unseen Poem:\n- Read the poem at least THREE times before writing\n- First read: overall meaning, subject, speaker, mood\n- Second read: key images, techniques, structure, sound\n- Third read: confirm your interpretation, note specific quotes\n\nTechniques to look for:\n- Imagery (visual, auditory, tactile, olfactory, gustatory)\n- Metaphor and simile\n- Personification\n- Alliteration, assonance, onomatopoeia\n- Enjambment and caesura\n- Rhyme scheme and rhythm\n- Tone and mood shifts\n- Symbolism\n- Contrast and juxtaposition\n\nKey rules:\n- Always QUOTE directly from the poem\n- Explain the EFFECT of each technique - don't just name it\n- Link techniques to the poem's meaning and mood\n- Show personal response: what struck you and why\n\nCommon pitfalls:\n- Identifying techniques without explaining their effect\n- Paraphrasing the poem instead of analysing it\n- Ignoring the specific question asked\n- Forgetting to quote from the poem"},
    {num:9, label:"P2: Poetry - Prescribed Poetry",
     q:"SECTION III - POETRY (70 marks)\n\nPart B: PRESCRIBED POETRY (50 marks)\n\nAnswer ONE question on a poet you have studied.\n\nPrescribed poets include: Eavan Boland, Sylvia Plath, W.B. Yeats, Emily Dickinson, Seamus Heaney, Elizabeth Bishop, and others as per the syllabus.\n\nA statement about the poet's work is given, and candidates must discuss it with reference to poems they have studied.\n\n(Refer to the full exam paper for the specific prescribed poetry question.)",
     a:"MARKING CRITERIA (50 marks total):\n- Clarity of Purpose (P): 15 marks\n- Coherence of Delivery (C): 15 marks\n- Efficiency of Language Use (L): 15 marks\n- Accuracy of Mechanics (M): 5 marks\n\nKey approach:\n- Refer to at least THREE poems by your chosen poet\n- Quote directly and accurately from the poems\n- Discuss themes, techniques, imagery, and personal response\n- Address the SPECIFIC statement or question asked\n- Show how the poet's style and concerns are evident across multiple poems\n\nStructure:\n- Introduction: Address the question directly, name your poet, indicate your overall response\n- Body: 3-4 paragraphs, each discussing a different poem, always linking back to the question\n- Conclusion: Summarise your overall response to the statement\n\nApproach: Know 5-6 poems well for each poet. Learn key quotes by heart. Practice linking poems thematically. NEVER write a pre-prepared answer - always respond to the actual question asked. Examiners can spot recycled essays."},
  ],
  "2023": [
    // ===== PAPER 1: COMPREHENDING (100 marks) =====
    // Theme: BETWEEN TWO WORLDS
    // 2023 format: Answer ONE Question A on one text AND ONE Question B on a DIFFERENT text
    {num:1, label:"P1: Text 1 - Between Two Worlds (Q A)",
     q:"TEXT 1 - BETWEEN TWO WORLDS\nAdapted from a novel by Abdulrazak Gurnah (Nobel Prize-winning author).\n\nThe narrator describes moving to London to live with Uncle Amir and Auntie Asha. Uncle Amir wants him to study business: 'In your circumstances, it is the perfect option and it will allow you to work anywhere in the world. Make money!' But the narrator would have preferred to study literature: 'It would have sounded cowardly to tell him that I should have preferred to study literature.' He describes arriving at their luxurious home, noting the contrast: 'A whole family lived in a room of this size where I had come from.' His new suitcase looked 'cheap and flimsy and tiny on that rug.'\n\nQuestion A (50 marks)\n\n(i) Based on your reading of Text 1, explain how the writer conveys the narrator's experience of being 'between two worlds'. Support your answer with reference to the text. (15)\n\n(ii) Identify and discuss three features of the writer's style that contribute to the effectiveness of this text. Refer to the text in your answer. (15)\n\n(iii) Based on your reading of Text 1, do you think the narrator is content with the choices being made for him? Give reasons for your answer with reference to the text. (20)",
     a:"MARKING CRITERIA (50 marks total):\nAll tasks assessed using P/C/L/M criteria:\n- Clarity of Purpose (P): 30% (15 marks)\n- Coherence of Delivery (C): 30% (15 marks)\n- Efficiency of Language Use (L): 30% (15 marks)\n- Accuracy of Mechanics (M): 10% (5 marks)\n\nQ A(i) - 15 marks: Between two worlds:\n- Literary aspirations vs Uncle Amir's business plans ('I should have preferred to study literature' but 'I did not have the courage to say anything')\n- Physical contrast: luxurious London room vs modest origins ('A whole family lived in a room of this size where I had come from')\n- The suitcase as symbol: 'cheap and flimsy and tiny on that rug' - object from old world out of place in new\n- Emotional displacement: 'too flustered to take in everything immediately'\n- The wardrobe 'the depth of a coffin' - dark undertone amid luxury\n- Gratitude vs loss of autonomy: 'I was moved by the pleasure they took in my arrival' but unable to express his own wishes\n\nQ A(ii) - 15 marks: Style features:\n- First-person narration: creates intimacy and sympathy, we access his inner conflict\n- Contrast/juxtaposition: old world vs new, modesty vs luxury, wishes vs reality\n- Vivid descriptive detail: listing of room contents ('a large bed, a dark wardrobe the depth of a coffin, a wide desk...')\n- Symbolism: the suitcase represents the narrator's displacement\n- Understated tone: restraint mirrors the narrator's own emotional restraint\n- Simile and imagery: 'wardrobe the depth of a coffin' - sinister note amid comfort\n\nQ A(iii) - 20 marks: Is the narrator content?\nEvidence he is NOT content:\n- 'It would have sounded cowardly' - self-censoring\n- 'I did not have the courage to say anything' - suppressing his wishes\n- His passion for literature is described with warmth; business with none\n- 'how I might have preferred to proceed with my life' - conditional, wistful\nHowever, he appreciates the kindness shown to him.\nA strong answer will acknowledge the complexity - gratitude mixed with quiet dissatisfaction.\n\nApproach: In 2023, you answer Q A on ONE text and Q B on a DIFFERENT text. Plan which texts to use before starting. Use direct quotation throughout."},
    {num:2, label:"P1: Text 1 - Between Two Worlds (Q B)",
     q:"TEXT 1 - BETWEEN TWO WORLDS\n\nQuestion B (50 marks)\n\nA functional writing task inspired by Text 1 and the theme of being between two worlds. This may ask you to write a personal essay, speech, article, blog post, or letter exploring the experience of displacement, cultural transition, or navigating between different worlds.\n\n(Refer to the full exam paper for exact wording.)",
     a:"MARKING CRITERIA (50 marks total):\n- Clarity of Purpose (P): 15 marks\n- Coherence of Delivery (C): 15 marks\n- Efficiency of Language Use (L): 15 marks\n- Accuracy of Mechanics (M): 5 marks\n\nKey points:\n- Identify the FORMAT required and write in the correct register\n- Draw on ideas from Text 1: displacement, cultural contrast, identity, family expectations\n- Add your own material - personal experience, examples, insights\n- Sustain the register throughout the piece\n\nIf personal essay: reflective, honest, move between narrative and insight\nIf speech: direct address, rhetorical devices, persuasive tone\nIf article: headline, engaging opening, balanced perspective, informed tone\nIf blog post: personal voice, accessible style, engaging title\n\nApproach: Remember you CANNOT answer Q B on the same text as your Q A. If you answered Q A on Text 1, you must answer Q B on Text 2 or Text 3."},
    {num:3, label:"P1: Text 2 (Q A & Q B)",
     q:"TEXT 2 - (Theme: BETWEEN TWO WORLDS)\n\nQuestion A (50 marks):\nThree comprehension-style questions testing understanding, language analysis, and personal response.\n\nQuestion B (50 marks):\nA functional writing task related to the theme of Text 2.\n\n(Refer to the full exam paper for the specific text and questions.)",
     a:"MARKING CRITERIA (50 marks for either Q A or Q B):\nAll tasks assessed using P/C/L/M criteria.\n\nFor Question A: Read carefully, quote directly, analyse language techniques, support personal opinions with evidence.\nFor Question B: Correct format and register. Draw on text ideas. Sustain quality throughout.\n\nApproach: Remember the constraint - Q A and Q B must be on DIFFERENT texts."},
    {num:4, label:"P1: Text 3 (Q A & Q B)",
     q:"TEXT 3 - (Theme: BETWEEN TWO WORLDS)\n\nQuestion A (50 marks):\nThree comprehension-style questions.\n\nQuestion B (50 marks):\nA functional writing task related to the theme of Text 3.\n\n(Refer to the full exam paper for the specific text and questions.)",
     a:"MARKING CRITERIA (50 marks):\nSame P/C/L/M criteria.\n\nApproach: Same principles. Remember: Q A and Q B on DIFFERENT texts."},
    // ===== PAPER 1: COMPOSING (100 marks) =====
    {num:5, label:"P1: Composing - All 7 Options",
     q:"SECTION II - COMPOSING (100 marks)\nTheme: BETWEEN TWO WORLDS\n\nWrite a composition on any ONE of the following:\n\n1. Write a personal essay exploring the experience of being caught between two worlds.\n\n2. Write a short story in which a character must navigate between two very different worlds.\n\n3. Write a discursive essay on the topic: 'We are all, in some way, caught between two worlds.'\n\n4. Write a descriptive composition based on a place or moment that represents a boundary between two worlds.\n\n5. Write a narrative exploring the idea that 'leaving one world behind is the price of entering another.'\n\n6. Write an argumentative essay: 'The online world has become more real to us than the physical world.'\n\n7. Write a composition exploring the idea that 'home is not a place but a feeling.'\n\n(Note: Refer to the full exam paper for exact wording of all 7 options.)",
     a:"MARKING CRITERIA (100 marks total):\n- Clarity of Purpose (P): 30 marks\n- Coherence of Delivery (C): 30 marks\n- Efficiency of Language Use (L): 30 marks\n- Accuracy of Mechanics (M): 10 marks\n\nAdvice by type:\n\nPersonal Essay (Option 1): Reflective tone, specific anecdotes, move between story and insight, show genuine self-awareness.\n\nShort Story (Option 2): Strong opening, developed characters, clear plot arc, effective ending. Two worlds could be literal (two places) or figurative (childhood/adulthood, reality/imagination).\n\nDiscursive (Option 3): Multiple perspectives, evidence, balanced. Consider: digital/physical, home/away, public/private, past/present.\n\nDescriptive (Option 4): Sensory language, atmosphere, vivid detail. Could be a border, a doorway, a moment of transition.\n\nNarrative (Option 5): Compelling story showing the cost and reward of change. Character development through the journey.\n\nArgumentative (Option 6): Clear thesis, evidence from real life, address counter-arguments. Social media, gaming, remote work as examples.\n\nCreative/Personal (Option 7): Explore belonging, memory, identity. What makes somewhere feel like home? Emotional depth.\n\nApproach: Spend 5 minutes planning. Choose the option that suits YOUR strengths. Aim for 4-5 pages. Quality of language matters as much as content."},
    // ===== PAPER 2: SINGLE TEXT (60 marks in 2023) =====
    {num:6, label:"P2: Single Text - All Options",
     q:"SECTION I - THE SINGLE TEXT (60 marks)\nAnswer ONE question from this section.\n\nPrescribed Texts for 2023:\nA. All the Light We Cannot See - Anthony Doerr\nB. A Doll's House - Henrik Ibsen\nC. Macbeth - William Shakespeare\nD. Frankenstein - Mary Shelley\nE. The Picture of Dorian Gray - Oscar Wilde\n\nN.B. Candidates MUST answer on Shakespearean Drama - either here (Macbeth) or in Comparative Study (Macbeth, Othello).\n\nA. ALL THE LIGHT WE CANNOT SEE - Anthony Doerr\n(i) In your opinion, to what extent do innate personal qualities or environmental factors, or both, shape the behaviour of at least two characters in All the Light We Cannot See? Develop your discussion with reference to Doerr's novel.\nOR\n(ii) 'We learn many interesting lessons from Doerr's exploration of resilience and resistance in All the Light We Cannot See.' Discuss this statement with reference to Doerr's novel.\n\nB. A DOLL'S HOUSE - Henrik Ibsen\n(i) 'Torvald Helmer is a complex and tragic character who evokes both disdain and sympathy in the audience.' To what extent do you agree or disagree? Develop your discussion with reference to Ibsen's play.\nOR\n(ii) To what extent does Ibsen's use of dialogue and symbolism in A Doll's House increase or diminish the impact of this play on you? Develop your discussion with reference to Ibsen's play.\n\nC. MACBETH - William Shakespeare\n(i) 'Macbeth's unstable and tragic identity is shaped by a variety of ambiguities and complexities in his character.' Discuss with reference to Shakespeare's play.\nOR\n(ii) 'Shakespeare makes effective use of Lady Macbeth and the Witches to heighten the dramatic impact of his play Macbeth in a variety of ways.' Discuss with reference to the play.\n\nD. FRANKENSTEIN - Mary Shelley\n(i) and (ii) options available - see full paper.\n\nE. THE PICTURE OF DORIAN GRAY - Oscar Wilde\n(i) and (ii) options available - see full paper.",
     a:"MARKING CRITERIA (60 marks total):\n- Clarity of Purpose (P): 18 marks\n- Coherence of Delivery (C): 18 marks\n- Efficiency of Language Use (L): 18 marks\n- Accuracy of Mechanics (M): 6 marks\n\nGuidance by text:\n\nAll the Light We Cannot See:\n- Q(i) Nature vs nurture: Werner - innate genius with radios vs Nazi indoctrination at Schulpforta. Marie-Laure - innate resilience vs wartime environment. Frederick - gentle nature crushed by environment. Von Rumpel - obsession shaped by greed. Discuss how BOTH factors interplay.\n- Q(ii) Resilience and resistance: Marie-Laure navigating blindness and war. Etienne overcoming agoraphobia to broadcast. Madame Manec's resistance network. Werner's final act of humanity. What LESSONS do we learn? Courage, compassion, the power of knowledge.\n\nA Doll's House:\n- Q(i) Torvald as complex: Disdain - patronising nicknames ('my little skylark'), controlling behaviour, concern for reputation over Nora. Sympathy - he genuinely loves Nora (in his way), his world collapses, he is a product of his society. Tragic because he cannot see beyond his role.\n- Q(ii) Dialogue: Nora's shifting register (playful early, serious later). Symbolism: tarantella (desperate frenzy), Christmas tree (deteriorating like marriage), macaroons (secret rebellion), Nora's fancy dress (performing a role), the door slam.\n\nMacbeth:\n- Q(i) Ambiguities: Brave warrior AND murderer. Free will AND fate. Loves Lady Macbeth AND destroys their relationship. His soliloquies show conscience ('Is this a dagger...', 'Tomorrow and tomorrow...'). Tragic because he knows what he's doing is wrong.\n- Q(ii) Lady Macbeth: 'Unsex me here' speech, persuasion in Act 1, her own destruction (sleepwalking scene). Witches: 'Fair is foul', ambiguous prophecies, catalysts for action. Both heighten dramatic tension and explore themes of ambition and guilt.\n\nApproach: Answer the SPECIFIC question asked. Use direct quotation. Structure: Intro (address question), Body (3-4 developed paragraphs with evidence), Conclusion. Show personal engagement."},
    // ===== PAPER 2: COMPARATIVE STUDY (70 marks) =====
    {num:7, label:"P2: Comparative Study",
     q:"SECTION II - THE COMPARATIVE STUDY (70 marks)\nAnswer ONE question.\n\nModes of comparison: Theme or Issue / Literary Genre / Cultural Context\n\nN.B. Candidates MUST answer on Shakespearean Drama. They may do so here (Macbeth, Othello) or in Single Text (Macbeth).\n\nCompare at least TWO texts from the prescribed comparative texts list.\n\n(Refer to the full exam paper for the specific comparative question.)",
     a:"MARKING CRITERIA (70 marks total):\n- Clarity of Purpose (P): 21 marks\n- Coherence of Delivery (C): 21 marks\n- Efficiency of Language Use (L): 21 marks\n- Accuracy of Mechanics (M): 7 marks\n\nKey approach:\n- COMPARE throughout - the most common mistake is writing separate mini-essays on each text\n- Every paragraph should mention at least TWO texts\n- Use comparison language: 'Similarly', 'In contrast', 'Both texts', 'Unlike', 'While X..., Y...', 'Just as... so too...'\n\nFor Theme or Issue: How does the theme manifest in each text? Compare characters' experiences, choices, and outcomes.\n\nFor Literary Genre: Compare how the story is told - narrative voice, structure, dramatic techniques, imagery, symbolism.\n\nFor Cultural Context: Compare the worlds - social norms, power, gender, class, values. How do characters navigate or challenge their cultural context?\n\nApproach: Make sure you have fulfilled the Shakespeare requirement (either here or in Single Text). Plan your comparison points before writing. Aim for 3-4 points of comparison, each developed with evidence from both texts."},
    // ===== PAPER 2: POETRY =====
    {num:8, label:"P2: Poetry - Unseen Poem",
     q:"SECTION III - POETRY\n\nPart A: UNSEEN POEM (20 marks)\n\nAn unseen poem is printed on the paper. Candidates answer questions on it.\n\nTypical questions:\n(i) What is the central theme or mood of this poem? Explain with reference to the poem. (10)\n(ii) Choose two images or techniques from the poem and explain why you found them effective. (10)\n\n(Refer to the full exam paper for the specific unseen poem and questions.)",
     a:"MARKING CRITERIA (20 marks total):\nAssessed using P/C/L/M criteria.\n\nStep-by-step approach:\n1. Read the poem THREE times before writing anything\n2. First read: What is the poem about? Who is speaking? What is the mood?\n3. Second read: Underline striking images, techniques, unusual word choices\n4. Third read: Confirm your interpretation, select your best quotes\n\nTechniques checklist:\n- Imagery (visual, auditory, tactile, etc.)\n- Metaphor, simile, personification\n- Alliteration, assonance, onomatopoeia\n- Enjambment, caesura\n- Rhyme scheme, rhythm, metre\n- Tone shifts, volta\n- Symbolism, contrast\n\nGolden rules:\n- QUOTE directly from the poem\n- Name the technique AND explain its EFFECT\n- Link to the poem's overall meaning\n- Show personal response"},
    {num:9, label:"P2: Poetry - Prescribed Poetry",
     q:"SECTION III - POETRY\n\nPart B: PRESCRIBED POETRY (50 marks)\n\nAnswer ONE question on a poet you have studied.\n\nPrescribed poets include: Eavan Boland, Sylvia Plath, W.B. Yeats, Emily Dickinson, Seamus Heaney, Elizabeth Bishop, Derek Mahon, and others.\n\nA statement about the poet's work is given; discuss with reference to poems studied.\n\n(Refer to the full exam paper for the specific question.)",
     a:"MARKING CRITERIA (50 marks total):\n- Clarity of Purpose (P): 15 marks\n- Coherence of Delivery (C): 15 marks\n- Efficiency of Language Use (L): 15 marks\n- Accuracy of Mechanics (M): 5 marks\n\nKey approach:\n- Refer to at least THREE poems\n- Quote directly and accurately\n- Discuss themes, techniques, imagery, and personal response\n- Address the SPECIFIC statement or question\n- Show connections across poems\n\nStructure:\n- Introduction: Address the question, name your poet, state your position\n- Body: 3-4 paragraphs, each focused on a different poem but linked to the question\n- Conclusion: Summarise your response\n\nApproach: Know 5-6 poems well. Learn key quotes. Practice linking poems thematically. Never use a pre-prepared essay - respond to the actual question. Examiners can spot recycled answers."},
  ],
  "2024": [
    // ===== PAPER 1: COMPREHENDING (100 marks) =====
    // Theme: CONNECTIONS
    // 2024 format: Answer ONE Question A on one text AND ONE Question B on a DIFFERENT text
    {num:1, label:"P1: Text 1 - Connections Through Nature (Q A)",
     q:"TEXT 1 - CONNECTIONS\nAn essay by Fintan O'Toole about connections between generations, inspired by birds and memory.\n\nThe writer describes how his youngest son got a waxwing tattoo on his forearm - 'a gorgeous winter visitor to Ireland that looks like a dressed-up finch, with a backwards quiff for a crest and two vivid red blobs on its wings like sealing wax.' The son knew this would 'disarm my prejudices because the bird connects him to his father and his grandfather. It is a genetic memory with wings.'\n\nThe writer's first piece of writing was a school essay called 'Waxwings', about his father taking him to Ballsbridge to see waxwings: 'I was interested, of course, less in the birds than in my dad's excitement at seeing them, and the way the sharing of this pleasure with us was a gift of time and love.'\n\nAfter his father died, 'something of his spirit migrated into that tattoo. It found a new fleshy perch.' In the Natural History Museum, a pallid swift was first recorded in Ireland in 1953 by his father on Howth Head.\n\nQuestion A (50 marks)\n\n(i) Based on your reading of Text 1, explain how the writer uses the image of the waxwing to explore the idea of connections between generations. Support your answer with reference to the text. (15)\n\n(ii) Identify and comment on three features of the writer's style that make this text engaging for the reader. Support your answer with reference to the text. (15)\n\n(iii) Based on your reading of Text 1, do you think the writer successfully conveys the importance of connections in our lives? Give reasons for your answer. (20)",
     a:"MARKING CRITERIA (50 marks total):\nAll tasks assessed using P/C/L/M criteria:\n- Clarity of Purpose (P): 30% (15 marks)\n- Coherence of Delivery (C): 30% (15 marks)\n- Efficiency of Language Use (L): 30% (15 marks)\n- Accuracy of Mechanics (M): 10% (5 marks)\n\nQ A(i) - 15 marks: The waxwing as connection:\n- Son's tattoo connects three generations - son, father, grandfather\n- 'It is a genetic memory with wings' - powerful metaphor linking nature and family\n- Father took writer to see waxwings at Ballsbridge as a child - shared experience\n- 'the sharing of this pleasure with us was a gift of time and love' - connection through shared joy\n- After father died, 'something of his spirit migrated into that tattoo. It found a new fleshy perch' - continuity beyond death\n- The pallid swift in the museum, spotted by his father in 1953 - physical evidence of the father's passion\n- The writer's first essay was 'Waxwings' - writing itself as a form of connection\n\nQ A(ii) - 15 marks: Style features:\n- Metaphor: 'genetic memory with wings' - combines biology and poetry\n- Vivid descriptive detail: 'backwards quiff for a crest and two vivid red blobs on its wings'\n- Simile: 'like sealing wax applied to an ancient missive from on high' - elevates the ordinary\n- Personal, intimate tone: draws the reader into family life\n- Structural connections: different birds/memories parallel each other\n- Contrast: modern tattoo vs 1953 discovery, youth vs age, life vs death\n- Humour: 'Parents - at least those of my age - don't like the idea of their children getting tattoos'\n\nQ A(iii) - 20 marks: Does the writer successfully convey importance of connections?\n- The tangible connections (tattoo, museum specimen) represent intangible family bonds\n- Nature as a bridge between generations - passion passed down\n- Memory and storytelling as forms of connection that outlast death\n- The essay itself is an act of connection - writing about his father preserves the bond\n- The warmth of tone conveys genuine feeling without sentimentality\n\nApproach: Quote directly. For (ii), name the technique AND explain its EFFECT - 'The metaphor \"genetic memory with wings\" is effective because it suggests that the connection between generations is both natural and transcendent.'"},
    {num:2, label:"P1: Text 1 - Connections Through Nature (Q B)",
     q:"TEXT 1 - CONNECTIONS\n\nQuestion B (50 marks)\n\nA functional writing task inspired by Text 1 and the theme of connections. This may ask you to write a personal essay about the connections that matter most to you, a speech about the importance of maintaining connections, or an article exploring how we stay connected across generations.\n\n(Refer to the full exam paper for exact wording.)",
     a:"MARKING CRITERIA (50 marks total):\n- Clarity of Purpose (P): 15 marks\n- Coherence of Delivery (C): 15 marks\n- Efficiency of Language Use (L): 15 marks\n- Accuracy of Mechanics (M): 5 marks\n\nKey points:\n- Use ideas from Text 1 as a springboard: generational bonds, nature, memory, objects as symbols of connection\n- Add your own personal material\n- Write in the correct FORMAT and REGISTER\n\nIf personal essay: reflective and honest, specific anecdotes, insight about what connections mean\nIf speech: direct address, rhetorical devices, build to a moving conclusion\nIf article: journalistic conventions, engaging opening, broader perspective\n\nApproach: Remember you CANNOT answer Q B on the same text as your Q A. Show emotional depth and genuine engagement with the theme."},
    {num:3, label:"P1: Text 2 (Q A & Q B)",
     q:"TEXT 2 - (Theme: CONNECTIONS)\n\nQuestion A (50 marks):\nThree comprehension-style questions testing understanding, language analysis, and personal response.\n\nQuestion B (50 marks):\nA functional writing task related to the theme of Text 2.\n\n(Refer to the full exam paper for the specific text and questions.)",
     a:"MARKING CRITERIA (50 marks):\nAll tasks assessed using P/C/L/M criteria.\n\nApproach: Read carefully, quote directly, analyse techniques, support opinions with evidence. Remember: Q A and Q B must be on DIFFERENT texts."},
    {num:4, label:"P1: Text 3 (Q A & Q B)",
     q:"TEXT 3 - (Theme: CONNECTIONS)\n\nQuestion A (50 marks):\nThree comprehension-style questions.\n\nQuestion B (50 marks):\nA functional writing task related to the theme of Text 3.\n\n(Refer to the full exam paper for the specific text and questions.)",
     a:"MARKING CRITERIA (50 marks):\nSame P/C/L/M criteria.\n\nApproach: Same principles. Remember: Q A and Q B on DIFFERENT texts."},
    // ===== PAPER 1: COMPOSING (100 marks) =====
    {num:5, label:"P1: Composing - All 7 Options",
     q:"SECTION II - COMPOSING (100 marks)\nTheme: CONNECTIONS\n\nWrite a composition on any ONE of the following:\n\n1. Write a personal essay exploring the connections that shape who we are.\n\n2. Write a short story in which an unexpected connection changes a character's life.\n\n3. Write a discursive essay: 'In the age of social media, we are more connected but less connected than ever.'\n\n4. Write a descriptive composition capturing a moment of connection between people or between a person and a place.\n\n5. Write a narrative exploring the idea that 'the connections we make define us.'\n\n6. Write an argumentative essay: 'Technology has fundamentally changed the nature of human connection.'\n\n7. Write a composition exploring the idea that 'the most meaningful connections are often the most unexpected.'\n\n(Note: Refer to the full exam paper for exact wording of all 7 options.)",
     a:"MARKING CRITERIA (100 marks total):\n- Clarity of Purpose (P): 30 marks\n- Coherence of Delivery (C): 30 marks\n- Efficiency of Language Use (L): 30 marks\n- Accuracy of Mechanics (M): 10 marks\n\nAdvice by type:\n\nPersonal Essay (Option 1): Family connections, friendships, connections to place or culture. Be specific and reflective. Use the O'Toole text as inspiration - small details that reveal deep connections.\n\nShort Story (Option 2): Build to the unexpected connection. Developed characters, effective dialogue, satisfying resolution. The connection should feel earned, not forced.\n\nDiscursive (Option 3): Balance pros and cons of digital connection. Consider: social media friendships vs face-to-face, global connection vs local community, information vs genuine understanding.\n\nDescriptive (Option 4): Sensory detail, atmosphere, emotional resonance. Show the connection through imagery rather than stating it directly.\n\nNarrative (Option 5): A character's journey shaped by the people or places they connect with. Show cause and effect.\n\nArgumentative (Option 6): Take a clear position with evidence. Consider both sides. Address: video calls, social media, AI, remote work, online communities.\n\nCreative (Option 7): Could be narrative, reflective, or descriptive. Show the surprise and significance of unexpected connections.\n\nApproach: Plan for 5 minutes. Choose your strongest genre. Aim for 4-5 pages. Quality over quantity. Strong opening and closing essential."},
    // ===== PAPER 2: SINGLE TEXT (60 marks in 2024) =====
    {num:6, label:"P2: Single Text - All Options",
     q:"SECTION I - THE SINGLE TEXT (60 marks)\nAnswer ONE question from this section.\n\nPrescribed Texts for 2024:\nA. All the Light We Cannot See - Anthony Doerr\nB. The Crucible - Arthur Miller\nC. Hamlet - William Shakespeare\nD. Frankenstein - Mary Shelley\nE. The Picture of Dorian Gray - Oscar Wilde\n\nN.B. Candidates MUST answer on Shakespearean Drama - either here (Hamlet) or in Comparative Study (Hamlet, Macbeth).\n\nA. ALL THE LIGHT WE CANNOT SEE - Anthony Doerr\n(i) 'We are fascinated by the tensions that emerge from Doerr's exploration of a variety of moral and ethical issues in his novel.' Discuss with reference to Doerr's novel.\nOR\n(ii) To what extent do you think the narrative structure adopted by Doerr is effective in engaging the reader? Develop your response with reference to Doerr's novel.\n\nB. THE CRUCIBLE - Arthur Miller\n(i) 'Miller uses Proctor's complex relationship with Elizabeth to explore a variety of core issues in his play, The Crucible.' Discuss with reference to Miller's play.\nOR\n(ii) Discuss the compelling reasons why Miller's play, The Crucible, should not be considered an entirely bleak play. Develop your response with reference to Miller's play.\n\nC. HAMLET - William Shakespeare\n(i) 'Shakespeare uses Hamlet's complex relationship with Gertrude to explore a variety of core issues in his play, Hamlet.' Discuss with reference to Shakespeare's play.\nOR\n(ii) Discuss the aspects of Shakespeare's play, Hamlet, that make it a surprisingly positive and hopeful drama. Develop your response with reference to the play.\n\nD. FRANKENSTEIN - Mary Shelley\n(i) 'We are fascinated by the tensions that emerge from Shelley's exploration of a variety of moral and ethical issues in her novel, Frankenstein.' Discuss with reference to Shelley's novel.\nOR\n(ii) Options available - see full paper.\n\nE. THE PICTURE OF DORIAN GRAY - Oscar Wilde\n(i) and (ii) options available - see full paper.",
     a:"MARKING CRITERIA (60 marks total):\n- Clarity of Purpose (P): 18 marks\n- Coherence of Delivery (C): 18 marks\n- Efficiency of Language Use (L): 18 marks\n- Accuracy of Mechanics (M): 6 marks\n\nGuidance by text:\n\nAll the Light We Cannot See:\n- Q(i) Moral/ethical tensions: Werner's complicity with Nazis vs his inherent goodness, the ethics of war, the diamond's curse (greed vs selflessness), Marie-Laure's father hiding the diamond, Etienne's duty to resist. Show how these tensions FASCINATE - they are complex, not black and white.\n- Q(ii) Narrative structure: Non-linear dual timeline (1944 and backstory), alternating perspectives (Werner/Marie-Laure), very short chapters creating urgency, parallel journeys converging. Effective because it builds suspense, creates thematic echoes, and mirrors the radio transmissions connecting characters.\n\nThe Crucible:\n- Q(i) Proctor and Elizabeth: Guilt over Abigail affair, Elizabeth's coldness, rebuilding trust, her lie in court to protect him, his final confession and refusal to sign. Core issues explored: integrity, forgiveness, truth, reputation, personal vs public morality.\n- Q(ii) Not entirely bleak: Proctor's final integrity ('Because it is my name! Because I cannot have another in my life!'), Rebecca Nurse's quiet courage, Elizabeth's growth and forgiveness ('He have his goodness now'), Giles Corey's defiance ('More weight'), the power of individual conscience against mass hysteria.\n\nHamlet:\n- Q(i) Hamlet and Gertrude: Disgust at her 'o'erhasty marriage', the closet scene confrontation, his cruelty vs his love, her drinking the poison. Core issues: loyalty, betrayal, appearance vs reality, moral corruption, the mother-son bond.\n- Q(ii) Positive and hopeful: Hamlet-Horatio friendship (genuine loyalty), Hamlet's wit and intelligence, justice ultimately achieved, Horatio survives to 'tell my story', Hamlet's growth and acceptance ('the readiness is all'), love between Hamlet and Ophelia (however tragic).\n\nFrankenstein:\n- Q(i) Moral/ethical issues: Creation without responsibility, playing God, prejudice against the Creature based on appearance, Victor's abandonment, the ethics of scientific ambition, the Creature's demand for a companion, the cycle of revenge.\n\nApproach: Answer the SPECIFIC question. Use direct quotation. Show personal engagement. Structure clearly: Introduction, 3-4 developed body paragraphs, Conclusion."},
    // ===== PAPER 2: COMPARATIVE STUDY (70 marks) =====
    {num:7, label:"P2: Comparative Study",
     q:"SECTION II - THE COMPARATIVE STUDY (70 marks)\nAnswer ONE question.\n\nModes of comparison: Theme or Issue / Literary Genre / Cultural Context\n\nN.B. Candidates MUST answer on Shakespearean Drama. They may do so here (Hamlet, Macbeth) or in Single Text (Hamlet).\n\nCompare at least TWO texts from the prescribed comparative texts list.\n\n(Refer to the full exam paper for the specific comparative question.)",
     a:"MARKING CRITERIA (70 marks total):\n- Clarity of Purpose (P): 21 marks\n- Coherence of Delivery (C): 21 marks\n- Efficiency of Language Use (L): 21 marks\n- Accuracy of Mechanics (M): 7 marks\n\nKey approach:\n- COMPARE in every paragraph - never write about texts in isolation\n- Use linking language constantly: 'Similarly', 'In contrast', 'Both', 'Unlike', 'While', 'Just as... so too...'\n- Address the specific mode asked\n- Specific examples and quotations from each text\n\nFor Theme or Issue: How does each text explore the theme? Compare characters' experiences, choices, consequences.\n\nFor Literary Genre: Compare narrative techniques, structure, style, dramatic devices, imagery, symbolism.\n\nFor Cultural Context: Compare social worlds, power structures, gender roles, class, values, historical settings.\n\nApproach: Check you've fulfilled the Shakespeare requirement. Plan comparison points before writing. 3-4 developed points of comparison with evidence from all texts. Every paragraph must be genuinely comparative."},
    // ===== PAPER 2: POETRY =====
    {num:8, label:"P2: Poetry - Unseen Poem",
     q:"SECTION III - POETRY\n\nPart A: UNSEEN POEM (20 marks)\n\nAn unseen poem is printed on the paper. Answer questions testing understanding, analysis, and personal response.\n\n(Refer to the full exam paper for the specific unseen poem and questions.)",
     a:"MARKING CRITERIA (20 marks total):\nAssessed using P/C/L/M criteria.\n\nStep-by-step:\n1. Read THREE times\n2. First read: subject, mood, speaker\n3. Second read: images, techniques, structure, sound\n4. Third read: confirm interpretation, select quotes\n\nTechniques to look for: imagery, metaphor, simile, personification, alliteration, assonance, onomatopoeia, enjambment, caesura, rhyme, rhythm, tone shifts, symbolism, contrast.\n\nGolden rules:\n- QUOTE from the poem\n- Name technique AND explain EFFECT\n- Link to overall meaning\n- Show personal response\n\nCommon mistakes: identifying techniques without explaining effect; paraphrasing instead of analysing; not quoting; ignoring the question."},
    {num:9, label:"P2: Poetry - Prescribed Poetry",
     q:"SECTION III - POETRY\n\nPart B: PRESCRIBED POETRY (50 marks)\n\nAnswer ONE question on a poet you have studied.\n\nPrescribed poets include: Eavan Boland, Sylvia Plath, W.B. Yeats, Emily Dickinson, Seamus Heaney, Elizabeth Bishop, Derek Mahon, and others.\n\nA statement about the poet's work is given; discuss with reference to poems studied.\n\n(Refer to the full exam paper for the specific question.)",
     a:"MARKING CRITERIA (50 marks total):\n- Clarity of Purpose (P): 15 marks\n- Coherence of Delivery (C): 15 marks\n- Efficiency of Language Use (L): 15 marks\n- Accuracy of Mechanics (M): 5 marks\n\nKey approach:\n- Refer to at least THREE poems\n- Quote directly and accurately\n- Discuss themes, techniques, imagery, personal response\n- Address the SPECIFIC statement\n- Show connections across poems\n\nStructure:\n- Introduction: Address question, name poet, indicate your response\n- Body: 3-4 paragraphs, each on a different poem, linked to question\n- Conclusion: Summarise your overall response\n\nApproach: Know 5-6 poems well. Learn key quotes. Link poems thematically. Never submit a pre-prepared answer - always respond to the actual question. Examiners spot recycled essays immediately."},
  ],
};
