var STUDY_ENGLISH = [
  {
    topic: "Paper 1 Comprehension",
    icon: "📖",
    subtopics: [
      {
        title: "Language of Argument",
        content: "Argumentative writing aims to persuade the reader to accept a position or viewpoint. Writers build arguments using a combination of logic, evidence, and rhetorical devices.\n\nKey features to identify:\n- Thesis statement: The writer's central claim, usually stated early.\n- Evidence and support: Facts, statistics, expert opinions, examples, anecdotes used to back up claims.\n- Logical connectors: \"Therefore\", \"consequently\", \"however\", \"on the other hand\", \"furthermore\" - these signal how ideas relate.\n- Counterarguments: Strong arguments acknowledge opposing views and refute them. Look for \"Some might argue...\" or \"Critics suggest...\"\n- Tone: Often assertive and confident. May shift between measured and passionate depending on the point.\n\nHow to analyse in the exam:\n- Identify the writer's central argument first.\n- Note how they structure their reasoning (strongest point first? Building to climax?).\n- Look for rhetorical devices: rhetorical questions, repetition, rule of three.\n- Assess whether the argument is balanced or one-sided.\n- Comment on the effectiveness of evidence used.",
        keyTerms: ["thesis", "counterargument", "assertion", "rebuttal", "logical fallacy", "premise", "deduction", "induction", "concession"],
        formula: null,
        examTip: "When asked about argument, always name the SPECIFIC technique (e.g., 'appeal to authority', 'use of statistics') rather than saying 'good argument'. Examiners reward precise terminology."
      },
      {
        title: "Language of Persuasion",
        content: "Persuasive language goes beyond logical argument - it appeals to emotions, values, and identity. Persuasion works by making the audience FEEL something, not just think something.\n\nThe three classical appeals (Aristotle):\n- Ethos: Appeal to credibility. The writer establishes authority or trustworthiness. E.g., citing experience, credentials, or shared values.\n- Pathos: Appeal to emotion. Uses vivid imagery, personal stories, emotive diction to provoke feelings like sympathy, anger, hope, or fear.\n- Logos: Appeal to logic. Uses facts, statistics, cause-and-effect reasoning, and structured arguments.\n\nPersuasive techniques to identify:\n- Emotive language: Words chosen to provoke emotional response (\"heartbreaking\", \"devastating\", \"inspiring\").\n- Inclusive pronouns: \"We\", \"our\", \"us\" - creates a sense of shared identity and community.\n- Direct address: \"You\" - makes the reader feel personally involved.\n- Anaphora: Repetition at the start of successive sentences for emphasis and rhythm.\n- Rhetorical questions: Questions asked for effect, not answers. \"Can we really stand by and do nothing?\"\n- Rule of three: Grouping ideas in threes for impact. \"We came, we saw, we conquered.\"\n- Hyperbole: Deliberate exaggeration to emphasise a point.\n- Contrast/antithesis: Placing opposing ideas together. \"Ask not what your country can do for you, ask what you can do for your country.\"",
        keyTerms: ["ethos", "pathos", "logos", "emotive language", "anaphora", "rhetorical question", "hyperbole", "inclusive pronoun", "direct address", "antithesis"],
        formula: null,
        examTip: "In Question A (iii), you must discuss FOUR elements of style for 20 marks (5 each). Use the PCLM structure for each: name the technique (Point), quote from the text (Context), explain why it's that technique (Language), and say what effect it has on the reader (Meaning)."
      },
      {
        title: "Language of Narration",
        content: "Narrative language tells a story - whether fiction or non-fiction. Narration uses specific techniques to engage readers and convey meaning through storytelling.\n\nTypes of narrative perspective:\n- First person (\"I/we\"): Intimate, subjective, limited to narrator's knowledge. Creates empathy and immediacy.\n- Second person (\"you\"): Unusual, draws reader directly into the experience. Often used in speeches or experimental fiction.\n- Third person limited: Follows one character's perspective using \"he/she/they\". Close but with some distance.\n- Third person omniscient: All-knowing narrator who can enter any character's mind. Gives a broader view.\n\nNarrative techniques:\n- Dialogue: Reveals character, creates pace, provides information naturally.\n- Description: Sensory details (sight, sound, touch, taste, smell) create vivid scenes.\n- Show don't tell: \"Her hands trembled\" (showing fear) vs \"She was afraid\" (telling).\n- Foreshadowing: Hints about what will happen later. Creates suspense.\n- Flashback: Jumping back in time to provide context or background.\n- Pace: Short sentences = urgency/tension. Long sentences = reflection/calm.\n- Imagery: Vivid descriptive language that creates mental pictures.\n- Symbolism: Objects or events that represent deeper meaning.",
        keyTerms: ["narrator", "point of view", "first person", "third person omniscient", "dialogue", "foreshadowing", "flashback", "pace", "show don't tell", "stream of consciousness"],
        formula: null,
        examTip: "When analysing narrative texts in comprehension, focus on HOW the story is told, not just WHAT happens. The examiner wants you to discuss narrative technique, not summarise the plot."
      },
      {
        title: "Language of Information",
        content: "Informative writing aims to educate, explain, or present facts clearly. It prioritises clarity and accuracy over emotional engagement.\n\nKey features of informative language:\n- Objective tone: Neutral, balanced, avoids personal bias (though some texts blend information with opinion).\n- Clear structure: Logical organisation with headings, subheadings, topic sentences, clear paragraphing.\n- Technical vocabulary: Subject-specific terms appropriate to the topic.\n- Facts and data: Statistics, dates, names, research findings, expert quotes.\n- Explanatory techniques: Definitions, examples, analogies, cause-and-effect explanations.\n- Visual language: References to diagrams, charts, illustrations (in print media).\n\nHow informative texts engage readers:\n- Surprising facts or statistics that challenge assumptions.\n- Concrete examples that make abstract concepts tangible.\n- Analogies that connect unfamiliar ideas to familiar ones.\n- Anecdotes that humanise data and facts.\n- Questions that invite curiosity before providing answers.\n\nBlended texts:\nMany LC comprehension texts blend information with persuasion or narrative. E.g., a science article might use storytelling techniques to explain research. Identify BOTH the informative and the persuasive/narrative elements.",
        keyTerms: ["objective tone", "technical vocabulary", "statistics", "analogy", "cause and effect", "topic sentence", "exposition", "clarity"],
        formula: null,
        examTip: "Informative texts often appear as Text 1 or Text 2 on Paper 1. When asked about style, don't just say 'informative' - identify the SPECIFIC techniques used to convey information effectively (e.g., 'use of statistics', 'expert testimony', 'concrete examples')."
      }
    ]
  },
  {
    topic: "Composition Types",
    icon: "✍️",
    subtopics: [
      {
        title: "Personal Essay",
        content: "The personal essay is a reflective piece where you explore your own thoughts, experiences, and feelings on a topic. It's one of the most popular composition choices because it allows genuine personal voice.\n\nStructure:\n- Introduction: Hook the reader with an anecdote, question, or striking statement. Introduce the topic and your angle.\n- Body (3-4 paragraphs): Each paragraph explores a different aspect, experience, or reflection. Move from specific memories to broader insights.\n- Conclusion: Reflect on what you've learned or how you've changed. Leave the reader with a thought-provoking final line.\n\nKey characteristics:\n- Authentic voice: Write as yourself. Let your personality come through.\n- Specific detail: Concrete memories and moments, not vague generalisations. \"I remember the smell of rain on hot tarmac\" beats \"I remember that day.\"\n- Reflection: Don't just describe - analyse. What did the experience MEAN? How did it change you?\n- Vulnerability: The best personal essays show honesty about doubts, mistakes, and growth.\n- Varied tone: Mix humour with seriousness, nostalgia with insight.\n\nCommon topics: disappointments, turning points, people who influenced you, lessons learned, identity, belonging, growing up.\n\nPCLM breakdown:\n- Purpose (30): Clear engagement with the topic, sustained personal voice.\n- Coherence (30): Logical flow, good paragraphing, clear structure.\n- Language (30): Varied vocabulary, imagery, sentence variety, appropriate tone.\n- Mechanics (10): Spelling, grammar, punctuation accuracy.",
        keyTerms: ["reflection", "anecdote", "personal voice", "vulnerability", "insight", "specific detail", "introspection"],
        formula: null,
        examTip: "The personal essay is marked on quality of reflection, not drama of events. A beautifully written essay about making tea with your grandmother will outscore a poorly written essay about skydiving. Depth beats excitement."
      },
      {
        title: "Short Story",
        content: "The short story requires creative writing skills - character, plot, setting, dialogue, and atmosphere. You have about 60-75 minutes to write approximately 800-1200 words.\n\nStructure:\n- Opening: Establish character, setting, and tone immediately. Hook the reader in the first paragraph. Drop them into the action.\n- Rising action: Build conflict and tension. Develop character through actions and dialogue, not description.\n- Climax: The turning point - moment of greatest tension, revelation, or change.\n- Resolution: Brief but satisfying. Show the consequence or change. Don't over-explain.\n\nEssential techniques:\n- Show don't tell: \"His jaw clenched and he turned away\" not \"He was angry.\"\n- Sensory detail: Sight, sound, smell, touch, taste. Ground the reader in the scene.\n- Dialogue: Reveals character and advances plot. Keep it natural - people speak in fragments, interrupt, trail off.\n- Varied sentences: Short sentences for tension. Longer ones for description or reflection.\n- Strong opening: \"The letter arrived on a Tuesday\" is better than \"Once upon a time.\"\n- Satisfying ending: Can be twist, resolution, open-ended, circular (return to opening image). Avoid \"and then I woke up.\"\n\nCommon mistakes:\n- Too much happens (keep it focused - one main event/conflict).\n- All telling, no showing.\n- Unrealistic dialogue.\n- Rushed ending because of poor time management.\n- No character development or change.",
        keyTerms: ["protagonist", "antagonist", "conflict", "climax", "resolution", "dialogue", "show don't tell", "sensory detail", "narrative arc", "denouement"],
        formula: null,
        examTip: "Plan your story in 5 minutes before writing. Know your ending before you start. A planned 800-word story with clear structure will score higher than a rambling 1500-word story that runs out of time for a proper ending."
      },
      {
        title: "Speech",
        content: "A speech is a persuasive or informative piece delivered to a specific audience. It must sound like it's meant to be spoken aloud.\n\nStructure:\n- Opening: Greeting + hook. \"Good morning, ladies and gentlemen. Imagine for a moment...\" or \"Today, I want to challenge everything you think you know about...\"\n- Body (3-4 points): Each point developed with evidence, examples, anecdotes. Use transitions: \"My second point is...\", \"Furthermore...\", \"But here's the thing...\"\n- Conclusion: Summarise, call to action, memorable closing line. \"So I ask you today...\", \"The choice is ours...\"\n\nSpeech-specific techniques:\n- Direct address: \"You\", \"we\", \"us\" - creates connection with audience.\n- Rhetorical questions: \"Can we really afford to ignore this?\" - engages audience thinking.\n- Anaphora (repetition): \"We will fight... We will not surrender... We will prevail...\" - builds rhythm and emphasis.\n- Rule of three: \"Education, opportunity, and hope\" - creates memorable phrasing.\n- Contrast/antithesis: \"It's not about what we take, but what we give.\"\n- Personal anecdote: Brief stories that humanise your argument.\n- Humour: Used sparingly to engage and disarm. Self-deprecating humour works well.\n- Emotive language: Words that provoke feeling - \"heartbreaking\", \"inspiring\", \"devastating\".\n- Pauses (indicated by short sentences or dashes): Create dramatic emphasis.\n\nTone: Confident, engaging, passionate but controlled. Vary between serious and lighter moments.",
        keyTerms: ["rhetoric", "direct address", "anaphora", "rule of three", "call to action", "inclusive language", "antithesis", "audience engagement"],
        formula: null,
        examTip: "Remember this is a SPEECH not an essay. Use conversational markers: 'Now, some of you might be thinking...', 'Let me tell you a story...', 'Picture this...'. Examiners look for awareness of audience and oral delivery."
      },
      {
        title: "Feature Article",
        content: "A feature article is a piece of magazine or newspaper journalism that explores a topic in depth. It's more in-depth and personal than a news report, blending facts with analysis and opinion.\n\nStructure:\n- Headline: Catchy, informative, may use wordplay or intrigue. \"The Hidden Cost of Fast Fashion\" or \"Why Ireland's Teens Are Turning Off Their Phones.\"\n- Subheading (optional): One-line summary or expansion of headline.\n- Introduction: Engaging lead paragraph - start with an anecdote, startling fact, vivid description, or provocative question.\n- Body: Mix of paragraphs covering different angles: facts/statistics, expert quotes, personal observations, case studies, analysis.\n- Conclusion: Circle back to opening, leave reader with insight, question, or call to reflection.\n\nKey characteristics:\n- Informative but engaging: Not dry facts - tell the story behind the facts.\n- Varied paragraph types: Mix short punchy paragraphs with longer developed ones.\n- Accessible tone: Intelligent but not academic. Conversational without being informal.\n- Subheadings: Can be used to break up sections (optional in exam but shows awareness of format).\n- Statistics and evidence: Ground your article in real (or realistic) facts.\n- Human interest: Include quotes, personal stories, case studies to bring the topic alive.\n- Balance: Show multiple perspectives even if you lean one way.",
        keyTerms: ["headline", "lead paragraph", "byline", "subheading", "human interest", "case study", "feature writing", "journalistic style"],
        formula: null,
        examTip: "A feature article is NOT a formal essay and NOT a news report. It sits between the two - informative but with personality. Include a headline. Start with something that grabs attention. Mix factual content with personal reflection."
      },
      {
        title: "Discursive Essay",
        content: "A discursive essay explores a topic from multiple angles, weighing up different perspectives before reaching a balanced conclusion. It's more analytical and less personal than a personal essay.\n\nStructure:\n- Introduction: Introduce the topic, provide context, state your thesis or the question you're exploring. \"The debate around [topic] has never been more relevant...\"\n- Body paragraphs (4-5): Each paragraph presents a different argument or perspective. Include both sides. Develop each point with evidence.\n  - Para 1-2: Arguments FOR\n  - Para 3-4: Arguments AGAINST (or counterarguments)\n  - OR alternate point/counterpoint throughout\n- Conclusion: Weigh up the arguments and state your considered view. \"On balance...\", \"Having considered both sides...\", \"Ultimately...\"\n\nKey characteristics:\n- Balanced exploration: Show you understand multiple viewpoints.\n- Evidence-based: Support points with examples, facts, statistics, expert views.\n- Formal but engaging: More formal than personal essay, but still readable.\n- Clear signposting: \"On the one hand...\", \"Conversely...\", \"However...\", \"A further consideration is...\"\n- Critical thinking: Don't just list points - analyse and evaluate them.\n- Strong thesis: Even though it's balanced, you should have a clear position by the end.\n\nCommon topics: technology, social media, education, environment, politics, ethics, culture.",
        keyTerms: ["thesis", "counterargument", "analysis", "evaluation", "signposting", "balanced argument", "evidence", "perspective", "critical thinking"],
        formula: null,
        examTip: "The discursive essay rewards sophistication of thought. Don't just list 'pros and cons' - show how arguments interact, qualify each other, and lead to a nuanced conclusion. Examiners want to see you THINK, not just describe."
      }
    ]
  },
  {
    topic: "Paper 2 Single Text",
    icon: "🎭",
    subtopics: [
      {
        title: "Approaching a Text",
        content: "The Single Text question (60 marks) tests your in-depth knowledge of ONE prescribed text. You choose one question from two options on your studied text.\n\n2025 prescribed texts:\n- The Tenant of Wildfell Hall (Anne Bronte)\n- All the Light We Cannot See (Anthony Doerr)\n- The Crucible (Arthur Miller)\n- King Lear (William Shakespeare)\n- Frankenstein (Mary Shelley)\n\nHow to prepare:\n- Read the text at least twice. First for plot, second for analysis.\n- Keep a quotation bank: 15-20 key quotes with page references, organised by theme/character.\n- Know the text's context: when written, why, historical background.\n- Identify 4-5 major themes and be able to discuss each with specific textual evidence.\n- Understand all major and minor characters and their roles in developing themes.\n- Know the writer's techniques: narrative style, use of imagery, symbolism, structure.\n\nAnswer structure (60 marks):\n- Introduction (5 min): State your argument clearly. Show you understand the question. Preview your main points.\n- Body paragraphs (45 min): 4-5 developed paragraphs. Each with: point, textual evidence (quote), analysis of technique, link to question.\n- Conclusion (5 min): Synthesise your argument. Don't introduce new ideas. Show how your points connect.\n\nMarking: Relevance/Insight (15), Argument/Support (30), Language/Style (10), Mechanics (5).",
        keyTerms: ["prescribed text", "textual evidence", "close reading", "quotation", "context", "interpretation", "critical analysis"],
        formula: null,
        examTip: "You have about 60 minutes for 60 marks. Spend 5 minutes planning. The biggest mistake is retelling the plot instead of answering the question. Every paragraph should directly address the question asked."
      },
      {
        title: "Themes",
        content: "Themes are the central ideas or messages explored in a text. Examiners frequently ask about themes because they test your understanding of WHAT the text is really about, beyond the surface plot.\n\nCommon themes across LC texts:\n- Power and powerlessness: Who holds power? How is it used/abused? Who is powerless and why?\n- Justice and injustice: Is justice achieved? What forces prevent it? What does the text say about fairness?\n- Identity and self-knowledge: How do characters understand themselves? How does identity change?\n- Appearance vs reality: What gaps exist between how things appear and how they truly are?\n- Love and relationships: What forms of love are shown? How do relationships help or harm characters?\n- Isolation and belonging: Who is isolated and why? What does community/belonging mean?\n- Moral conflict: What moral choices do characters face? What do their choices reveal?\n- Ambition: What drives characters? When does ambition become destructive?\n- Truth and deception: Who tells the truth? Who lies? What are the consequences?\n\nHow to discuss themes in the exam:\n- State the theme clearly.\n- Show how it develops through the text (beginning, middle, end).\n- Use specific scenes, quotes, and character actions as evidence.\n- Analyse HOW the writer presents the theme (through imagery, symbolism, structure, dialogue).\n- Connect to the question asked - don't just describe the theme, answer the QUESTION about it.",
        keyTerms: ["theme", "motif", "symbolism", "central idea", "universal truth", "moral message", "subtext"],
        formula: null,
        examTip: "Never just identify a theme - always discuss how the writer PRESENTS it. 'Miller explores the theme of justice' is weak. 'Miller exposes the failure of justice through the court scenes, where Danforth's rigid adherence to spectral evidence reveals how legal systems can be corrupted by fear' is strong."
      },
      {
        title: "Characters",
        content: "Character analysis is central to Paper 2. You need to understand not just WHAT characters do, but WHY they do it, and HOW the writer creates them.\n\nAspects of character to analyse:\n- Motivation: What drives the character? What do they want? What are they afraid of?\n- Development/arc: How does the character change from beginning to end? What causes the change?\n- Relationships: How do they relate to other characters? What do these relationships reveal?\n- Flaws and strengths: What makes them human? What are their virtues and failings?\n- Function in the text: What role does this character play in developing themes? Are they a foil, antagonist, catalyst?\n- Credibility: How does the writer make the character believable? Through dialogue, actions, thoughts, descriptions?\n\nTechniques writers use to create character:\n- Dialogue: What characters say and HOW they say it reveals personality, education, class, emotions.\n- Actions: What characters DO matters more than what they say. Actions reveal true nature.\n- Interior monologue/soliloquy: Direct access to thoughts and feelings.\n- Other characters' reactions: How others respond to a character tells us about them.\n- Physical description: Appearance can reflect inner qualities (or contrast with them).\n- Symbolism: Objects, settings, or imagery associated with a character.\n- Stage directions (drama): Physical actions, tone, pauses reveal character.\n\nKey literary terms for character:\n- Protagonist: Main character the story centres on.\n- Antagonist: Character who opposes the protagonist.\n- Foil: Character who contrasts with another to highlight specific qualities.\n- Tragic hero: Character of high status whose flaw leads to their downfall.\n- Anti-hero: Protagonist who lacks traditional heroic qualities.",
        keyTerms: ["protagonist", "antagonist", "foil", "tragic hero", "character arc", "motivation", "credibility", "soliloquy", "dialogue", "characterisation"],
        formula: null,
        examTip: "When writing about characters, always connect character analysis to THEME. Don't just describe what Proctor does - explain what his choices REVEAL about conscience, integrity, or the human condition. Character analysis should serve your overall argument."
      },
      {
        title: "Style and Techniques",
        content: "Style refers to HOW a writer tells their story - the distinctive choices they make in language, structure, and technique. Understanding style is essential for the Single Text.\n\nLanguage and diction:\n- Formal vs informal register: Does the language match the period/setting?\n- Imagery: Metaphor, simile, personification - what mental pictures does the writer create?\n- Symbolism: Objects, colours, settings that represent deeper meanings.\n- Tone: The writer's attitude - ironic, tragic, comic, satirical, lyrical.\n- Diction: Specific word choices that create effects.\n\nStructure:\n- Chronological vs non-linear: Is the story told in order or with flashbacks/flash-forwards?\n- Opening and closing: How does the text begin and end? Any parallels or contrasts?\n- Climax and turning points: Where is the moment of greatest tension or change?\n- Pacing: Where does the text speed up or slow down? Why?\n- Acts and scenes (drama): How is the play divided? What happens at act breaks?\n\nNarrative techniques:\n- Point of view: Whose perspective are we given? What are we shown vs hidden?\n- Unreliable narrator: Can we trust the narrator's account?\n- Dramatic irony: When the audience knows something the character doesn't.\n- Foreshadowing: Hints about what will happen.\n- Pathetic fallacy: When weather/setting reflects characters' emotions.\n\nDrama-specific:\n- Soliloquy: Character speaks thoughts aloud, alone on stage.\n- Aside: Brief comment to audience, unheard by other characters.\n- Stage directions: Physical actions, setting, tone indicated by the playwright.",
        keyTerms: ["style", "diction", "imagery", "symbolism", "structure", "dramatic irony", "foreshadowing", "pathetic fallacy", "soliloquy", "aside", "register"],
        formula: null,
        examTip: "Style questions are about the WRITER'S CRAFT, not the story. Focus on technique: 'Shakespeare uses the storm in Act 3 as pathetic fallacy to mirror Lear's inner turmoil' shows awareness of craft. Simply describing the storm does not."
      }
    ]
  },
  {
    topic: "Comparative Study",
    icon: "⚖️",
    subtopics: [
      {
        title: "Cultural Context",
        content: "Cultural Context examines the world of the text - the society, values, norms, and historical setting that shape characters and events.\n\nWhat to look for:\n- Social structures: Class system, hierarchy, who holds power in society.\n- Gender roles: How are men and women expected to behave? Who conforms? Who rebels?\n- Economic conditions: Wealth, poverty, work, class mobility.\n- Religious/moral values: What beliefs guide the society? How are they enforced?\n- Historical period: When is the text set? What was happening in that era?\n- Family structures: Marriage, parenthood, family dynamics, inheritance.\n- Education and knowledge: Who has access to education? What role does it play?\n- Law and justice: How does the legal system work? Is it fair?\n- Community and belonging: Who belongs? Who is excluded? Why?\n\nComparing Cultural Contexts:\n- Look for similarities: Both texts may show patriarchal societies, or rigid class systems, or the consequences of conformity.\n- Look for differences: One text may show a community that protects its members while another shows one that destroys them.\n- Consider how cultural context SHAPES characters: Does the society enable or restrict them?\n- Consider how characters RESPOND to their context: Do they conform, rebel, escape, or adapt?\n\nPart (a) - 30 marks: Discuss ONE text in depth. Show how cultural context influences a central character's behaviour.\nPart (b) - 40 marks: COMPARE how cultural context influences characters in TWO other texts. Must use comparison language throughout.",
        keyTerms: ["cultural context", "social norms", "patriarchy", "class system", "conformity", "rebellion", "values", "power structures", "marginalisation"],
        formula: null,
        examTip: "Cultural Context is NOT just about describing the setting. You must show how the society INFLUENCES characters and events. Always connect the context to character behaviour and outcomes."
      },
      {
        title: "General Vision and Viewpoint",
        content: "General Vision and Viewpoint (GV&V) examines the overall outlook of a text - whether it presents an optimistic or pessimistic view of life, and how characters' experiences shape the reader's sense of hope or despair.\n\nKey concepts:\n- Optimistic vision: Characters overcome challenges, find meaning, achieve justice or happiness. The text suggests life can improve.\n- Pessimistic vision: Characters are defeated, corrupted, or destroyed. The text suggests the world is fundamentally unfair or bleak.\n- Mixed/ambiguous vision: Most texts contain BOTH. The best answers explore this complexity.\n\nWhat contributes to vision:\n- Character outcomes: Do characters achieve what they want? Are good characters rewarded? Are villains punished?\n- Tone: Is the overall mood hopeful, tragic, ironic, satirical, bittersweet?\n- Ending: How does the text end? Resolution, ambiguity, tragedy, triumph?\n- Key moments: Turning points that shift the vision from hope to despair or vice versa.\n- Relationships: Do relationships sustain characters or destroy them?\n- Justice: Is justice achieved? If not, what does this suggest about the world?\n- Human nature: Does the text suggest people are fundamentally good, evil, or complex?\n\nComparing GV&V:\n- Compare the overall outlook of each text (optimistic vs pessimistic).\n- Compare specific moments that establish the vision.\n- Compare character journeys - do they end in triumph or defeat?\n- Consider whether different texts offer hope in different ways.\n- Use comparison language: 'While Text A offers a bleak vision through..., Text B provides more hope because...'\n\nCommon pitfall: Don't just label texts as 'optimistic' or 'pessimistic'. Show the COMPLEXITY - most texts have elements of both.",
        keyTerms: ["general vision", "viewpoint", "optimistic", "pessimistic", "ambiguous", "tone", "outlook", "resolution", "human nature", "bittersweet"],
        formula: null,
        examTip: "The strongest GV&V answers acknowledge complexity. Saying 'The Crucible is pessimistic because Proctor dies' is simplistic. Saying 'While Proctor's death creates a tragic vision, his refusal to betray his conscience offers a thread of moral optimism - suggesting integrity can survive even in the darkest circumstances' shows nuance."
      },
      {
        title: "Literary Genre",
        content: "Literary Genre examines the conventions, forms, and techniques that define different types of literature - and how writers use, adapt, or subvert these conventions.\n\nKey genres on the LC course:\n- Tragedy: Features a protagonist of high status whose flaw (hamartia) leads to downfall. Follows pattern: exposition, rising action, climax, falling action, catastrophe. Evokes pity and fear (catharsis). E.g., King Lear.\n- Drama/Play: Written to be performed. Uses dialogue, stage directions, acts/scenes. Conflict drives the action. E.g., The Crucible.\n- Novel: Extended prose fiction with developed characters, plot, themes, and setting. Can be any sub-genre.\n- Gothic fiction: Dark settings, supernatural elements, extreme emotions, mystery, isolation. E.g., Frankenstein.\n- Film: Visual storytelling using cinematography, editing, sound, mise-en-scene, dialogue.\n\nGenre conventions to discuss:\n- Setting: How does setting create atmosphere appropriate to the genre?\n- Character types: Does the text use genre-specific character types (tragic hero, villain, ingenue)?\n- Plot structure: Does it follow expected genre patterns or subvert them?\n- Tone and mood: How does the genre shape the emotional atmosphere?\n- Themes: What themes are typical of this genre?\n- Audience expectations: How does the writer meet or surprise genre expectations?\n\nComparing genres:\n- How do different genres tell similar stories differently?\n- What does the genre allow or restrict in terms of storytelling?\n- How do genre conventions shape audience response?",
        keyTerms: ["genre", "convention", "tragedy", "hamartia", "catharsis", "gothic", "dramatic form", "subversion", "narrative form", "cinematic techniques"],
        formula: null,
        examTip: "When comparing genres, focus on how the FORM of each text shapes meaning. A tragic play creates meaning through dialogue and performance; a novel creates it through prose and interiority. Show you understand that genre is not just a label but a set of tools the writer uses."
      },
      {
        title: "Comparison Techniques",
        content: "The Comparative Study requires you to explicitly COMPARE texts - not write separate essays about each one. This is the most common mistake students make.\n\nStructure for Part (b) - 40 marks:\nOption 1 - Point-by-point comparison:\n- Point 1: Compare how both texts handle aspect X.\n- Point 2: Compare how both texts handle aspect Y.\n- Point 3: Compare how both texts handle aspect Z.\nThis is the BEST structure for comparative answers.\n\nOption 2 - Block comparison (less effective):\n- Text A discussion (but with forward references to Text B)\n- Text B discussion (with constant references back to Text A)\nRisky because it can become two separate essays.\n\nComparison language (ESSENTIAL - use these phrases):\nSimilarity: \"Similarly...\", \"In the same way...\", \"Both texts...\", \"Likewise...\", \"Just as Text A shows..., Text B also...\", \"This is echoed in...\"\nDifference: \"In contrast...\", \"However...\", \"Unlike...\", \"While Text A..., Text B...\", \"Whereas...\", \"On the other hand...\", \"Conversely...\"\nNuance: \"Although both texts explore..., they do so in markedly different ways...\", \"While there are surface similarities, the underlying message differs...\", \"To a greater/lesser extent...\"\n\nWhat examiners look for:\n- Sustained comparison throughout (not just at the start/end).\n- Specific textual evidence from BOTH texts.\n- Genuine analytical comparison (not just 'Text A has X, Text B also has X').\n- Understanding of HOW texts are similar or different, and WHY.\n- Appropriate focus on the mode (theme/cultural context/GV&V).",
        keyTerms: ["comparison", "contrast", "similarity", "difference", "point-by-point", "textual evidence", "linking phrases", "sustained comparison", "nuance"],
        formula: null,
        examTip: "Use at least one comparison phrase in EVERY paragraph of Part (b). Examiners literally look for comparison language. A paragraph that discusses one text without referencing the other will lose marks, no matter how good the analysis is."
      }
    ]
  },
  {
    topic: "Unseen Poetry",
    icon: "🌙",
    subtopics: [
      {
        title: "Analysis Techniques",
        content: "The Unseen Poem (20 marks) tests your ability to analyse a poem you've never seen before. You have about 20 minutes.\n\nStep-by-step approach:\n1. Read the poem three times:\n   - First reading: Get the overall meaning and feeling. What is it about?\n   - Second reading: Look for techniques and patterns. What do you notice?\n   - Third reading: Focus on specific lines and words. What stands out?\n\n2. Consider the basics:\n   - Subject: What is the poem about? (Literal level)\n   - Theme: What deeper idea is being explored? (Figurative level)\n   - Speaker: Who is speaking? What is their perspective/attitude?\n   - Audience: Who is being addressed?\n   - Tone: What is the emotional atmosphere? Does it change?\n   - Structure: How is the poem organised? Stanzas, line length, rhyme?\n\n3. Identify techniques:\n   - Imagery: What pictures are created? What senses are engaged?\n   - Figurative language: Metaphor, simile, personification, symbolism.\n   - Sound devices: Alliteration, assonance, consonance, onomatopoeia, rhyme.\n   - Structural devices: Enjambment, caesura, stanza breaks, line length variation.\n   - Repetition: Words, phrases, or structures that recur.\n   - Contrast: Opposing ideas, images, or tones.\n\n4. Write your response:\n   - Answer the specific question asked.\n   - Use short, integrated quotes from the poem.\n   - Name techniques and explain their EFFECT.\n   - Don't just identify - analyse. Say WHY the poet uses this technique and what it ACHIEVES.",
        keyTerms: ["close reading", "annotation", "literal meaning", "figurative meaning", "speaker", "tone", "mood", "subject", "theme"],
        formula: null,
        examTip: "For the unseen poem, you choose between Question 1 (two shorter parts worth 10+10) or Question 2 (one longer response worth 20). If you find the poem difficult to understand, choose Question 1 - the two parts give you more guidance. If you feel confident, Question 2 lets you develop a fuller analysis."
      },
      {
        title: "Language Features in Poetry",
        content: "Recognising and discussing language features is the core skill for unseen poetry analysis. Here are the key features with examples of how to discuss them.\n\nImagery:\n- Visual imagery: Creates pictures in the reader's mind. \"The sun bled across the horizon.\"\n- Auditory imagery: Creates sound. \"The clock ticked its relentless rhythm.\"\n- Tactile imagery: Creates sensation of touch. \"The rough bark scraped her palms.\"\n- Olfactory/gustatory: Smell and taste. Less common but powerful when used.\n\nFigurative language:\n- Metaphor: Direct comparison. \"Time is a thief.\" Identifies one thing AS another.\n- Extended metaphor: A metaphor developed across several lines or the whole poem.\n- Simile: Comparison using like/as. \"Her voice was like honey.\"\n- Personification: Giving human qualities to non-human things. \"The wind whispered.\"\n- Symbolism: An object representing a larger concept. A rose = love, a road = life journey.\n\nSound devices:\n- Alliteration: Repeated initial consonants. Creates rhythm, emphasis, or mood.\n- Assonance: Repeated vowel sounds. Creates musicality or mood.\n- Consonance: Repeated consonant sounds within or at end of words.\n- Onomatopoeia: Words that sound like what they describe (buzz, crash, murmur).\n- Rhyme: End rhyme, internal rhyme, half-rhyme, slant rhyme.\n\nStructural devices:\n- Enjambment: Line runs on to next without punctuation. Creates flow, urgency, or continuation.\n- Caesura: Pause mid-line (usually punctuation). Creates emphasis, reflection, or dramatic effect.\n- Volta: A \"turn\" in the poem where meaning or tone shifts. Often at a stanza break.\n- Stanza structure: Regular stanzas suggest order; irregular suggests chaos or freedom.\n- Line length: Short lines = emphasis, urgency. Long lines = flow, expansion.",
        keyTerms: ["imagery", "metaphor", "simile", "personification", "alliteration", "assonance", "enjambment", "caesura", "volta", "rhyme scheme", "onomatopoeia", "symbolism"],
        formula: null,
        examTip: "Don't just list techniques - explain their EFFECT. Instead of 'The poet uses alliteration in line 3', write 'The alliteration of the harsh \"c\" sound in \"cold, cruel, cutting\" mirrors the brutality being described, making the reader almost feel the harshness.' Technique + Quote + Effect = marks."
      }
    ]
  },
  {
    topic: "Exam Techniques",
    icon: "🎯",
    subtopics: [
      {
        title: "Time Management",
        content: "Time management is one of the most important skills for LC English. Poor timing is the single biggest reason students underperform.\n\nPaper 1 - 170 minutes, 200 marks:\n- 9:30-9:40: Read all 3 texts, decide which to use for Q-A and Q-B (10 min)\n- 9:40-10:20: Question A on your chosen text (40 min for 50 marks)\n- 10:20-11:00: Question B on a DIFFERENT text (40 min for 50 marks)\n- 11:00-11:05: Read all 7 composition options, choose one (5 min)\n- 11:05-11:15: Plan your composition - outline, key points, structure (10 min)\n- 11:15-12:15: Write your composition (60 min for 100 marks)\n- 12:15-12:20: Proofread and review (5 min)\n\nPaper 2 - 200 minutes, 200 marks:\n- 2:00-2:05: Read all questions across all sections (5 min)\n- 2:05-3:05: Single Text (60 min for 60 marks)\n- 3:05-4:15: Comparative Study (70 min for 70 marks)\n- 4:15-4:35: Unseen Poem (20 min for 20 marks)\n- 4:35-5:15: Prescribed Poetry (40 min for 50 marks)\n- 5:15-5:20: Review all answers (5 min)\n\nGolden rule: 1 mark = approximately 1 minute. Never spend 90 minutes on a 50-mark question.\n\nIf you're running out of time:\n- Write your remaining points in bullet form rather than leaving them blank.\n- A partial answer earns partial marks. A blank page earns zero.\n- Prioritise sections worth the most marks.",
        keyTerms: ["time allocation", "planning", "proofreading", "prioritisation"],
        formula: null,
        examTip: "Wear a watch. Set mini-deadlines for each section. When your time is up, MOVE ON. An incomplete answer on one question plus a complete answer on the next will ALWAYS outscore a perfect answer on one and a blank on the other."
      },
      {
        title: "Marking Criteria - PCLM",
        content: "All extended writing in LC English is assessed using the PCLM criteria. Understanding these helps you know exactly what examiners are looking for.\n\nP - Clarity of Purpose (30 marks):\n- Have you understood and fulfilled the task?\n- Is your response focused and sustained?\n- Do you show clear engagement with the question/topic?\n- Is your purpose clear throughout (to argue, narrate, describe, analyse, persuade)?\nHow to maximise: State your purpose/position clearly in your introduction. Every paragraph should serve your overall purpose. Stay on topic.\n\nC - Coherence of Delivery (30 marks):\n- Is your response well-structured and organised?\n- Do your paragraphs flow logically from one to the next?\n- Is there a clear introduction, development, and conclusion?\n- Are transitions smooth and effective?\nHow to maximise: Plan before writing. Use topic sentences. Link paragraphs with transition words. Each paragraph = one main idea.\n\nL - Efficiency of Language Use (30 marks):\n- Is your vocabulary varied and appropriate?\n- Are your sentences varied in length and structure?\n- Is your style appropriate to the task (formal for essay, conversational for speech)?\n- Do you use literary/rhetorical devices effectively?\nHow to maximise: Avoid repeating the same words. Mix short and long sentences. Use specific vocabulary, not vague words. Show range.\n\nM - Accuracy of Mechanics (10 marks):\n- Is your spelling accurate?\n- Is your grammar correct?\n- Is your punctuation used properly?\n- Is your tense consistent?\nHow to maximise: Proofread. Check apostrophes, comma splices, and tense consistency. If unsure of a spelling, use a different word.",
        keyTerms: ["PCLM", "purpose", "coherence", "language", "mechanics", "marking criteria", "assessment"],
        formula: null,
        examTip: "Mechanics is only 10 marks, but LANGUAGE is 30. This means your writing style matters three times more than correct spelling. Focus on sophisticated, varied language. Don't play it safe with simple sentences just to avoid errors - take controlled risks with your vocabulary and style."
      },
      {
        title: "Question Decoding",
        content: "Understanding what the question is REALLY asking is crucial. Many students lose marks by misreading or partially answering questions.\n\nKey instruction words:\n- \"Discuss\": Explore the topic in depth, considering different angles. Give your view with evidence.\n- \"To what extent do you agree?\": Take a clear position (agree/disagree/partially agree) and ARGUE it with evidence. Don't sit on the fence.\n- \"Analyse\": Break down into components and examine each in detail. How does it work? Why?\n- \"Compare\": Show similarities AND differences between texts. Use comparison language.\n- \"Evaluate\": Judge the effectiveness/success of something. Give your assessment with reasons.\n- \"Explain\": Make something clear. Show you understand HOW or WHY something works.\n- \"Respond\": Give your personal reaction, supported by references to the text.\n\nCommon question patterns on Paper 1:\n- \"What insights do you gain...?\" = Identify 3 key things the text reveals. Support each with a reference.\n- \"Elements of language that are effective...\" = Identify 4 techniques, quote examples, explain their effects.\n- Functional writing (Q-B): Always address ALL bullet points. Missing one loses significant marks.\n\nCommon question patterns on Paper 2:\n- Single Text: Usually about themes OR literary techniques. One broad, one focused.\n- Comparative: Part (a) = depth on one text. Part (b) = comparison of two texts.\n- Poetry: Either mood/title questions OR language effectiveness.",
        keyTerms: ["discuss", "analyse", "evaluate", "compare", "instruction words", "question decoding", "bullet points"],
        formula: null,
        examTip: "Before writing, underline the KEY WORDS in the question. If it says 'To what extent', you MUST state a position. If it says 'four elements', you MUST discuss exactly four. If Question B has bullet points, tick each one off as you address it. Answering the wrong question is the fastest way to lose marks."
      }
    ]
  },
  {
    topic: "Key Literary Terms",
    icon: "📚",
    subtopics: [
      {
        title: "Figures of Speech",
        content: "Figures of speech are expressions that use words in non-literal ways to create effects. They are the building blocks of literary analysis.\n\nMetaphor: Describes something by saying it IS something else. \"Life is a journey.\" \"Time is a thief.\" Creates direct, powerful comparison. Extended metaphor = a metaphor developed across several lines or an entire text.\n\nSimile: Comparison using 'like' or 'as'. \"Her eyes sparkled like diamonds.\" \"He ran as fast as the wind.\" More explicit than metaphor.\n\nPersonification: Giving human qualities to non-human things. \"The wind howled.\" \"Justice is blind.\" Makes abstract concepts tangible.\n\nHyperbole: Deliberate exaggeration for emphasis. \"I've told you a million times.\" \"This bag weighs a ton.\" Not meant literally - used for effect.\n\nUnderstatement (Litotes): Deliberately representing something as less than it is. \"It's just a scratch\" (about a serious wound). Often ironic.\n\nOxymoron: Two contradictory words together. \"Bittersweet.\" \"Deafening silence.\" \"Living dead.\" Highlights paradox or complexity.\n\nParadox: A statement that seems contradictory but reveals a deeper truth. \"The only way to find yourself is to lose yourself.\"\n\nIrony: Gap between appearance and reality. Verbal irony = saying the opposite of what you mean. Dramatic irony = audience knows something characters don't. Situational irony = outcome is opposite to expectation.\n\nAllusion: A reference to another text, event, person, or cultural element. \"He was a real Romeo\" (allusion to Shakespeare). Assumes reader knowledge.\n\nEuphemism: A mild expression substituted for a harsh one. \"Passed away\" instead of \"died.\" \"Let go\" instead of \"fired.\"",
        keyTerms: ["metaphor", "simile", "personification", "hyperbole", "litotes", "oxymoron", "paradox", "irony", "allusion", "euphemism"],
        formula: null,
        examTip: "When you identify a figure of speech, always follow up with its EFFECT. Don't just say 'The writer uses a metaphor.' Say 'The metaphor of time as a thief suggests something valuable is being stolen from us, creating a sense of urgency and loss.' Technique + Effect = full marks."
      },
      {
        title: "Sound and Structural Devices",
        content: "Sound devices create rhythm, mood, and emphasis through the sounds of words. Structural devices shape how a text is organised and how meaning unfolds.\n\nSound devices:\n- Alliteration: Repetition of initial consonant sounds. \"Peter Piper picked...\" Creates rhythm and emphasis. Harsh consonants (k, t, g) can create aggression; soft ones (l, m, s) create gentleness.\n- Assonance: Repetition of vowel sounds within words. \"The rain in Spain falls mainly on the plain.\" Creates musicality and mood.\n- Consonance: Repetition of consonant sounds within or at the end of words. \"Pitter patter\" - the repeated 't' sound.\n- Onomatopoeia: Words that imitate sounds. \"Buzz\", \"crash\", \"whisper\", \"sizzle.\" Creates sensory immediacy.\n- Sibilance: Repetition of 's' sounds. Creates whispering, sinister, or soothing effect.\n- Rhyme: End rhyme (at line ends), internal rhyme (within a line), half-rhyme/slant rhyme (near-rhyme). Creates pattern, expectation, musicality.\n\nStructural devices:\n- Anaphora: Repetition at the START of successive clauses. \"We shall fight on the beaches, we shall fight on the landing grounds...\" Builds momentum.\n- Epistrophe: Repetition at the END of successive clauses. \"Government of the people, by the people, for the people.\"\n- Juxtaposition: Placing contrasting ideas side by side. Highlights differences.\n- Antithesis: Balanced contrasting phrases. \"It was the best of times, it was the worst of times.\"\n- Climax (rhetorical): Building arguments in ascending order of importance.\n- Bathos: Sudden shift from the serious to the trivial, often for comic effect.\n\nNarrative structure:\n- In medias res: Starting in the middle of the action.\n- Foreshadowing: Hints about future events.\n- Flashback: Jump to an earlier time.\n- Circular structure: Ending where it began.\n- Parallel structure: Repeated grammatical patterns.",
        keyTerms: ["alliteration", "assonance", "consonance", "onomatopoeia", "sibilance", "anaphora", "epistrophe", "juxtaposition", "antithesis", "in medias res", "circular structure"],
        formula: null,
        examTip: "Sound devices are especially important for poetry and speech analysis. Read quotations ALOUD (in your head) to hear the effects. If you can hear the harshness of consonants or the softness of sibilance, say so - examiners reward students who engage with how language SOUNDS, not just what it means."
      },
      {
        title: "Narrative and Dramatic Terms",
        content: "These terms are essential for discussing prose fiction (novels, short stories) and drama (plays).\n\nNarrative terms:\n- Narrator: The voice telling the story. Not always the author.\n- Point of view (POV): The perspective from which the story is told (first person, third person limited, third person omniscient, second person).\n- Unreliable narrator: A narrator whose account cannot be fully trusted (due to bias, limited knowledge, or deception).\n- Stream of consciousness: Narrative technique presenting thoughts as they occur, without conventional structure.\n- Interior monologue: Extended representation of a character's thoughts.\n- Free indirect discourse: Blending narrator's voice with character's thoughts without quotation marks.\n- Exposition: Background information provided to the reader.\n- Rising action: Events building toward the climax.\n- Climax: Moment of greatest tension or dramatic intensity.\n- Falling action: Events after the climax leading to resolution.\n- Denouement: The final unraveling or resolution of the plot.\n- Subplot: A secondary storyline that parallels or contrasts with the main plot.\n\nDramatic terms:\n- Soliloquy: A character speaks their thoughts aloud, alone on stage. Reveals inner conflict.\n- Aside: A brief remark to the audience, unheard by other characters.\n- Dramatic irony: The audience knows something a character does not.\n- Tragic flaw (hamartia): The character weakness that leads to the hero's downfall.\n- Catharsis: The emotional release experienced by the audience at the end of a tragedy.\n- Chorus: In Greek/some modern drama, a group that comments on the action.\n- Staging/mise-en-scene: The visual arrangement of a scene.\n- Monologue: An extended speech by one character to other characters present.",
        keyTerms: ["narrator", "point of view", "unreliable narrator", "stream of consciousness", "exposition", "climax", "denouement", "soliloquy", "dramatic irony", "hamartia", "catharsis", "aside"],
        formula: null,
        examTip: "For drama texts like King Lear or The Crucible, always consider how the play would work on STAGE. Discuss how soliloquies reveal inner conflict, how dramatic irony creates tension for the AUDIENCE, and how staging choices (who is on stage, who exits) affect meaning."
      }
    ]
  },
  {
    topic: "Essay Structure and Planning",
    icon: "📝",
    subtopics: [
      {
        title: "Planning Your Essay",
        content: "Spending 5-10 minutes planning before you write is the single most impactful thing you can do to improve your grades. A planned essay is always better than an unplanned one.\n\nStep 1 - Read and decode the question (2 min):\n- Underline key words and instruction words.\n- What EXACTLY is being asked?\n- What type of response is required (discuss, compare, analyse, to what extent)?\n\nStep 2 - Brainstorm (3 min):\n- Jot down every relevant idea, quote, example, technique that comes to mind.\n- Don't filter yet - get everything down.\n- For comparative: brainstorm for EACH text.\n\nStep 3 - Select and organise (3 min):\n- Choose your 3-5 strongest points.\n- Arrange them in logical order (chronological? thematic? ascending importance?).\n- For each point, note the evidence you'll use (quote or reference).\n- Decide your opening hook and closing thought.\n\nStep 4 - Write a brief outline:\n- Intro: Hook + thesis/position\n- Para 1: [Point] - [Evidence]\n- Para 2: [Point] - [Evidence]\n- Para 3: [Point] - [Evidence]\n- Para 4: [Point] - [Evidence]\n- Conclusion: [Synthesis + final thought]\n\nThis plan should fit in the margin of your answer booklet. It takes 5-10 minutes but saves you 15-20 minutes of indecision and restructuring while writing.\n\nPlanning prevents:\n- Going off-topic\n- Repeating yourself\n- Running out of things to say\n- Forgetting key quotes\n- Writing an unstructured response",
        keyTerms: ["brainstorm", "outline", "thesis", "planning", "structure", "organisation"],
        formula: null,
        examTip: "Cross out your plan with a single line when you're done - the examiner will see you planned (which they appreciate) but won't mark it. If you run out of time, your plan shows the examiner what you WOULD have written."
      },
      {
        title: "Paragraph Structure",
        content: "Every body paragraph should follow a clear structure. This ensures your argument is developed, evidenced, and linked to the question.\n\nThe PEAL structure (works for all Paper 2 and most Paper 1 answers):\n\nP - Point: Start with a clear topic sentence that states the paragraph's main idea and links to the question.\nExample: \"Shakespeare uses the Fool as a dramatic device to expose Lear's failures as both king and father.\"\n\nE - Evidence: Provide specific textual evidence - a quote, reference to a scene, or specific detail.\nExample: \"The Fool tells Lear, 'Thou shouldst not have been old till thou hadst been wise,' directly criticising the king's decision to divide his kingdom.\"\n\nA - Analysis: Explain what the evidence shows. Discuss technique, language, effect. This is where you show your understanding.\nExample: \"The Fool's use of direct address and the conditional 'shouldst' implies that wisdom was within Lear's reach but he chose poorly. The inversion of the expected relationship - a fool instructing a king - creates dramatic irony and emphasises how far Lear has fallen.\"\n\nL - Link: Connect back to the question and/or transition to the next point.\nExample: \"This demonstrates Shakespeare's exploration of truth-telling, showing that in Lear's corrupted court, only the 'fool' dares speak honestly - a powerful commentary on how power silences truth.\"\n\nEach paragraph should be 8-12 sentences. Too short = underdeveloped. Too long = needs splitting.\n\nTransition between paragraphs:\n- \"Furthermore...\", \"Moreover...\", \"Building on this...\"\n- \"In contrast...\", \"However...\", \"On the other hand...\"\n- \"Similarly...\", \"This is also evident in...\"\n- \"Perhaps most significantly...\" (for your strongest point)",
        keyTerms: ["topic sentence", "evidence", "analysis", "link", "PEAL", "paragraph", "transition", "development"],
        formula: null,
        examTip: "The most common weakness examiners report is UNDERDEVELOPED paragraphs - students who make a point and quote but don't ANALYSE. The analysis section should be the LONGEST part of each paragraph. Don't just quote - explain what the quote reveals and HOW the technique works."
      },
      {
        title: "Introductions and Conclusions",
        content: "Strong openings and closings frame your essay effectively and leave a positive impression on the examiner.\n\nIntroduction structure (3-5 sentences):\n1. Hook: An engaging opening that catches attention. Can be a bold statement, a question, a relevant quote, or a striking observation.\n2. Context: Brief background - identify the text(s), author(s), and topic.\n3. Thesis/Position: State your main argument or the direction of your answer clearly.\n4. Preview (optional): Briefly indicate the points you'll develop.\n\nExample introduction:\n\"Power in The Crucible is not held by those with the highest position, but by those most willing to manipulate fear. [Hook] Arthur Miller's 1953 play, set during the Salem witch trials, exposes how authority can be weaponised when a society abandons reason for hysteria. [Context] This essay will argue that Miller presents power as fundamentally unstable and corrupting, operating through fear, reputation, and religious authority. [Thesis]\"\n\nConclusion structure (3-4 sentences):\n1. Synthesis: Draw your main points together. Don't just repeat them - show how they connect.\n2. Final assessment: State your overall view or judgment clearly.\n3. Wider significance: End with a broader thought - what does this mean beyond the text? Why does it matter?\n\nExample conclusion:\n\"Ultimately, Miller demonstrates that power built on fear is inherently fragile - it must constantly escalate to sustain itself, eventually consuming even those who wield it. Danforth, Abigail, and Parris all discover that the power they seized through the trials cannot protect them from its consequences. In this way, The Crucible remains devastatingly relevant - a reminder that any society that sacrifices truth for power is doomed to destroy itself.\"\n\nAvoid in conclusions:\n- \"In conclusion...\" (formulaic)\n- Introducing new points\n- Apologising (\"I may be wrong but...\")\n- Simply repeating the introduction",
        keyTerms: ["hook", "thesis", "context", "synthesis", "wider significance", "framing"],
        formula: null,
        examTip: "Your introduction and conclusion are the first and last things the examiner reads - they create the overall impression. A strong, confident opening signals that a good essay follows. A thoughtful conclusion elevates an average essay. Spend 2-3 minutes crafting each."
      }
    ]
  }
];
