var FLASHCARDS_CHEMISTRY = [
  // ===== ATOMIC STRUCTURE =====
  {cat:"atomic-structure", q:"Define Atomic Number (Z)", a:"The number of protons in the nucleus of an atom. Determines the element's identity and its position in the periodic table."},
  {cat:"atomic-structure", q:"Define Mass Number (A)", a:"The total number of protons and neutrons in the nucleus of an atom.\nA = Z + N (where N = number of neutrons)"},
  {cat:"atomic-structure", q:"Define Isotopes", a:"Atoms of the same element with the same number of protons but different numbers of neutrons (same atomic number, different mass number). Example: ¹²C and ¹⁴C."},
  {cat:"atomic-structure", q:"What are the main subatomic particles?", a:"Proton: mass 1, charge +1, in nucleus\nNeutron: mass 1, charge 0, in nucleus\nElectron: mass ~1/1840, charge -1, orbits nucleus in energy levels"},
  {cat:"atomic-structure", q:"Describe the Bohr Model of the atom", a:"Electrons orbit the nucleus in fixed energy levels (shells).\nMax electrons per shell: 2n² (n = shell number)\n1st: 2, 2nd: 8, 3rd: 18\nElectrons fill lowest energy levels first (Aufbau principle)."},
  {cat:"atomic-structure", q:"Write the electron configuration of Sodium (Na, Z=11)", a:"1s² 2s² 2p⁶ 3s¹\nSodium has 11 electrons.\nShorthand: 2, 8, 1\nGroup 1 (1 valence electron), Period 3."},
  {cat:"atomic-structure", q:"What is the Heisenberg Uncertainty Principle?", a:"It is impossible to simultaneously know both the exact position and exact momentum (velocity) of an electron. We can only describe the probability of finding an electron in a region (orbital)."},
  {cat:"atomic-structure", q:"Define Orbital", a:"A region of space around the nucleus where there is a high probability of finding an electron. Types: s (spherical), p (dumbbell), d (cloverleaf). Each orbital holds max 2 electrons (opposite spins — Pauli Exclusion)."},
  {cat:"atomic-structure", q:"State Hund's Rule", a:"When filling orbitals of equal energy (degenerate orbitals), electrons occupy them singly first with parallel spins before pairing up. Example: 2p³ → ↑_↑_↑_ not ↑↓_↑__ ."},

  // ===== BONDING =====
  {cat:"bonding", q:"Define Ionic Bonding", a:"The electrostatic attraction between oppositely charged ions. Formed when electrons are transferred from a metal to a non-metal. Example: NaCl (Na⁺ and Cl⁻)."},
  {cat:"bonding", q:"Define Covalent Bonding", a:"The sharing of one or more pairs of electrons between two non-metal atoms. Each atom contributes one electron to the shared pair. Example: H₂, H₂O, CO₂."},
  {cat:"bonding", q:"What is Electronegativity?", a:"The ability of an atom to attract a shared pair of electrons towards itself in a covalent bond. Increases across a period, decreases down a group. Most electronegative: Fluorine (4.0)."},
  {cat:"bonding", q:"Define a Polar Covalent Bond", a:"A covalent bond where electrons are shared unequally because the atoms have different electronegativities. Creates a dipole (δ+ and δ-). Example: H-Cl."},
  {cat:"bonding", q:"What are Van der Waals forces?", a:"The weakest intermolecular forces. Caused by temporary/induced dipoles in molecules. Strength increases with molecular size (more electrons). Present in all molecules (e.g., between I₂ molecules)."},
  {cat:"bonding", q:"What is a Hydrogen Bond?", a:"A strong intermolecular force between a hydrogen atom bonded to a highly electronegative atom (F, O, or N) and a lone pair on another F, O, or N atom. Explains high boiling point of water."},
  {cat:"bonding", q:"Explain the shape of a water molecule", a:"H₂O: 2 bonding pairs + 2 lone pairs around oxygen.\nShape: bent/V-shaped\nBond angle: 104.5° (less than tetrahedral 109.5° because lone pairs repel more than bonding pairs).\nVSEPR theory."},
  {cat:"bonding", q:"What is VSEPR Theory?", a:"Valence Shell Electron Pair Repulsion Theory: electron pairs around a central atom arrange themselves to be as far apart as possible to minimise repulsion.\nLinear (180°), Trigonal planar (120°), Tetrahedral (109.5°), V-shaped, Pyramidal."},
  {cat:"bonding", q:"What are the properties of Ionic Compounds?", a:"1. High melting/boiling points (strong ionic bonds)\n2. Conduct electricity when molten or dissolved (ions free to move)\n3. Do not conduct when solid (ions in fixed positions)\n4. Soluble in water\n5. Form crystalline structures"},

  // ===== STOICHIOMETRY =====
  {cat:"stoichiometry", q:"Define Relative Atomic Mass (Ar)", a:"The average mass of an atom of an element relative to 1/12 the mass of a carbon-12 atom. Accounts for isotopic abundances."},
  {cat:"stoichiometry", q:"Define the Mole", a:"The amount of substance that contains 6.022 × 10²³ particles (Avogadro's number). One mole of any element has a mass equal to its relative atomic mass in grams."},
  {cat:"stoichiometry", q:"How do you calculate the number of moles?", a:"n = mass / molar mass (for solids)\nn = C × V (for solutions, where C is in mol/L and V in litres)\nn = V / 22,400 (for gases at STP, where V is in cm³)\nn = PV / RT (ideal gas equation)"},
  {cat:"stoichiometry", q:"What is a Limiting Reagent?", a:"The reactant that is completely used up first in a reaction. It determines the maximum amount of product that can be formed. The other reactant(s) are in excess."},
  {cat:"stoichiometry", q:"How do you calculate Percentage Yield?", a:"% Yield = (Actual yield / Theoretical yield) × 100\nTheoretical yield is calculated from stoichiometry.\nActual yield is measured experimentally.\nAlways ≤ 100% (losses, side reactions, incomplete reaction)."},
  {cat:"stoichiometry", q:"What is a Standard Solution?", a:"A solution of accurately known concentration. Prepared by dissolving a precisely weighed amount of primary standard in a volumetric flask and making up to the mark with distilled water."},
  {cat:"stoichiometry", q:"Define Molarity", a:"The concentration of a solution expressed as the number of moles of solute per litre of solution.\nMolarity (M) = moles of solute / volume of solution (in litres)\nUnits: mol L⁻¹ or mol/dm³"},

  // ===== ORGANIC CHEMISTRY =====
  {cat:"organic", q:"What is a Homologous Series?", a:"A series of organic compounds with the same general formula, similar chemical properties, and each member differs by CH₂. Properties change gradually. Examples: alkanes (CₙH₂ₙ₊₂), alkenes (CₙH₂ₙ)."},
  {cat:"organic", q:"Name the first 4 Alkanes", a:"Methane (CH₄), Ethane (C₂H₆), Propane (C₃H₈), Butane (C₄H₁₀)\nGeneral formula: CₙH₂ₙ₊₂\nSaturated hydrocarbons (single bonds only)\nUndergo substitution reactions."},
  {cat:"organic", q:"Name the first 3 Alkenes", a:"Ethene (C₂H₄), Propene (C₃H₆), Butene (C₄H₈)\nGeneral formula: CₙH₂ₙ\nUnsaturated (contain C=C double bond)\nUndergo addition reactions.\nTest: decolourise bromine water."},
  {cat:"organic", q:"What is an Addition Reaction?", a:"A reaction where atoms are added across a double bond (C=C → C-C).\nExamples:\nC₂H₄ + Br₂ → C₂H₄Br₂ (addition of bromine)\nC₂H₄ + H₂ → C₂H₆ (hydrogenation)\nC₂H₄ + H₂O → C₂H₅OH (hydration)"},
  {cat:"organic", q:"What are the Functional Groups for: alcohol, carboxylic acid, ester, aldehyde, ketone?", a:"Alcohol: -OH\nCarboxylic acid: -COOH\nEster: -COO- (formed from acid + alcohol)\nAldehyde: -CHO (terminal)\nKetone: C=O (non-terminal)"},
  {cat:"organic", q:"Define Structural Isomers", a:"Molecules with the same molecular formula but different structural formulas (atoms arranged differently). Example: butane and methylpropane (both C₄H₁₀)."},
  {cat:"organic", q:"Describe the mechanism of Electrophilic Addition (ethene + Br₂)", a:"1. Br₂ approaches C=C double bond\n2. π electrons in C=C repel electron cloud of Br₂ → Br₂ becomes polarised (Brδ⁺—Brδ⁻)\n3. Brδ⁺ (electrophile) attacks C=C → carbocation intermediate formed\n4. Br⁻ attacks carbocation → 1,2-dibromoethane formed"},
  {cat:"organic", q:"What is Esterification?", a:"The reaction between a carboxylic acid and an alcohol to form an ester and water.\nAcid + Alcohol → Ester + Water\nCH₃COOH + C₂H₅OH → CH₃COOC₂H₅ + H₂O\nReversible reaction; acid catalyst (H₂SO₄) needed."},
  {cat:"organic", q:"What is a Polymer?", a:"A large molecule made of many repeating units (monomers) joined together.\nAddition polymer: from alkene monomers (e.g., polyethene from ethene)\nCondensation polymer: monomers join with loss of small molecule (e.g., nylon, polyester)"},
  {cat:"organic", q:"Name 3 tests to distinguish Organic Compounds", a:"1. Bromine water: decolourised by alkenes (unsaturated)\n2. Fehling's/Benedict's: brick-red precipitate with aldehydes\n3. Sodium carbonate: fizzing (CO₂) with carboxylic acids"},

  // ===== ACIDS & BASES =====
  {cat:"acids-bases", q:"Define an Acid (Brønsted-Lowry)", a:"A proton (H⁺) donor. Example: HCl → H⁺ + Cl⁻\nStrong acid: fully dissociates in water (HCl, H₂SO₄, HNO₃)\nWeak acid: partially dissociates (CH₃COOH, H₂CO₃)"},
  {cat:"acids-bases", q:"Define a Base (Brønsted-Lowry)", a:"A proton (H⁺) acceptor. Example: NH₃ + H⁺ → NH₄⁺\nAlkali: a base that dissolves in water to produce OH⁻ ions (e.g., NaOH)."},
  {cat:"acids-bases", q:"Define pH", a:"A measure of the hydrogen ion concentration in a solution.\npH = -log₁₀[H⁺]\npH 7 = neutral, pH < 7 = acidic, pH > 7 = basic/alkaline\nEach pH unit = 10× change in [H⁺]"},
  {cat:"acids-bases", q:"What is a Conjugate Acid-Base Pair?", a:"Two species that differ by one proton (H⁺).\nHCl + H₂O → H₃O⁺ + Cl⁻\nHCl/Cl⁻ is one conjugate pair\nH₂O/H₃O⁺ is the other conjugate pair"},
  {cat:"acids-bases", q:"What is a Buffer Solution?", a:"A solution that resists changes in pH when small amounts of acid or base are added.\nMade from: weak acid + its salt (conjugate base)\nExample: CH₃COOH + CH₃COONa\nAdded H⁺ reacts with CH₃COO⁻; added OH⁻ reacts with CH₃COOH."},
  {cat:"acids-bases", q:"Describe a Titration procedure", a:"1. Rinse burette with solution, fill and record initial reading\n2. Pipette known volume of other solution into conical flask\n3. Add indicator (e.g., phenolphthalein)\n4. Add solution from burette drop by drop until endpoint (colour change)\n5. Record final reading; calculate titre\n6. Repeat for concordant results (within 0.1 cm³)"},

  // ===== EQUILIBRIUM =====
  {cat:"equilibrium", q:"State Le Chatelier's Principle", a:"If a system in equilibrium is subjected to a change in concentration, temperature, or pressure, the system will shift to oppose the change and restore equilibrium."},
  {cat:"equilibrium", q:"What is the Equilibrium Constant (Kc)?", a:"For aA + bB ⇌ cC + dD:\nKc = [C]ᶜ[D]ᵈ / [A]ᵃ[B]ᵇ\nKc is constant at a given temperature.\nKc > 1: products favoured. Kc < 1: reactants favoured.\nOnly changes with temperature."},
  {cat:"equilibrium", q:"What effect does a catalyst have on equilibrium?", a:"A catalyst has NO effect on the position of equilibrium or on Kc. It speeds up both the forward and reverse reactions equally, so equilibrium is reached faster."},
  {cat:"equilibrium", q:"How does increasing pressure affect a gaseous equilibrium?", a:"Equilibrium shifts to the side with fewer moles of gas.\nExample: N₂ + 3H₂ ⇌ 2NH₃ (4 moles → 2 moles)\nIncreasing pressure shifts right → more NH₃ produced."},

  // ===== RATES OF REACTION =====
  {cat:"rates", q:"Define Rate of Reaction", a:"The change in concentration of a reactant or product per unit time.\nRate = Δ[concentration] / Δtime\nUnits: mol L⁻¹ s⁻¹ (or mol dm⁻³ s⁻¹)"},
  {cat:"rates", q:"Name 5 factors that affect the Rate of Reaction", a:"1. Concentration (higher → faster)\n2. Temperature (higher → faster)\n3. Surface area (greater → faster)\n4. Catalyst (lowers activation energy)\n5. Nature of reactants"},
  {cat:"rates", q:"Define Activation Energy (Ea)", a:"The minimum amount of energy that colliding particles must have for a successful reaction to occur. A catalyst provides an alternative pathway with a lower activation energy."},
  {cat:"rates", q:"What is Collision Theory?", a:"For a reaction to occur, particles must:\n1. Collide with each other\n2. Have sufficient energy (≥ activation energy)\n3. Collide with correct orientation\nIncreasing temperature increases the frequency and energy of collisions."},
  {cat:"rates", q:"Define a Catalyst", a:"A substance that increases the rate of a reaction without being consumed. It provides an alternative reaction pathway with lower activation energy. Homogeneous: same phase. Heterogeneous: different phase."},

  // ===== THERMOCHEMISTRY =====
  {cat:"thermochemistry", q:"Define Exothermic Reaction", a:"A reaction that releases heat energy to the surroundings. ΔH is negative.\nTemperature of surroundings increases.\nExamples: combustion, neutralisation, respiration."},
  {cat:"thermochemistry", q:"Define Endothermic Reaction", a:"A reaction that absorbs heat energy from the surroundings. ΔH is positive.\nTemperature of surroundings decreases.\nExamples: photosynthesis, thermal decomposition, dissolving NH₄NO₃."},
  {cat:"thermochemistry", q:"State Hess's Law", a:"The enthalpy change for a reaction is the same regardless of the route taken (provided initial and final conditions are the same). Allows calculation of ΔH for reactions that cannot be measured directly."},
  {cat:"thermochemistry", q:"How do you calculate heat energy in a calorimetry experiment?", a:"q = mcΔT\nq = heat energy (J)\nm = mass of water (g)\nc = specific heat capacity of water (4.18 J g⁻¹ °C⁻¹)\nΔT = temperature change (°C)"},
  {cat:"thermochemistry", q:"Define Bond Energy", a:"The energy required to break one mole of a particular bond in the gaseous state.\nΔH = Σ(bonds broken) - Σ(bonds formed)\nIf energy to break bonds > energy released forming bonds → endothermic (and vice versa)."},
  {cat:"thermochemistry", q:"Define Standard Enthalpy of Formation (ΔHf°)", a:"The enthalpy change when one mole of a compound is formed from its elements in their standard states at 25°C and 1 atm. ΔHf° of any element in its standard state = 0."},

  // ===== ELECTROCHEMISTRY =====
  {cat:"electrochemistry", q:"Define Oxidation and Reduction (OIL RIG)", a:"Oxidation Is Loss of electrons (increase in oxidation number)\nReduction Is Gain of electrons (decrease in oxidation number)\nThey always occur together (redox reaction).\nOxidising agent: gains electrons (is reduced)\nReducing agent: loses electrons (is oxidised)"},
  {cat:"electrochemistry", q:"What is an Electrochemical Cell?", a:"A device that converts chemical energy to electrical energy (voltaic/galvanic cell) or electrical energy to chemical energy (electrolytic cell).\nVoltaic: spontaneous reaction produces current\nElectrolytic: external current drives non-spontaneous reaction"},
  {cat:"electrochemistry", q:"Define Electrolysis", a:"The decomposition of an ionic compound (electrolyte) by passing an electric current through it (when molten or in solution).\nCations → cathode (gain electrons, reduction)\nAnions → anode (lose electrons, oxidation)"},
  {cat:"electrochemistry", q:"Write the equation for the electrolysis of water", a:"2H₂O → 2H₂ + O₂\nAt cathode: 4H⁺ + 4e⁻ → 2H₂ (reduction)\nAt anode: 2H₂O → O₂ + 4H⁺ + 4e⁻ (oxidation)\nRatio: H₂ : O₂ = 2 : 1"},
  {cat:"electrochemistry", q:"What is the Reactivity Series?", a:"A ranking of metals in order of their reactivity (tendency to lose electrons).\nK > Na > Ca > Mg > Al > Zn > Fe > Pb > H > Cu > Ag > Au\nMore reactive metals are stronger reducing agents.\nMore reactive metals displace less reactive metals from solution."},
  {cat:"electrochemistry", q:"Define Oxidation Number", a:"The charge an atom would have if all bonds were ionic. Rules:\nFree element = 0, H = +1 (except metal hydrides -1), O = -2 (except peroxides -1), sum = charge on ion.\nUseful for identifying redox reactions."},

  // ===== EXPERIMENTS =====
  {cat:"experiments", q:"Describe the experiment to prepare a standard solution of sodium carbonate", a:"1. Calculate mass needed (using n = mass/Mr and C = n/V)\n2. Weigh accurately on electronic balance\n3. Dissolve in some distilled water in a beaker\n4. Transfer to volumetric flask (rinse beaker several times)\n5. Make up to the mark with distilled water\n6. Stopper and invert to mix"},
  {cat:"experiments", q:"Describe the experiment to determine heat of reaction by calorimetry", a:"1. Measure a known volume of solution into a polystyrene cup (calorimeter)\n2. Record initial temperature\n3. Add second reactant, stir with thermometer\n4. Record highest/lowest temperature reached\n5. Calculate: q = mcΔT\n6. Calculate ΔH per mole"},
  {cat:"experiments", q:"Describe the experiment to measure the rate of reaction (CaCO₃ + HCl)", a:"1. Place marble chips in flask on balance\n2. Add HCl and start timer\n3. Record mass loss at regular intervals (CO₂ escapes)\n4. Plot mass loss vs time graph\n5. Steepest part = fastest rate\n6. Variables: concentration of acid, size of marble chips, temperature"},
  {cat:"experiments", q:"How do you test for the following gases: O₂, CO₂, H₂?", a:"O₂: relights a glowing splint\nCO₂: turns limewater milky (Ca(OH)₂ + CO₂ → CaCO₃ + H₂O)\nH₂: burns with a 'pop' when a lit splint is placed near it"},
  {cat:"experiments", q:"Describe the Flame Test for metal ions", a:"1. Clean nichrome wire with HCl\n2. Dip in sample\n3. Hold in Bunsen flame\nColours: Li⁺ red, Na⁺ yellow, K⁺ lilac, Ca²⁺ brick-red, Cu²⁺ blue-green, Ba²⁺ green"},

  // ===== ADDITIONAL KEY CONCEPTS =====
  {cat:"atomic-structure", q:"What are the Periodic Trends across a Period?", a:"Left to right across a period:\n• Atomic radius decreases\n• Ionisation energy increases\n• Electronegativity increases\n• Metallic character decreases\n• Elements go from metals → metalloids → non-metals"},
  {cat:"atomic-structure", q:"Define First Ionisation Energy", a:"The minimum energy required to remove the most loosely bound electron from a neutral gaseous atom.\nM(g) → M⁺(g) + e⁻\nIncreases across a period (greater nuclear charge), decreases down a group (greater distance from nucleus)."},
  {cat:"bonding", q:"Define Metallic Bonding", a:"The electrostatic attraction between a lattice of positive metal ions and a 'sea' of delocalised electrons. Explains properties: conductivity (electrons move freely), malleability, ductility, high melting points."},
  {cat:"stoichiometry", q:"State Avogadro's Law", a:"Equal volumes of all gases at the same temperature and pressure contain the same number of molecules.\nAt STP: 1 mole of any gas occupies 22.4 L (22,400 cm³)."},
  {cat:"organic", q:"What is Fractional Distillation?", a:"The separation of crude oil into fractions based on different boiling points.\nSmaller molecules: lower boiling points, more volatile, less viscous (e.g., petrol/gasoline).\nLarger molecules: higher boiling points (e.g., bitumen)."},
  {cat:"organic", q:"Describe Free Radical Substitution (methane + chlorine)", a:"Initiation: Cl₂ → 2Cl• (UV light breaks Cl-Cl bond, homolytic fission)\nPropagation: Cl• + CH₄ → CH₃• + HCl then CH₃• + Cl₂ → CH₃Cl + Cl•\nTermination: two radicals combine (Cl• + Cl• → Cl₂, CH₃• + Cl• → CH₃Cl, etc.)"},
  {cat:"acids-bases", q:"What is the Kw expression?", a:"Kw = [H⁺][OH⁻] = 1.0 × 10⁻¹⁴ mol² L⁻² at 25°C\nIn pure water: [H⁺] = [OH⁻] = 1.0 × 10⁻⁷ mol/L → pH = 7\nKw is the ionic product of water."},
  {cat:"rates", q:"Define Order of Reaction", a:"The power to which the concentration of a reactant is raised in the rate equation.\nRate = k[A]ᵐ[B]ⁿ\nm = order w.r.t. A, n = order w.r.t. B\nOverall order = m + n\nDetermined experimentally."},
  {cat:"electrochemistry", q:"What is Rusting and how can it be prevented?", a:"Rusting: iron reacts with oxygen and water → hydrated iron(III) oxide (Fe₂O₃·xH₂O).\nPrevention: painting, oiling, galvanising (zinc coating), sacrificial protection (more reactive metal), alloying (stainless steel), electroplating."},
  {cat:"thermochemistry", q:"What is the Born-Haber Cycle?", a:"An application of Hess's Law used to calculate lattice energy of ionic compounds. Steps: atomisation of metal, ionisation of metal, atomisation of non-metal, electron affinity, lattice energy. The sum of all enthalpy changes equals ΔHf°."},
  {cat:"organic", q:"What is Saponification?", a:"The hydrolysis of a fat or oil using a strong alkali (NaOH or KOH) to produce soap (sodium/potassium salt of a fatty acid) and glycerol.\nFat + NaOH → Soap + Glycerol\nThis is the reverse of esterification."},
  {cat:"acids-bases", q:"Define a Primary Standard", a:"A substance used to prepare a standard solution that must be:\n1. High purity\n2. Known, stable formula\n3. Stable in air (not hygroscopic)\n4. High molar mass (reduces weighing error)\n5. Soluble in water\nExamples: Na₂CO₃, (COOH)₂·2H₂O"},
  {cat:"experiments", q:"Describe the experiment to measure the Percentage Ethanoic Acid in Vinegar", a:"1. Prepare a standard NaOH solution\n2. Pipette 25 cm³ of diluted vinegar into conical flask\n3. Add phenolphthalein indicator\n4. Titrate with NaOH until pink colour persists\n5. Calculate moles NaOH, then moles CH₃COOH (1:1 ratio)\n6. Calculate concentration and percentage"},
  {cat:"organic", q:"What is Cracking?", a:"Breaking down large, less useful hydrocarbon molecules into smaller, more useful ones.\nThermal cracking: high temperature and pressure → alkanes + alkenes\nCatalytic cracking: lower temperature + catalyst (zeolite)\nImportant for producing petrol and alkenes for plastics."},
  {cat:"bonding", q:"What is a Dative (Coordinate) Covalent Bond?", a:"A covalent bond where both electrons in the shared pair come from one atom (the donor). The other atom (acceptor) has an empty orbital.\nExample: NH₄⁺ (ammonia donates lone pair to H⁺)\nAlso: H₃O⁺, CO, Al₂Cl₆"},
  {cat:"atomic-structure", q:"Explain Emission Line Spectra", a:"When excited electrons return to lower energy levels, they emit photons of specific wavelengths (colours).\nEach element has a unique emission spectrum — used for identification.\nLines correspond to specific energy transitions.\nE = hf (Planck's equation)"},
  {cat:"equilibrium", q:"What is Kw and how does it change with temperature?", a:"Kw = [H⁺][OH⁻] = 1.0 × 10⁻¹⁴ at 25°C\nDissociation of water is endothermic.\nIncreasing temperature → Kw increases → [H⁺] increases → pH decreases.\nWater is still neutral (equal [H⁺] and [OH⁻]) but pH is less than 7."},
  {cat:"stoichiometry", q:"How do you balance a Redox equation using half-equations?", a:"1. Write separate oxidation and reduction half-equations\n2. Balance atoms (other than O and H)\n3. Balance O using H₂O, then H using H⁺\n4. Balance charges using electrons\n5. Multiply half-equations so electrons cancel\n6. Add together and simplify"},
  {cat:"organic", q:"Name the tests to distinguish between an Aldehyde and a Ketone", a:"Aldehydes are easily oxidised; ketones are not.\n1. Fehling's solution: aldehyde gives brick-red precipitate (Cu₂O). Ketone: no reaction.\n2. Tollens' reagent (silver mirror test): aldehyde gives silver mirror. Ketone: no reaction.\nAldehydes are reducing agents."},
  {cat:"experiments", q:"Describe the experiment to determine the concentration of a NaOH solution by titration with HCl", a:"1. Prepare standard HCl solution (or vice versa)\n2. Pipette 25.0 cm³ of NaOH into conical flask\n3. Add methyl orange or phenolphthalein indicator\n4. Fill burette with HCl, record initial reading\n5. Titrate until endpoint (colour change)\n6. Record final reading, calculate titre\n7. Use C₁V₁/n₁ = C₂V₂/n₂ to find concentration"},
  {cat:"organic", q:"What is an Alcohol? Name the 3 classes.", a:"An organic compound containing the -OH functional group.\nPrimary (1°): OH on carbon bonded to 1 other carbon (e.g., ethanol)\nSecondary (2°): OH on carbon bonded to 2 other carbons (e.g., propan-2-ol)\nTertiary (3°): OH on carbon bonded to 3 other carbons\n1° can be oxidised to aldehyde then acid; 2° to ketone; 3° resists oxidation."},
  {cat:"acids-bases", q:"Define a Strong Acid vs a Weak Acid", a:"Strong acid: fully dissociates in water — all molecules ionise. Examples: HCl, H₂SO₄, HNO₃. Low pH.\nWeak acid: partially dissociates — equilibrium between molecules and ions. Example: CH₃COOH (Ka is small). Higher pH than strong acid of same concentration."},
  {cat:"electrochemistry", q:"What is a Fuel Cell?", a:"An electrochemical cell that converts chemical energy of a fuel (usually H₂) directly into electrical energy.\n2H₂ + O₂ → 2H₂O + electrical energy\nAdvantages: efficient, clean (water is only product), no moving parts.\nUsed in space missions and electric vehicles."}
];
