var FLASHCARDS_SPANISH = [
  // ===== GRAMMAR - TENSES =====
  {cat:"grammar-tenses", q:"How do you form the Present Tense of regular -AR verbs?", a:"Remove -ar, add endings:\nyo: -o\ntú: -as\nél/ella: -a\nnosotros: -amos\nvosotros: -áis\nellos/ellas: -an\nExample: hablar → hablo, hablas, habla, hablamos, habláis, hablan"},
  {cat:"grammar-tenses", q:"How do you form the Present Tense of regular -ER verbs?", a:"Remove -er, add endings:\nyo: -o\ntú: -es\nél/ella: -e\nnosotros: -emos\nvosotros: -éis\nellos/ellas: -en\nExample: comer → como, comes, come, comemos, coméis, comen"},
  {cat:"grammar-tenses", q:"How do you form the Present Tense of regular -IR verbs?", a:"Remove -ir, add endings:\nyo: -o\ntú: -es\nél/ella: -e\nnosotros: -imos\nvosotros: -ís\nellos/ellas: -en\nExample: vivir → vivo, vives, vive, vivimos, vivís, viven"},
  {cat:"grammar-tenses", q:"How do you form the Preterite (Past) Tense of -AR verbs?", a:"Remove -ar, add endings:\nyo: -é\ntú: -aste\nél/ella: -ó\nnosotros: -amos\nvosotros: -asteis\nellos/ellas: -aron\nExample: hablar → hablé, hablaste, habló, hablamos, hablasteis, hablaron"},
  {cat:"grammar-tenses", q:"How do you form the Preterite Tense of -ER/-IR verbs?", a:"Remove -er/-ir, add endings:\nyo: -í\ntú: -iste\nél/ella: -ió\nnosotros: -imos\nvosotros: -isteis\nellos/ellas: -ieron\nExample: comer → comí, comiste, comió, comimos, comisteis, comieron"},
  {cat:"grammar-tenses", q:"How do you form the Imperfect Tense of -AR verbs?", a:"Remove -ar, add endings:\nyo: -aba\ntú: -abas\nél/ella: -aba\nnosotros: -ábamos\nvosotros: -abais\nellos: -aban\nUsed for: descriptions, habitual actions in the past, background actions."},
  {cat:"grammar-tenses", q:"How do you form the Imperfect Tense of -ER/-IR verbs?", a:"Remove -er/-ir, add endings:\nyo: -ía\ntú: -ías\nél/ella: -ía\nnosotros: -íamos\nvosotros: -íais\nellos: -ían\nOnly 3 irregulars: ser (era), ir (iba), ver (veía)"},
  {cat:"grammar-tenses", q:"When do you use Preterite vs Imperfect?", a:"Preterite: completed actions, specific time, sequence of events.\n'Ayer fui al cine' (I went to the cinema yesterday)\n\nImperfect: ongoing/habitual past actions, descriptions, time/age/weather.\n'Cuando era joven, jugaba al fútbol' (When I was young, I used to play football)"},
  {cat:"grammar-tenses", q:"How do you form the Future Tense?", a:"Add endings to the FULL infinitive:\nyo: -é\ntú: -ás\nél/ella: -á\nnosotros: -emos\nvosotros: -éis\nellos: -án\nExample: hablar → hablaré, hablarás, hablará...\nIrregular stems: tener→tendr, hacer→har, poder→podr, salir→saldr"},
  {cat:"grammar-tenses", q:"How do you form the Conditional Tense?", a:"Add endings to the FULL infinitive (same stem as future):\nyo: -ía\ntú: -ías\nél/ella: -ía\nnosotros: -íamos\nvosotros: -íais\nellos: -ían\nUsed for: would, could, should. 'Me gustaría...' (I would like...)"},
  {cat:"grammar-tenses", q:"How do you form the Perfect Tense?", a:"haber (present) + past participle\nhe, has, ha, hemos, habéis, han + past participle\nPast participle: -ar → -ado, -er/-ir → -ido\nIrregulars: hecho (hacer), dicho (decir), escrito (escribir), visto (ver), puesto (poner), roto (romper), abierto (abrir), vuelto (volver)"},
  {cat:"grammar-tenses", q:"How do you form the Present Continuous?", a:"estar (present) + gerund (-ando/-iendo)\nestoy, estás, está, estamos, estáis, están + gerund\n-ar → -ando (hablando)\n-er/-ir → -iendo (comiendo, viviendo)\nUsed for: actions happening RIGHT NOW. 'Estoy estudiando' (I am studying)"},

  // ===== GRAMMAR - IRREGULAR VERBS =====
  {cat:"grammar-irregular", q:"Conjugate SER (to be — permanent) in the Present", a:"soy, eres, es, somos, sois, son\nUsed for: identity, nationality, profession, time, characteristics, origin.\n'Soy irlandés' (I am Irish)\n'Son las tres' (It is three o'clock)"},
  {cat:"grammar-irregular", q:"Conjugate ESTAR (to be — temporary) in the Present", a:"estoy, estás, está, estamos, estáis, están\nUsed for: location, temporary states, feelings, health.\n'Estoy cansado' (I am tired)\n'El libro está en la mesa' (The book is on the table)"},
  {cat:"grammar-irregular", q:"When do you use SER vs ESTAR?", a:"SER: permanent traits, identity, nationality, profession, time, dates, material, origin.\nESTAR: location, temporary feelings/states, health, progressive tense.\nSome adjectives change meaning:\nser aburrido = boring, estar aburrido = bored\nser listo = clever, estar listo = ready"},
  {cat:"grammar-irregular", q:"Conjugate IR (to go) in the Present", a:"voy, vas, va, vamos, vais, van\nPreterite: fui, fuiste, fue, fuimos, fuisteis, fueron (same as ser!)\nIr + a + infinitive = near future: 'Voy a estudiar' (I am going to study)"},
  {cat:"grammar-irregular", q:"Conjugate TENER (to have) in the Present", a:"tengo, tienes, tiene, tenemos, tenéis, tienen\nPreterite: tuve, tuviste, tuvo, tuvimos, tuvisteis, tuvieron\nExpressions: tener hambre (be hungry), tener sed (be thirsty), tener frío/calor (be cold/hot), tener __años (be __years old), tener que + inf (have to)"},
  {cat:"grammar-irregular", q:"Conjugate HACER (to do/make) in the Present", a:"hago, haces, hace, hacemos, hacéis, hacen\nPreterite: hice, hiciste, hizo, hicimos, hicisteis, hicieron\nUsed in weather: hace sol (it's sunny), hace frío (it's cold), hace calor (it's hot), hace viento (it's windy)"},
  {cat:"grammar-irregular", q:"Conjugate PODER (to be able to/can) in the Present", a:"puedo, puedes, puede, podemos, podéis, pueden\nPreterite: pude, pudiste, pudo, pudimos, pudisteis, pudieron\nStem-changing: o → ue\n'¿Puedo ir al baño?' (Can I go to the bathroom?)"},
  {cat:"grammar-irregular", q:"Conjugate QUERER (to want) in the Present", a:"quiero, quieres, quiere, queremos, queréis, quieren\nPreterite: quise, quisiste, quiso, quisimos, quisisteis, quisieron\nStem-changing: e → ie\n'Quiero ser médico' (I want to be a doctor)"},
  {cat:"grammar-irregular", q:"Name 6 common stem-changing verbs and their changes", a:"e → ie: pensar (to think), cerrar (to close), empezar (to begin)\ne → i: pedir (to ask for), servir (to serve), repetir (to repeat)\no → ue: poder (can), dormir (to sleep), volver (to return)\nStem changes do NOT occur in nosotros/vosotros forms."},
  {cat:"grammar-irregular", q:"What are Reflexive Verbs? Give 5 examples.", a:"Verbs where the subject performs the action on themselves. Use reflexive pronouns: me, te, se, nos, os, se.\n1. levantarse (get up)\n2. ducharse (shower)\n3. acostarse (go to bed)\n4. vestirse (get dressed)\n5. llamarse (be called)\n'Me levanto a las siete' (I get up at seven)"},

  // ===== SUBJUNCTIVE =====
  {cat:"subjunctive", q:"When do you use the Subjunctive?", a:"After verbs/expressions of:\n1. Wishing/wanting: quiero que, espero que\n2. Emotion: me alegra que, es triste que\n3. Doubt/uncertainty: dudo que, no creo que\n4. Commands/advice: es necesario que, es importante que\n5. Purpose: para que\n6. After 'cuando' referring to the future"},
  {cat:"subjunctive", q:"How do you form the Present Subjunctive?", a:"Take the yo form of the present, remove -o, add opposite endings:\n-AR verbs: -e, -es, -e, -emos, -éis, -en\n-ER/-IR verbs: -a, -as, -a, -amos, -áis, -an\nhablar: hable, hables, hable...\ncomer: coma, comas, coma...\nIrregulars: sea (ser), vaya (ir), haya (haber), sepa (saber), dé (dar)"},
  {cat:"subjunctive", q:"Give 5 example sentences using the Subjunctive", a:"1. Quiero que vengas a mi fiesta (I want you to come to my party)\n2. Es importante que estudies (It's important that you study)\n3. Espero que haga buen tiempo (I hope the weather is good)\n4. No creo que sea verdad (I don't think it's true)\n5. Cuando tenga 18 años, iré a la universidad (When I'm 18, I'll go to uni)"},

  // ===== VOCABULARY =====
  {cat:"vocabulary", q:"Family vocabulary (10 key words)", a:"padre/madre (father/mother)\nhermano/hermana (brother/sister)\nabuelo/abuela (grandfather/grandmother)\ntío/tía (uncle/aunt)\nprimo/prima (cousin)\nhijo/hija (son/daughter)\nmarido/esposo (husband)\nmujer/esposa (wife)\nnovio/novia (boyfriend/girlfriend)\nfamilia numerosa (large family)"},
  {cat:"vocabulary", q:"School vocabulary (10 key words)", a:"el instituto (secondary school)\nla asignatura (subject)\nel horario (timetable)\nel recreo (break/recess)\nlos deberes (homework)\nel examen (exam)\naprobar (to pass)\nsuspendar (to fail)\nel bachillerato (Leaving Cert equivalent)\nel profesorado (teaching staff)"},
  {cat:"vocabulary", q:"Health vocabulary (10 key words)", a:"la salud (health)\nsano/a (healthy)\nenfermo/a (sick/ill)\nel médico (doctor)\nel hospital (hospital)\nme duele la cabeza (I have a headache)\ntener fiebre (to have a fever)\nla dieta equilibrada (balanced diet)\nhacer ejercicio (to exercise)\nel estrés (stress)"},
  {cat:"vocabulary", q:"Technology vocabulary (10 key words)", a:"el móvil/smartphone (mobile phone)\nlas redes sociales (social media)\nnavegar por internet (to browse the internet)\ndescargar (to download)\nla pantalla (screen)\nel ordenador/portátil (computer/laptop)\nla aplicación/app (app)\nel ciberacoso (cyberbullying)\nen línea (online)\ncompartir (to share)"},
  {cat:"vocabulary", q:"Environment vocabulary (10 key words)", a:"el medio ambiente (environment)\nla contaminación (pollution)\nel cambio climático (climate change)\nreciclar (to recycle)\nlas energías renovables (renewable energy)\nel efecto invernadero (greenhouse effect)\nel calentamiento global (global warming)\nproteger (to protect)\nlos residuos (waste)\nahorrar energía (to save energy)"},
  {cat:"vocabulary", q:"Travel & holidays vocabulary (10 key words)", a:"viajar (to travel)\nel vuelo (flight)\nel alojamiento (accommodation)\nel hotel/hostal (hotel/hostel)\nla playa (beach)\nhacer turismo (to do sightseeing)\nel equipaje (luggage)\nel billete (ticket)\nel pasaporte (passport)\nel destino (destination)"},
  {cat:"vocabulary", q:"Personality adjectives (10 key words)", a:"simpático/a (nice/friendly)\nantipático/a (unfriendly)\ntímido/a (shy)\nextrovertido/a (outgoing)\ntrabajador/a (hardworking)\nperezoso/a (lazy)\namable (kind)\negoísta (selfish)\ngracioso/a (funny)\nterco/a (stubborn)"},
  {cat:"vocabulary", q:"Time expressions for Past Tense", a:"ayer (yesterday)\nanteayer (the day before yesterday)\nla semana pasada (last week)\nel mes/año pasado (last month/year)\nhace dos días (two days ago)\nel otro día (the other day)\nen aquel entonces (back then)\ncuando era joven (when I was young)\nsiempre (always — with imperfect for habitual)\ntodos los días (every day — imperfect)"},
  {cat:"vocabulary", q:"Time expressions for Future Tense", a:"mañana (tomorrow)\npasado mañana (the day after tomorrow)\nla semana que viene (next week)\nel mes/año que viene (next month/year)\nen el futuro (in the future)\ndentro de cinco años (in five years' time)\ncuando sea mayor (when I'm older)\nalgún día (someday)\npronto (soon)"},

  // ===== EXAM PHRASES =====
  {cat:"exam-phrases", q:"Opinion phrases (10 key expressions)", a:"En mi opinión... (In my opinion...)\nCreo que... (I think that...)\nPienso que... (I think that...)\nMe parece que... (It seems to me that...)\nEstoy de acuerdo (I agree)\nNo estoy de acuerdo (I disagree)\nDesde mi punto de vista (From my point of view)\nPor un lado... por otro lado (On one hand... on the other)\nEs verdad que... (It's true that...)\nNo cabe duda de que... (There's no doubt that...)"},
  {cat:"exam-phrases", q:"Linking words and connectors", a:"además (furthermore/also)\nsin embargo (however)\nno obstante (nevertheless)\npor lo tanto (therefore)\nen primer lugar (firstly)\nen segundo lugar (secondly)\npor ejemplo (for example)\nen conclusión (in conclusion)\nes decir (that is to say)\nen cambio (on the other hand)\naunque (although)\nya que / puesto que / dado que (since/because)"},
  {cat:"exam-phrases", q:"Useful phrases for the Written Production (essay)", a:"Hoy en día... (Nowadays...)\nEn la sociedad actual... (In today's society...)\nUno de los problemas más graves es... (One of the most serious problems is...)\nEs necesario que + subjunctive (It is necessary that...)\nPara concluir / en resumen (To conclude / in summary)\nSin lugar a dudas (Without a doubt)\nHay que tener en cuenta que (One must bear in mind that)"},
  {cat:"exam-phrases", q:"Phrases for agreeing and disagreeing", a:"Agreeing:\nEstoy totalmente de acuerdo (I totally agree)\nTienes toda la razón (You're completely right)\nComparto tu opinión (I share your opinion)\n\nDisagreeing:\nNo estoy de acuerdo en absoluto (I don't agree at all)\nNo comparto esa opinión (I don't share that opinion)\nMe temo que no es así (I'm afraid that's not the case)"},
  {cat:"exam-phrases", q:"Phrases for expressing feelings", a:"Me encanta / me fascina (I love / I'm fascinated by)\nMe preocupa que (I'm worried that)\nMe molesta que (It annoys me that)\nMe alegra que (I'm glad that)\nEstoy harto/a de (I'm fed up with)\nMe da igual (I don't care / it's all the same to me)\nMe sorprende que (I'm surprised that)\nTengo miedo de (I'm afraid of)"},
  {cat:"exam-phrases", q:"How to start and end a formal letter in Spanish", a:"Start: Estimado/a señor/a (Dear Sir/Madam)\nMuy señor/a mío/a (Dear Sir/Madam — very formal)\nLe escribo para... (I am writing to you to...)\n\nEnd: Le saluda atentamente (Yours faithfully)\nAtentamente (Sincerely)\nQuedo a su disposición (I remain at your disposal)\nEn espera de su respuesta (Awaiting your reply)"},
  {cat:"exam-phrases", q:"How to start and end an informal letter/email", a:"Start: Querido/a (Dear — informal)\n¡Hola! ¿Qué tal? (Hi! How are you?)\nGracias por tu carta/email (Thanks for your letter/email)\n\nEnd: Un abrazo (A hug)\nBesos (Kisses)\nHasta pronto (See you soon)\nCuídate (Take care)\nEscríbeme pronto (Write to me soon)"},

  // ===== READING TIPS =====
  {cat:"reading-tips", q:"Top 5 strategies for the Reading Comprehension", a:"1. Read questions FIRST to know what to look for\n2. Underline key words in questions\n3. Scan text for those key words / synonyms\n4. Don't panic over unknown words — use context clues\n5. Answer in your own words where possible (avoid copying irrelevant text)"},
  {cat:"reading-tips", q:"Common false friends (falsos amigos) in Spanish", a:"actual = current (NOT actual)\neventualmente = possibly (NOT eventually)\nsensible = sensitive (NOT sensible)\néxito = success (NOT exit)\nrealizar = to carry out (NOT to realise)\nembarazada = pregnant (NOT embarrassed)\nassistir = to attend (NOT to assist)\nconstipado = having a cold (NOT constipated)"},
  {cat:"reading-tips", q:"How to work out meaning of unknown words in reading", a:"1. Look for cognates (words similar to English/French)\n2. Look at the root/stem of the word\n3. Check prefix/suffix: des- (un-), -mente (= -ly), -ción (= -tion)\n4. Read the sentence around it for context\n5. Is it a verb? What tense? Who is doing the action?"},

  // ===== LISTENING TIPS =====
  {cat:"listening-tips", q:"Top 5 strategies for the Listening exam", a:"1. Read questions carefully during reading time — predict answers\n2. Listen for key words, not every word\n3. Numbers, dates, times are often asked — practice hearing these\n4. Don't get stuck — if you miss one, move on\n5. Use the second listening to check and fill gaps"},
  {cat:"listening-tips", q:"Key number vocabulary for the Listening exam", a:"100 = cien, 200 = doscientos, 500 = quinientos\n1,000 = mil, 1,000,000 = un millón\nDays: lunes, martes, miércoles, jueves, viernes, sábado, domingo\nMonths: enero, febrero, marzo, abril, mayo, junio, julio, agosto, septiembre, octubre, noviembre, diciembre"},
  {cat:"listening-tips", q:"How to give the time in Spanish", a:"Es la una (It's 1 o'clock) — singular for 1\nSon las dos/tres/cuatro (It's 2/3/4 o'clock)\ny cuarto (quarter past), y media (half past)\nmenos cuarto (quarter to)\ny cinco/diez/veinte (five/ten/twenty past)\nen punto (exactly/on the dot)"},

  // ===== WRITING TIPS =====
  {cat:"writing-tips", q:"5 tips for scoring high marks in Written Production", a:"1. Plan your essay — intro, 2-3 body paragraphs, conclusion\n2. Use a variety of tenses (present, past, future, conditional)\n3. Include subjunctive to show higher-level grammar\n4. Use connectors and linking words throughout\n5. Give opinions with reasons — En mi opinión... porque..."},
  {cat:"writing-tips", q:"Common mistakes to avoid in the writing exam", a:"1. Adjective agreement: 'una chica simpática' not 'simpático'\n2. Ser vs estar confusion\n3. Forgetting accent marks on preterite: hablé, habló\n4. Using English word order: 'the red car' = 'el coche rojo' (adj after noun)\n5. Mixing up por and para\n6. Not conjugating verbs (writing infinitive instead)"},
  {cat:"writing-tips", q:"When do you use POR vs PARA?", a:"POR: because of, in exchange for, through, duration, per.\n'Gracias por tu ayuda' (Thanks for your help)\n'Estudié por dos horas' (I studied for two hours)\n\nPARA: purpose, destination, deadline, recipient, opinion.\n'Estudio para aprobar' (I study to pass)\n'Este regalo es para ti' (This gift is for you)"},

  // ===== ADDITIONAL KEY GRAMMAR =====
  {cat:"grammar-tenses", q:"What is the Pluperfect Tense?", a:"Had + past participle. Formed with Imperfect of haber + past participle.\nhabía, habías, había, habíamos, habíais, habían + past participle\n'Ya había comido cuando llegaste' (I had already eaten when you arrived)"},
  {cat:"grammar-tenses", q:"What is the Passive Voice in Spanish?", a:"ser + past participle (agrees with subject)\n'El libro fue escrito por Cervantes' (The book was written by Cervantes)\nOften avoided in Spanish — prefer active or 'se' construction:\n'Se habla español aquí' (Spanish is spoken here)"},
  {cat:"grammar-irregular", q:"What are Direct and Indirect Object Pronouns?", a:"Direct: me, te, lo/la, nos, os, los/las\n'Lo compré' (I bought it)\nIndirect: me, te, le, nos, os, les\n'Le di el libro' (I gave him/her the book)\nPosition: before conjugated verb or attached to infinitive/gerund.\nDouble pronouns: le/les → se before lo/la/los/las"},
  {cat:"grammar-irregular", q:"How does the verb GUSTAR work?", a:"Literally 'to please' — works backwards from English.\nMe gusta el chocolate (I like chocolate — chocolate pleases me)\nMe gustan los perros (I like dogs — dogs please me)\nNos gusta bailar (We like dancing)\nPronoun + gusta + singular noun/infinitive\nPronoun + gustan + plural noun\nSimilar verbs: encantar, interesar, molestar, importar"},
  {cat:"grammar-tenses", q:"What are the Imperative (command) forms?", a:"Tú (informal affirmative): use 3rd person singular present\nhabla, come, escribe\nIrregulars: ven (venir), pon (poner), sal (salir), haz (hacer), di (decir), ten (tener), sé (ser)\nNegative tú: no + present subjunctive: no hables, no comas\nUsted: present subjunctive: hable, coma, escriba"},
  {cat:"vocabulary", q:"Key phrases for discussing current issues / Diary Entry topics", a:"la inmigración (immigration)\nel paro/desempleo (unemployment)\nla igualdad de género (gender equality)\nel acoso escolar (bullying)\nla presión de los exámenes (exam pressure)\nlos jóvenes de hoy (young people today)\nla influencia de las redes sociales (the influence of social media)\nel consumismo (consumerism)\nla vida sana (healthy living)"},
  {cat:"exam-phrases", q:"Phrases for comparing and contrasting", a:"más... que (more... than)\nmenos... que (less... than)\ntan... como (as... as)\ntanto como (as much as)\nen comparación con (in comparison with)\na diferencia de (unlike)\nal igual que (just like)\nmientras que (while/whereas)\npor el contrario (on the contrary)"},
  {cat:"vocabulary", q:"Sports and leisure vocabulary (10 key words)", a:"el deporte (sport)\njugar al fútbol (to play football)\nel equipo (team)\nel partido (match)\nel entrenamiento (training)\nla natación (swimming)\nel atletismo (athletics)\nmontar en bicicleta (to cycle)\nel ocio (leisure)\nir de paseo (to go for a walk)"},
  {cat:"vocabulary", q:"Food and drink vocabulary (10 key words)", a:"el desayuno (breakfast)\nel almuerzo (lunch)\nla cena (dinner)\nla carne (meat)\nel pescado (fish)\nlas verduras (vegetables)\nla fruta (fruit)\nel postre (dessert)\nprobar (to try/taste)\ntener hambre/sed (to be hungry/thirsty)"},
  {cat:"vocabulary", q:"Work and career vocabulary (10 key words)", a:"el trabajo (work/job)\nel empleo (employment)\nel sueldo/salario (salary)\nsolicitar (to apply for)\nla entrevista (interview)\nel jefe/la jefa (boss)\nla empresa (company)\na tiempo parcial (part-time)\na tiempo completo (full-time)\nel paro (unemployment)"},
  {cat:"vocabulary", q:"House and home vocabulary (10 key words)", a:"la casa (house)\nel piso/apartamento (flat/apartment)\nel dormitorio (bedroom)\nla cocina (kitchen)\nel salón (living room)\nel cuarto de baño (bathroom)\nel jardín (garden)\nla planta baja (ground floor)\nel primer piso (first floor)\nmudarse (to move house)"},
  {cat:"grammar-irregular", q:"Conjugate SABER vs CONOCER (both mean 'to know')", a:"SABER (to know facts/how to):\nsé, sabes, sabe, sabemos, sabéis, saben\n'Sé nadar' (I know how to swim)\n\nCONOCER (to know/be familiar with people/places):\nconozco, conoces, conoce, conocemos, conocéis, conocen\n'Conozco Madrid' (I know Madrid)"},
  {cat:"grammar-irregular", q:"Conjugate DECIR (to say/tell) and OÍR (to hear)", a:"DECIR present: digo, dices, dice, decimos, decís, dicen\nPreterite: dije, dijiste, dijo, dijimos, dijisteis, dijeron\n\nOÍR present: oigo, oyes, oye, oímos, oís, oyen\nPreterite: oí, oíste, oyó, oímos, oísteis, oyeron"},
  {cat:"grammar-tenses", q:"How do you form the Future Perfect?", a:"habré, habrás, habrá, habremos, habréis, habrán + past participle\nUsed for: will have done something by a certain time.\n'Para junio, habré terminado los exámenes' (By June, I will have finished the exams)"},
  {cat:"grammar-tenses", q:"How do you form the Conditional Perfect?", a:"habría, habrías, habría, habríamos, habríais, habrían + past participle\nUsed for: would have done something.\n'Habría ido a la fiesta, pero estaba enfermo' (I would have gone to the party, but I was ill)"},
  {cat:"subjunctive", q:"What triggers the Subjunctive after 'cuando'?", a:"When 'cuando' (when) refers to a FUTURE action, use the subjunctive:\n'Cuando tenga dinero, compraré un coche' (When I have money, I'll buy a car)\nBut for habitual/past: use indicative:\n'Cuando llego a casa, como' (When I arrive home, I eat)"},
  {cat:"exam-phrases", q:"Phrases for giving advice", a:"Te aconsejo que + subjunctive (I advise you to...)\nDeberías + infinitive (You should...)\nSería mejor + infinitive (It would be better to...)\nYo que tú... (If I were you...)\nEs recomendable que + subjunctive (It's advisable that...)\nHay que + infinitive (One must...)"},
  {cat:"vocabulary", q:"City and directions vocabulary", a:"a la derecha (to the right)\na la izquierda (to the left)\ntodo recto/derecho (straight ahead)\nla esquina (corner)\nel cruce (crossroads)\nel semáforo (traffic light)\nel ayuntamiento (town hall)\nla plaza (square)\nel puente (bridge)\nenfrente de (opposite)"},
  {cat:"grammar-irregular", q:"What are Demonstrative Adjectives and Pronouns?", a:"This: este/esta/estos/estas (near speaker)\nThat: ese/esa/esos/esas (near listener)\nThat over there: aquel/aquella/aquellos/aquellas (far from both)\nAs pronouns, add accent: éste, ése, aquél (older convention)\n'Este libro es interesante' (This book is interesting)"},
  {cat:"grammar-irregular", q:"Explain the difference between QUE, CUAL, and QUIEN", a:"Que: that, which, who (most common relative pronoun)\nCual/Cuales: which (one/ones) — used in questions with ser\nQuien/Quienes: who — used after prepositions for people\n'¿Qué quieres?' (What do you want?)\n'¿Cuál prefieres?' (Which do you prefer?)\n'¿Con quién vas?' (Who are you going with?)"},
  {cat:"writing-tips", q:"How to structure a Diary Entry (journal entry) for the exam", a:"Start: Querido diario (Dear diary)\nPara 1: What happened / where you went (preterite)\nPara 2: How you felt / what it was like (imperfect for descriptions)\nPara 3: Future plans / what you will do (future tense)\nEnd: Hasta mañana / Hasta la próxima\nUse range of tenses + opinions + feelings for high marks"},
  {cat:"vocabulary", q:"Feelings and emotions vocabulary (10 key words)", a:"contento/a (happy/content)\ntriste (sad)\nenfadado/a (angry)\npreocupado/a (worried)\nasustado/a (scared)\nsorprendido/a (surprised)\navergonzado/a (embarrassed)\norgulloso/a (proud)\nceloso/a (jealous)\nagradecido/a (grateful)"},
  {cat:"grammar-irregular", q:"What are Possessive Adjectives in Spanish?", a:"mi/mis (my)\ntu/tus (your — informal)\nsu/sus (his/her/its/your formal/their)\nnuestro/a/os/as (our)\nvuestro/a/os/as (your — plural informal)\nMust agree with the THING possessed, not the owner.\n'Mis padres' (my parents), 'nuestra casa' (our house)"},
  {cat:"listening-tips", q:"Common question types in the Listening exam", a:"1. Personal details (name, age, where they live)\n2. Daily routine and times\n3. Opinions and reasons\n4. Future plans\n5. Describing an event in the past\n6. Advertisements (prices, opening hours, offers)\n7. News bulletins (who, what, where, when)\n8. Weather forecast"},
  {cat:"exam-phrases", q:"Useful phrases for expressing cause and effect", a:"porque (because)\ndebido a (due to)\na causa de (because of)\npor eso (that's why / for that reason)\ncomo resultado (as a result)\npor consiguiente (consequently)\nen consecuencia (as a consequence)\ngracias a (thanks to)\nla razón es que (the reason is that)"},
  {cat:"vocabulary", q:"Weather vocabulary", a:"hace sol (it's sunny)\nhace calor (it's hot)\nhace frío (it's cold)\nhace viento (it's windy)\nhace buen/mal tiempo (the weather is good/bad)\nllover — llueve (to rain — it's raining)\nnevar — nieva (to snow — it's snowing)\nnublado (cloudy)\nla tormenta (storm)\nel pronóstico (forecast)"},
  {cat:"grammar-tenses", q:"What is the Gerund and when is it used?", a:"Formed: -ar → -ando, -er/-ir → -iendo\nIrregulars: durmiendo (dormir), leyendo (leer), diciendo (decir)\nUsed with estar for present continuous: 'Estoy comiendo'\nAlso used as 'by doing': 'Practicando, mejoras' (By practising, you improve)\nNever used as a noun (use infinitive instead): 'Nadar es divertido'"},
  {cat:"reading-tips", q:"Key vocabulary for understanding Reading Comprehension instructions", a:"según (according to)\nseñala/indica (point out/indicate)\nverdadero o falso (true or false)\nbusca en el texto (find in the text)\n¿qué opina el autor? (what does the author think?)\nresume (summarise)\nen tus propias palabras (in your own words)\nel párrafo (paragraph)"},
  {cat:"exam-phrases", q:"Phrases for introducing and developing arguments in essays", a:"En cuanto a... (As for... / Regarding...)\nCon respecto a... (With regard to...)\nEs importante señalar que (It's important to point out that)\nNo hay que olvidar que (One mustn't forget that)\nA pesar de (Despite / In spite of)\nTeniendo en cuenta que (Taking into account that)\nEn lo que se refiere a (As far as ... is concerned)"},
  {cat:"grammar-irregular", q:"What are Adverbs and how are they formed in Spanish?", a:"Many adverbs formed by adding -mente to the feminine form of the adjective:\nrápida → rápidamente (quickly)\nlenta → lentamente (slowly)\nfácil → fácilmente (easily)\nCommon irregular adverbs: bien (well), mal (badly), mucho (a lot), poco (little), siempre (always), nunca (never), ya (already), todavía (still)"}
];
