var FLASHCARDS_ACCOUNTING = [
  // ===== FINAL ACCOUNTS =====
  {cat:"final-accounts", q:"What are the 3 main Final Accounts?", a:"1. Trading Account (calculates Gross Profit)\n2. Profit & Loss Account (calculates Net Profit)\n3. Balance Sheet (shows assets, liabilities, capital at a point in time)"},
  {cat:"final-accounts", q:"How do you calculate Gross Profit?", a:"Gross Profit = Sales - Cost of Sales\nCost of Sales = Opening Stock + Purchases - Closing Stock\n(Adjust for returns: Net Sales = Sales - Sales Returns; Net Purchases = Purchases - Purchase Returns)"},
  {cat:"final-accounts", q:"How do you calculate Net Profit?", a:"Net Profit = Gross Profit + Other Income - Expenses\nOther Income: discount received, rent received, commission earned, etc.\nExpenses: wages, rent, insurance, light & heat, depreciation, bad debts, etc."},
  {cat:"final-accounts", q:"What is the Balance Sheet equation?", a:"Assets = Liabilities + Capital\nOr: Capital = Assets - Liabilities\nFixed Assets + Current Assets = Capital + Long-term Liabilities + Current Liabilities"},
  {cat:"final-accounts", q:"Define Fixed Assets (Non-Current Assets)", a:"Assets purchased for long-term use in the business, not intended for resale. Examples: premises, machinery, vehicles, furniture & fittings. Shown at cost less accumulated depreciation (Net Book Value)."},
  {cat:"final-accounts", q:"Define Current Assets", a:"Short-term assets that can be converted to cash within one year. Listed in order of increasing liquidity:\nClosing Stock → Debtors → Prepayments → Bank → Cash"},
  {cat:"final-accounts", q:"Define Current Liabilities", a:"Short-term debts that must be paid within one year.\nExamples: Creditors, Bank Overdraft, Accruals, Tax Payable, VAT Payable"},
  {cat:"final-accounts", q:"How is Capital on the Balance Sheet calculated?", a:"Opening Capital + Net Profit - Drawings = Closing Capital\n(Or + Capital Introduced if applicable)"},
  {cat:"final-accounts", q:"What is a Manufacturing Account?", a:"Prepared by manufacturing businesses BEFORE the Trading Account.\nCalculates: Cost of Raw Materials Consumed + Direct Wages + Factory Overheads = Factory Cost of Production\nTransfers finished goods to Trading Account at factory cost."},
  {cat:"final-accounts", q:"Define Working Capital", a:"Working Capital = Current Assets - Current Liabilities\nRepresents the money available for day-to-day operations.\nAlso called Net Current Assets."},

  // ===== ADJUSTMENTS =====
  {cat:"adjustments", q:"What is an Accrual?", a:"An expense incurred but not yet paid at year end.\nEffect: increase the expense in P&L (debit) + show as a current liability in Balance Sheet (credit).\nExample: electricity used in December but bill received in January."},
  {cat:"adjustments", q:"What is a Prepayment?", a:"An expense paid in advance (before the period it relates to).\nEffect: reduce the expense in P&L (credit) + show as a current asset in Balance Sheet (debit).\nExample: insurance paid for 15 months — 3 months is prepaid."},
  {cat:"adjustments", q:"How do you handle Bad Debts?", a:"A bad debt is a debtor who will definitely not pay.\nDouble entry: Debit Bad Debts (expense in P&L), Credit Debtors (reduce asset in B/S).\nRemove from debtors figure on Balance Sheet."},
  {cat:"adjustments", q:"What is a Provision for Bad Debts?", a:"An estimate of the percentage of debtors who may not pay.\nIncrease in provision: Debit P&L (expense)\nDecrease in provision: Credit P&L (income)\nDeduct provision from Debtors on Balance Sheet.\nCalculated on debtors AFTER bad debts written off."},
  {cat:"adjustments", q:"How are Goods for Own Use treated?", a:"When the owner takes goods from the business for personal use.\nDouble entry: Debit Drawings (increase), Credit Purchases (decrease).\nReduces both Purchases in Trading Account and increases Drawings deducted from Capital."},
  {cat:"adjustments", q:"How is Interest on Capital treated?", a:"Interest paid to the owner on their capital investment.\nDouble entry: Debit Interest on Capital (P&L expense), Credit Capital (increase).\nNot a real cash payment — just an adjustment."},
  {cat:"adjustments", q:"What is a Dishonoured Cheque from a Debtor?", a:"A cheque received from a debtor that bounces (bank rejects it).\nDouble entry: Debit Debtors (debt is back), Credit Bank (money reversed).\nThe debtor still owes the money."},
  {cat:"adjustments", q:"What is the effect of returns on the Trading Account?", a:"Sales Returns (Returns Inward): deducted from Sales to give Net Sales.\nPurchase Returns (Returns Outward): deducted from Purchases to give Net Purchases.\nBoth reduce the respective figures."},

  // ===== RATIOS =====
  {cat:"ratios", q:"Calculate and interpret the Current Ratio", a:"Current Ratio = Current Assets / Current Liabilities\nIdeal: 2:1\nMeasures short-term liquidity — ability to pay debts due within one year.\nToo high may mean idle assets."},
  {cat:"ratios", q:"Calculate and interpret the Acid Test Ratio", a:"Acid Test = (Current Assets - Closing Stock) / Current Liabilities\nIdeal: 1:1\nA stricter test of liquidity — excludes stock as it may not be easily converted to cash."},
  {cat:"ratios", q:"Calculate the Gross Profit Percentage", a:"GP% = (Gross Profit / Sales) × 100\nShows profit earned on trading before expenses.\nHigher is better. Compare to previous years and industry average."},
  {cat:"ratios", q:"Calculate the Net Profit Percentage", a:"NP% = (Net Profit / Sales) × 100\nShows overall profitability after all expenses.\nIf GP% is stable but NP% falls → expenses are rising."},
  {cat:"ratios", q:"Calculate the Mark-Up Percentage", a:"Mark-Up % = (Gross Profit / Cost of Sales) × 100\nShows profit as a percentage of cost.\nIf Mark-Up is 50%, the selling price is 150% of cost."},
  {cat:"ratios", q:"Calculate the Rate of Stock Turnover", a:"Stock Turnover = Cost of Sales / Average Stock\nAverage Stock = (Opening Stock + Closing Stock) / 2\nShows how many times stock is sold and replaced per year.\nHigher = more efficient stock management."},
  {cat:"ratios", q:"Calculate Return on Capital Employed (ROCE)", a:"ROCE = (Net Profit / Capital Employed) × 100\nCapital Employed = Total Assets - Current Liabilities (or Capital + Long-term Liabilities)\nShows efficiency of capital usage. Compare to bank interest rates."},
  {cat:"ratios", q:"Calculate the Debtors Collection Period", a:"Debtors Days = (Debtors / Credit Sales) × 365\nShows average number of days to collect payment from debtors.\nLower is better — aim for within credit terms (e.g., 30 days)."},
  {cat:"ratios", q:"Calculate the Creditors Payment Period", a:"Creditors Days = (Creditors / Credit Purchases) × 365\nShows average number of days to pay creditors.\nShould be within credit terms. Ideally longer than debtors days (use cash flow advantage)."},
  {cat:"ratios", q:"What is the Dividend Cover Ratio?", a:"Dividend Cover = Net Profit After Tax / Total Dividends\nShows how many times dividends could be paid from profits.\nHigher ratio = more sustainable dividend. If < 1, paying dividends from reserves."},
  {cat:"ratios", q:"What is Earnings Per Share (EPS)?", a:"EPS = Net Profit After Tax / Number of Ordinary Shares\nShows profit attributable to each share.\nKey measure for investors comparing companies."},

  // ===== DEPRECIATION =====
  {cat:"depreciation", q:"Define Depreciation", a:"The allocation of the cost of a fixed asset over its useful economic life. NOT a cash expense — it's an accounting adjustment that recognises the decline in value of an asset due to wear and tear, obsolescence, or time."},
  {cat:"depreciation", q:"Calculate Straight Line Depreciation", a:"Annual Depreciation = (Cost - Residual Value) / Useful Life\nExample: Asset costs €20,000, residual value €2,000, life 6 years:\n(20,000 - 2,000) / 6 = €3,000 per year\nSame amount each year."},
  {cat:"depreciation", q:"Calculate Reducing Balance Depreciation", a:"Depreciation = Rate % × Net Book Value (at start of year)\nNBV decreases each year → depreciation amount decreases.\nYear 1: 20% × €20,000 = €4,000 (NBV = €16,000)\nYear 2: 20% × €16,000 = €3,200 (NBV = €12,800)\nHigher charge in early years."},
  {cat:"depreciation", q:"How do you account for the Sale of a Fixed Asset?", a:"1. Remove asset at cost (Credit Asset Account)\n2. Remove accumulated depreciation (Debit Accumulated Depreciation)\n3. Record sale proceeds (Debit Bank)\n4. Calculate profit/loss on disposal:\nProfit if proceeds > NBV → credit P&L\nLoss if proceeds < NBV → debit P&L"},

  // ===== CONTROL ACCOUNTS =====
  {cat:"control-accounts", q:"What is a Debtors Control Account?", a:"A summary account in the general ledger that shows the total amount owed by all debtors.\nDebit side: opening balance, credit sales, dishonoured cheques\nCredit side: receipts from debtors, sales returns, bad debts, discounts allowed\nClosing balance = total debtors."},
  {cat:"control-accounts", q:"What is a Creditors Control Account?", a:"A summary account showing the total amount owed to all creditors.\nDebit side: payments to creditors, purchase returns, discounts received\nCredit side: opening balance, credit purchases\nClosing balance = total creditors."},
  {cat:"control-accounts", q:"What are the purposes of Control Accounts?", a:"1. Check accuracy of the subsidiary ledgers (debtors/creditors ledger)\n2. Detect errors quickly\n3. Provide quick total debtors/creditors figures\n4. Internal control — prevents fraud\n5. Useful for preparation of final accounts"},
  {cat:"control-accounts", q:"Name 3 items that appear on the DEBIT side of a Debtors Control Account", a:"1. Opening balance (b/d)\n2. Credit sales\n3. Dishonoured cheques\n4. Interest charged to debtors"},
  {cat:"control-accounts", q:"Name 3 items that appear on the CREDIT side of a Debtors Control Account", a:"1. Bank/Cash receipts from debtors\n2. Sales returns (returns inward)\n3. Bad debts written off\n4. Discounts allowed\n5. Closing balance (c/d)"},

  // ===== CLUB ACCOUNTS =====
  {cat:"club-accounts", q:"What are Club Accounts?", a:"Financial statements of a non-profit organisation (club, society, charity).\nReceipts & Payments Account (instead of cash book)\nIncome & Expenditure Account (instead of P&L)\nAccumulated Fund (instead of capital)"},
  {cat:"club-accounts", q:"What is the difference between Receipts & Payments and Income & Expenditure?", a:"Receipts & Payments: a cash summary — lists all cash in/out (includes capital items). Like a cash book.\nIncome & Expenditure: accruals-based — matches income and expenses to the period (like P&L). Surplus/Deficit instead of Profit/Loss."},
  {cat:"club-accounts", q:"How do you calculate Subscription Income for the Income & Expenditure Account?", a:"Subscriptions received in the year\n+ Subscriptions due but not yet received (debtors)\n- Subscriptions received in advance (creditors)\n- Subscriptions relating to previous year received this year\n= Subscription Income for the year"},
  {cat:"club-accounts", q:"What is the Accumulated Fund?", a:"The club's equivalent of capital. Calculated from the opening Balance Sheet:\nAccumulated Fund = Assets - Liabilities at the start of the year.\nSurplus is added; deficit is deducted."},
  {cat:"club-accounts", q:"How do you handle a Club Bar/Shop?", a:"Prepare a separate Trading Account for the bar/shop.\nSales - Cost of Sales = Gross Profit (or loss)\nTransfer the profit/loss to the main Income & Expenditure Account."},

  // ===== CASH FLOW STATEMENT =====
  {cat:"cash-flow", q:"What is a Cash Flow Statement?", a:"Shows the movement of cash in and out of a business during a period. Divided into 3 sections:\n1. Operating Activities\n2. Investing Activities\n3. Financing Activities\nReconciles opening and closing cash/bank balances."},
  {cat:"cash-flow", q:"What are Operating Activities in a Cash Flow Statement?", a:"Cash flows from the main trading activities.\nStart with Net Profit, then adjust:\n+ Depreciation (add back — not a cash expense)\n+ Loss on sale of assets / - Profit on sale\n- Increase in stock / + Decrease in stock\n- Increase in debtors / + Decrease in debtors\n+ Increase in creditors / - Decrease in creditors"},
  {cat:"cash-flow", q:"What are Investing Activities?", a:"Cash flows from buying/selling long-term assets.\nOutflows: purchase of fixed assets\nInflows: sale of fixed assets (proceeds received)\nAlways use the CASH amount actually paid/received."},
  {cat:"cash-flow", q:"What are Financing Activities?", a:"Cash flows from raising/repaying finance.\nInflows: shares issued, loans received, capital introduced\nOutflows: loan repayments, dividends paid, drawings"},

  // ===== BUDGETING =====
  {cat:"budgeting", q:"Define a Budget", a:"A financial plan for a future period of time, expressed in monetary terms. Used for planning, control, coordination, motivation, and performance evaluation."},
  {cat:"budgeting", q:"Name 4 types of budgets", a:"1. Sales Budget (expected revenue)\n2. Production Budget (units to produce)\n3. Cash Budget (expected cash receipts and payments)\n4. Master Budget (combines all budgets into projected final accounts)"},
  {cat:"budgeting", q:"What is a Cash Budget?", a:"A forecast of expected cash inflows and outflows over a period.\nFormat: Opening Balance + Total Receipts - Total Payments = Closing Balance\nHelps identify months where cash shortfall or surplus may occur."},
  {cat:"budgeting", q:"What is Variance Analysis?", a:"Comparing budgeted figures to actual figures and analysing the differences.\nFavourable variance: actual is better than budget (higher revenue or lower cost).\nAdverse/Unfavourable variance: actual is worse than budget."},
  {cat:"budgeting", q:"Name 3 advantages of Budgeting", a:"1. Planning: forces management to plan ahead\n2. Control: compare actual vs budget to take corrective action\n3. Coordination: ensures departments work towards common goals\n4. Motivation: targets can motivate staff\n5. Evaluation: assess performance of managers"},

  // ===== MARGINAL COSTING =====
  {cat:"marginal-costing", q:"Define Marginal Cost", a:"The cost of producing one additional unit of output. In accounting, it equals the variable cost per unit (direct materials + direct labour + variable overheads). Fixed costs are excluded."},
  {cat:"marginal-costing", q:"Define Contribution", a:"Contribution = Selling Price - Variable Cost (per unit)\nOr: Total Contribution = Total Sales - Total Variable Costs\nContribution goes towards covering fixed costs. After fixed costs are covered, it becomes profit."},
  {cat:"marginal-costing", q:"Calculate the Break-Even Point", a:"BEP (units) = Fixed Costs / Contribution per unit\nBEP (sales €) = Fixed Costs / C/S Ratio\nC/S Ratio = Contribution per unit / Selling Price per unit\nAt BEP: Total Contribution = Total Fixed Costs (Profit = 0)"},
  {cat:"marginal-costing", q:"What is the Margin of Safety?", a:"Margin of Safety = Actual Sales - Break-Even Sales\nShows how much sales can drop before the business makes a loss.\nCan be expressed in units or as a percentage of actual sales."},
  {cat:"marginal-costing", q:"Distinguish between Fixed and Variable Costs", a:"Fixed Costs: do not change with output level (rent, insurance, depreciation). Total stays constant; per unit decreases as output rises.\nVariable Costs: change directly with output (raw materials, direct labour). Total increases; per unit stays constant."},
  {cat:"marginal-costing", q:"What is a Break-Even Chart?", a:"A graph showing Total Revenue and Total Cost lines.\nX-axis: output/sales volume. Y-axis: costs/revenue (€).\nBEP: where TR and TC lines cross.\nAbove BEP: profit zone. Below BEP: loss zone.\nMargin of safety shown as distance from BEP to actual output."},

  // ===== ACCOUNTING CONCEPTS =====
  {cat:"concepts", q:"State the Going Concern Concept", a:"The assumption that the business will continue to operate for the foreseeable future. Assets are valued at cost (not liquidation value). If not a going concern, this must be disclosed."},
  {cat:"concepts", q:"State the Prudence/Conservatism Concept", a:"Anticipate losses but do not anticipate profits. Record expenses and liabilities as soon as they are known. Only record revenue when it is realised. Example: provision for bad debts."},
  {cat:"concepts", q:"State the Accruals/Matching Concept", a:"Income and expenses should be matched to the period in which they are incurred, not when cash is received or paid. Gives rise to accruals and prepayments."},
  {cat:"concepts", q:"State the Consistency Concept", a:"Accounting methods and policies should be applied consistently from one period to the next. Example: if straight-line depreciation is used, it should not be changed to reducing balance without disclosure."},
  {cat:"concepts", q:"State the Materiality Concept", a:"Only items that are significant enough to influence the decisions of users need to be disclosed separately. Immaterial items can be aggregated. Example: a stapler need not be capitalised as a fixed asset."},
  {cat:"concepts", q:"State the Business Entity Concept", a:"The business is treated as a separate entity from its owner(s). Personal transactions of the owner are excluded from the business accounts (except drawings/capital)."},
  {cat:"concepts", q:"State the Money Measurement Concept", a:"Only transactions that can be expressed in monetary terms are recorded in the accounts. Items like staff morale or brand reputation cannot be recorded."},
  {cat:"concepts", q:"State the Realisation Concept", a:"Revenue is recognised when the goods/services are delivered to the customer (earned), not when cash is received. The sale occurs when the legal title passes to the buyer."},
  {cat:"concepts", q:"State the Historical Cost Concept", a:"Assets are recorded at their original purchase price (cost), not at current market value. Exception: revaluation of land and buildings."},
  {cat:"concepts", q:"What is the Dual Aspect Concept?", a:"Every transaction has two effects — a debit and a credit of equal value.\nAssets = Liabilities + Capital always holds.\nThis is the foundation of double-entry bookkeeping."},

  // ===== ADDITIONAL KEY TOPICS =====
  {cat:"final-accounts", q:"What are the main elements of a Company P&L Account?", a:"Turnover (Sales)\n- Cost of Sales = Gross Profit\n- Distribution + Admin Costs = Operating Profit\n+ Investment Income - Interest Payable = Profit Before Tax\n- Corporation Tax = Profit After Tax\n- Dividends = Retained Profit"},
  {cat:"final-accounts", q:"What is a Company Balance Sheet layout?", a:"Fixed Assets (Intangible + Tangible + Financial)\n+ Current Assets - Current Liabilities = Net Current Assets\n= Total Assets less Current Liabilities\n- Long-term Liabilities (Creditors >1 year)\n= Net Assets\nFinanced by: Share Capital + Reserves = Shareholders' Funds"},
  {cat:"ratios", q:"What is Gearing Ratio?", a:"Gearing = (Long-term Liabilities / Capital Employed) × 100\nCapital Employed = Shareholders' Funds + Long-term Liabilities\nHigh gearing (>50%): risky — large proportion of finance from borrowing\nLow gearing: safer — more equity financing"},
  {cat:"marginal-costing", q:"What is Absorption Costing?", a:"All production costs (fixed + variable) are allocated to each unit.\nDiffers from marginal costing which only uses variable costs.\nAbsorption profit ≠ marginal profit when stock levels change.\nRequired for external reporting."},
  {cat:"adjustments", q:"What are the Double Entry rules for common adjustments?", a:"Accrual: Debit Expense (↑), Credit Accruals/Creditors (↑ CL)\nPrepayment: Debit Prepayments (↑ CA), Credit Expense (↓)\nBad Debt: Debit Bad Debts (↑ expense), Credit Debtors (↓ CA)\nDepreciation: Debit Depreciation (↑ expense), Credit Accumulated Depreciation (↑ contra asset)"},
  {cat:"cash-flow", q:"Why is a Cash Flow Statement important?", a:"1. Profit ≠ cash — profitable businesses can run out of cash\n2. Shows where cash came from and where it went\n3. Helps assess ability to pay debts and dividends\n4. Better indicator of financial health than profit alone\n5. Required for company financial statements"},
  {cat:"club-accounts", q:"Name 3 differences between Club Accounts and Business Accounts", a:"1. Income & Expenditure Account (not P&L)\n2. Surplus/Deficit (not Profit/Loss)\n3. Accumulated Fund (not Capital)\n4. Subscriptions as main income (not Sales)\n5. No profit motive — aim to provide service to members"},
  {cat:"concepts", q:"What are the users of financial statements?", a:"Internal: owners/shareholders, management, employees\nExternal: banks/lenders, creditors, Revenue Commissioners, potential investors, government agencies\nEach user has different information needs."},
  {cat:"ratios", q:"How do you interpret a fall in GP% but stable NP%?", a:"GP% fall: cost of sales rising faster than sales (e.g., raw material costs up, lower mark-up, more competition).\nStable NP%: the business has cut overheads/expenses to offset the fall in gross profit. Expenses are being well controlled."},
  {cat:"depreciation", q:"Name 3 causes of Depreciation", a:"1. Wear and tear from use\n2. Obsolescence (technological advances make asset outdated)\n3. Passage of time (leases expire)\n4. Depletion (natural resources extracted)"},
  {cat:"final-accounts", q:"What is Goodwill?", a:"An intangible fixed asset. The excess of the purchase price of a business over the fair value of its net assets. Arises when buying an existing business.\nGoodwill = Purchase Price - Net Assets Acquired\nAmortised (written off) over its useful life."},
  {cat:"ratios", q:"Calculate the Interest Cover Ratio", a:"Interest Cover = Operating Profit / Interest Payable\nShows how many times the firm can cover its interest payments from profits.\nHigher is better. If < 1, the firm cannot cover interest from profits."},
  {cat:"final-accounts", q:"What is a Revaluation Reserve?", a:"Created when a fixed asset (usually land/buildings) is revalued upwards.\nThe increase in value is NOT profit — it goes to a Revaluation Reserve on the Balance Sheet under Capital & Reserves.\nDouble entry: Debit Fixed Asset, Credit Revaluation Reserve."},
  {cat:"adjustments", q:"How do you treat a Debtor's cheque lodged but not yet credited by bank?", a:"This is a timing difference appearing on the Bank Reconciliation Statement.\nThe cheque has been lodged by the business but not yet cleared by the bank.\nAdd to the balance per bank statement to reconcile."},
  {cat:"final-accounts", q:"What is a Bank Reconciliation Statement?", a:"A statement that reconciles the cash book balance with the bank statement balance.\nDifferences arise from: unpresented cheques, lodgements not yet credited, bank charges, standing orders, direct debits, interest.\nAdjust cash book first, then prepare reconciliation."},
  {cat:"control-accounts", q:"What is a Suspense Account?", a:"A temporary account used when the trial balance does not balance. Errors are investigated and corrected by journalising corrections.\nWhen all errors are found, the suspense account balance becomes zero."},
  {cat:"concepts", q:"Name 4 types of errors that do NOT affect the Trial Balance", a:"1. Error of omission (transaction completely omitted)\n2. Error of commission (correct amount, wrong personal account)\n3. Error of principle (correct amount, wrong class of account)\n4. Compensating errors (two errors cancel each other out)\n5. Error of original entry (wrong amount in both accounts)"},
  {cat:"final-accounts", q:"What are Debentures?", a:"Long-term loans to a company, usually with a fixed interest rate. Debenture holders are creditors, NOT owners.\nInterest must be paid regardless of profit.\nShown as long-term liabilities on the Balance Sheet.\nMore secure than shares (repaid before shareholders if company winds up)."},
  {cat:"ratios", q:"What is the Price/Earnings (P/E) Ratio?", a:"P/E = Market Price per Share / Earnings Per Share\nShows how much investors are willing to pay for each euro of earnings.\nHigh P/E: investors expect future growth.\nLow P/E: may be undervalued or low growth expected."},
  {cat:"budgeting", q:"What is a Flexible Budget?", a:"A budget that adjusts for actual activity levels. Variable costs are recalculated based on actual output, while fixed costs remain unchanged.\nMore useful for variance analysis than a static budget because it provides a fairer comparison."},
  {cat:"marginal-costing", q:"Define Semi-Variable (Mixed) Cost", a:"A cost with both fixed and variable components.\nExample: phone bill — fixed line rental + variable call charges.\nCan be split using the High-Low method:\nVariable cost per unit = (Highest cost − Lowest cost) / (Highest output − Lowest output)"},
  {cat:"final-accounts", q:"What is a Provision?", a:"An amount set aside for a probable future liability where the exact amount or timing is uncertain.\nExample: provision for bad debts, provision for depreciation.\nShown as a deduction from the related asset or as a liability."}
];
