var FLASHCARDS_BIOLOGY = [
  // ===== CELL BIOLOGY =====
  {cat:"cell-biology", q:"Name 5 organelles found in animal cells and their functions", a:"1. Nucleus — contains DNA, controls cell activity\n2. Mitochondria — site of aerobic respiration (ATP production)\n3. Ribosomes — site of protein synthesis\n4. Cell membrane — controls entry/exit of substances\n5. Endoplasmic reticulum — transport of materials within cell"},
  {cat:"cell-biology", q:"Name 3 structures found in plant cells but NOT animal cells", a:"1. Cell wall — rigid, made of cellulose, provides support\n2. Chloroplasts — contain chlorophyll for photosynthesis\n3. Large central vacuole — stores cell sap, maintains turgor pressure"},
  {cat:"cell-biology", q:"Define Osmosis", a:"The movement of water molecules from a region of high water concentration to a region of low water concentration across a selectively permeable membrane."},
  {cat:"cell-biology", q:"Define Diffusion", a:"The movement of molecules or ions from a region of high concentration to a region of low concentration along a concentration gradient. Passive process (no energy required)."},
  {cat:"cell-biology", q:"Define Active Transport", a:"The movement of molecules or ions across a membrane against the concentration gradient (low → high concentration). Requires energy (ATP). Example: uptake of minerals by root hair cells."},
  {cat:"cell-biology", q:"What is a Selectively Permeable Membrane?", a:"A membrane that allows some substances to pass through but not others. The cell membrane is selectively permeable — it controls what enters and leaves the cell."},
  {cat:"cell-biology", q:"Distinguish between Prokaryotic and Eukaryotic cells", a:"Prokaryotic: no true nucleus (DNA free in cytoplasm), no membrane-bound organelles, smaller (1-10μm). Example: bacteria.\nEukaryotic: true nucleus with nuclear membrane, membrane-bound organelles, larger (10-100μm). Example: animal/plant cells."},
  {cat:"cell-biology", q:"Define Turgor Pressure", a:"The pressure exerted by the cell contents (water) pushing outward against the cell wall in a plant cell. Keeps the plant rigid and upright. Lost during plasmolysis."},
  {cat:"cell-biology", q:"What is Plasmolysis?", a:"The shrinking of the cell membrane away from the cell wall when a plant cell is placed in a hypertonic solution (loses water by osmosis). The cell becomes flaccid."},

  // ===== BIOMOLECULES =====
  {cat:"biomolecules", q:"Name the 4 main biomolecules", a:"1. Carbohydrates (C, H, O)\n2. Lipids (C, H, O — less O than carbs)\n3. Proteins (C, H, O, N, sometimes S)\n4. Nucleic acids (C, H, O, N, P) — DNA and RNA"},
  {cat:"biomolecules", q:"What is the test for starch?", a:"Iodine solution: turns blue-black in the presence of starch (remains brown if absent)."},
  {cat:"biomolecules", q:"What is the test for reducing sugars (e.g., glucose)?", a:"Benedict's test: add Benedict's reagent and heat in a water bath. Turns from blue to green/orange/brick-red if reducing sugar is present."},
  {cat:"biomolecules", q:"What is the test for protein?", a:"Biuret test: add NaOH then CuSO₄ solution. Turns purple/violet if protein is present (remains blue if absent)."},
  {cat:"biomolecules", q:"What is the test for lipids/fats?", a:"Emulsion test: dissolve sample in ethanol, pour into water. A white/cloudy emulsion forms if lipid is present."},
  {cat:"biomolecules", q:"Distinguish between monosaccharides, disaccharides, and polysaccharides", a:"Monosaccharides: single sugar units (glucose, fructose, galactose)\nDisaccharides: two sugars joined (sucrose, maltose, lactose)\nPolysaccharides: many sugars (starch, glycogen, cellulose)"},
  {cat:"biomolecules", q:"What is the structure of a protein?", a:"Made of amino acids joined by peptide bonds.\nPrimary: sequence of amino acids\nSecondary: alpha helix or beta sheet\nTertiary: 3D folding\nQuaternary: multiple polypeptide chains"},
  {cat:"biomolecules", q:"Name 3 functions of lipids", a:"1. Energy storage (more energy per gram than carbs)\n2. Insulation (subcutaneous fat)\n3. Protection of organs\n4. Component of cell membranes (phospholipids)"},
  {cat:"biomolecules", q:"What is the structure of DNA?", a:"Double helix — two antiparallel polynucleotide strands.\nEach nucleotide: deoxyribose sugar + phosphate group + nitrogenous base.\nBases: A-T (2 H-bonds), C-G (3 H-bonds).\nSugar-phosphate backbone on outside, bases on inside."},

  // ===== ENZYMES =====
  {cat:"enzymes", q:"Define Enzyme", a:"A biological catalyst that speeds up chemical reactions without being used up. Made of protein. Lowers the activation energy needed for a reaction."},
  {cat:"enzymes", q:"Explain the Lock and Key model", a:"The substrate (key) fits into the active site (lock) of the enzyme. The enzyme and substrate have complementary shapes. Enzyme-substrate complex forms, products released, enzyme is reused."},
  {cat:"enzymes", q:"Name 4 factors affecting enzyme activity", a:"1. Temperature (optimum ~37°C for human enzymes; denatured at high temps)\n2. pH (each enzyme has an optimum pH; e.g., pepsin pH 2)\n3. Substrate concentration (rate increases until all active sites saturated)\n4. Enzyme concentration"},
  {cat:"enzymes", q:"What is Denaturation?", a:"A permanent change in the shape of an enzyme's active site caused by high temperature or extreme pH. The substrate can no longer fit, and the enzyme loses its catalytic function."},
  {cat:"enzymes", q:"What is an Immobilised Enzyme?", a:"An enzyme that is fixed or attached to an inert material (e.g., alginate beads). Advantages: enzyme can be reused, easily recovered, products are not contaminated with enzyme."},
  {cat:"enzymes", q:"Define Metabolism", a:"The sum of all chemical reactions occurring in a living organism. Includes anabolism (building up — e.g., photosynthesis) and catabolism (breaking down — e.g., respiration)."},
  {cat:"enzymes", q:"What is Competitive Inhibition?", a:"An inhibitor molecule with a similar shape to the substrate competes for the active site. Can be overcome by increasing substrate concentration. Example: malonate inhibits succinate dehydrogenase."},

  // ===== GENETICS =====
  {cat:"genetics", q:"Define Gene", a:"A section of DNA that codes for a specific protein (or polypeptide). Genes are found at specific locations (loci) on chromosomes."},
  {cat:"genetics", q:"Define Allele", a:"An alternative form of a gene. For example, the gene for eye colour may have alleles for blue or brown. Diploid organisms have two alleles for each gene (one from each parent)."},
  {cat:"genetics", q:"Distinguish between Dominant and Recessive alleles", a:"Dominant: expressed in the phenotype when one or two copies are present (heterozygous or homozygous). Represented by capital letter (e.g., B).\nRecessive: only expressed when two copies are present (homozygous). Represented by lowercase (e.g., b)."},
  {cat:"genetics", q:"Define Genotype and Phenotype", a:"Genotype: the genetic makeup of an organism (e.g., Bb).\nPhenotype: the physical expression/observable characteristic (e.g., brown eyes)."},
  {cat:"genetics", q:"What is a Monohybrid Cross?", a:"A genetic cross involving one gene with two alleles. Example: Bb × Bb.\nExpected ratio: 3 dominant : 1 recessive (phenotype)\nGenotype ratio: 1 BB : 2 Bb : 1 bb"},
  {cat:"genetics", q:"Define Codominance", a:"When both alleles are equally expressed in the heterozygote. Neither is dominant over the other. Example: blood group AB — both A and B antigens are expressed."},
  {cat:"genetics", q:"What is Sex-Linked Inheritance?", a:"When a gene is located on the X chromosome. Males (XY) only need one copy of a recessive allele to show the trait. Example: colour blindness, haemophilia. More common in males."},
  {cat:"genetics", q:"What is a Mutation?", a:"A change in the amount or structure of DNA. Can be gene mutations (point mutation, insertion, deletion) or chromosome mutations (non-disjunction). Can be caused by mutagens (radiation, chemicals)."},
  {cat:"genetics", q:"What is DNA Profiling (DNA Fingerprinting)?", a:"A technique used to identify individuals based on their unique DNA patterns. Uses: forensics, paternity testing, resolving immigration disputes. Involves restriction enzymes, gel electrophoresis, and DNA probes."},
  {cat:"genetics", q:"Define Genetic Engineering", a:"The process of altering an organism's DNA by inserting a gene from another organism. Steps:\n1. Identify and isolate desired gene (restriction enzymes)\n2. Insert into vector (plasmid)\n3. Transform host organism\n4. Express the gene"},

  // ===== ECOLOGY =====
  {cat:"ecology", q:"Define Ecosystem", a:"A community of living organisms (biotic) and their physical environment (abiotic factors) interacting as a system."},
  {cat:"ecology", q:"Define a Habitat", a:"The place where an organism lives. It provides food, shelter, and conditions needed for survival."},
  {cat:"ecology", q:"Define a Niche", a:"The functional role of an organism in its ecosystem — what it eats, where it lives, when it is active, and how it interacts with other species. No two species can occupy the same niche."},
  {cat:"ecology", q:"Name 4 Abiotic Factors", a:"1. Temperature\n2. Light intensity\n3. pH of soil/water\n4. Water availability\nOthers: wind, humidity, mineral content"},
  {cat:"ecology", q:"Name 4 Biotic Factors", a:"1. Predation\n2. Competition (inter- and intra-specific)\n3. Parasitism\n4. Symbiosis/mutualism"},
  {cat:"ecology", q:"What is Ecological Succession?", a:"The gradual change in species composition in an area over time.\nPrimary succession: colonisation of bare rock/new land.\nSecondary succession: recolonisation after disturbance.\nEnds at climax community (stable, self-sustaining)."},
  {cat:"ecology", q:"How do you estimate population size using a Quadrat?", a:"1. Place quadrats randomly in the habitat\n2. Count organisms in each quadrat\n3. Calculate average per quadrat\n4. Population = average per quadrat × (total area / quadrat area)"},
  {cat:"ecology", q:"Define the Carbon Cycle", a:"The biogeochemical cycle in which carbon moves between atmosphere (CO₂), organisms (photosynthesis/respiration), soil (decomposition), fossil fuels (combustion), and oceans."},
  {cat:"ecology", q:"Define the Nitrogen Cycle", a:"Nitrogen fixation (N₂ → NH₃ by bacteria/lightning) → nitrification (NH₃ → NO₃⁻) → absorption by plants → consumption by animals → decomposition → denitrification (NO₃⁻ → N₂)."},

  // ===== PHOTOSYNTHESIS =====
  {cat:"photosynthesis", q:"Write the overall equation for Photosynthesis", a:"6CO₂ + 6H₂O → C₆H₁₂O₆ + 6O₂\n(carbon dioxide + water → glucose + oxygen)\nRequires: light energy and chlorophyll"},
  {cat:"photosynthesis", q:"Where does Photosynthesis occur?", a:"In the chloroplasts of plant cells (mesophyll cells of leaves).\nLight stage: thylakoid membranes (grana)\nDark stage (Calvin cycle): stroma"},
  {cat:"photosynthesis", q:"Describe the Light Stage of Photosynthesis", a:"1. Light absorbed by chlorophyll → electrons excited\n2. Water split (photolysis): 2H₂O → 4H⁺ + 4e⁻ + O₂\n3. Electrons pass through electron transport chain → ATP produced\n4. NADP⁺ reduced to NADPH\nProducts: ATP, NADPH, O₂"},
  {cat:"photosynthesis", q:"Describe the Dark Stage (Calvin Cycle)", a:"1. CO₂ fixed by combining with RuBP (5C) → 2 molecules of GP (3C)\n2. GP reduced to G3P using ATP and NADPH from light stage\n3. G3P used to make glucose\n4. RuBP regenerated\nOccurs in stroma; does not directly require light but needs light-stage products."},
  {cat:"photosynthesis", q:"Name 3 factors limiting the rate of Photosynthesis", a:"1. Light intensity (increases rate up to a point)\n2. CO₂ concentration (increases rate up to a point)\n3. Temperature (optimum ~25-30°C; enzymes denature at high temps)"},

  // ===== RESPIRATION =====
  {cat:"respiration", q:"Write the overall equation for Aerobic Respiration", a:"C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + 38 ATP\n(glucose + oxygen → carbon dioxide + water + energy)"},
  {cat:"respiration", q:"Name the 3 stages of Aerobic Respiration", a:"1. Glycolysis (cytoplasm): glucose → 2 pyruvate; net gain 2 ATP\n2. Krebs Cycle (matrix of mitochondria): acetyl CoA oxidised; CO₂, NADH, FADH₂ produced\n3. Electron Transport Chain (inner membrane of mitochondria): 34 ATP produced; O₂ is final electron acceptor"},
  {cat:"respiration", q:"What is Anaerobic Respiration?", a:"Respiration without oxygen.\nIn animals: glucose → lactic acid (+ 2 ATP)\nIn yeast (fermentation): glucose → ethanol + CO₂ (+ 2 ATP)\nMuch less efficient than aerobic respiration."},
  {cat:"respiration", q:"What happens in Glycolysis?", a:"Occurs in cytoplasm. No oxygen required.\n1. Glucose (6C) phosphorylated using 2 ATP\n2. Split into 2 molecules of G3P (3C)\n3. G3P oxidised → 2 pyruvate (3C)\n4. Net gain: 2 ATP + 2 NADH"},
  {cat:"respiration", q:"What is the role of NAD and FAD in respiration?", a:"NAD⁺ and FAD are coenzymes (electron carriers).\nThey accept hydrogen atoms (electrons + protons) during glycolysis and Krebs cycle.\nNADH and FADH₂ carry electrons to the electron transport chain where ATP is produced."},

  // ===== HUMAN SYSTEMS =====
  {cat:"human-systems", q:"Describe the structure of the Heart", a:"4 chambers: right atrium, right ventricle, left atrium, left ventricle.\nValves prevent backflow (tricuspid, bicuspid, semilunar).\nRight side pumps deoxygenated blood to lungs (pulmonary circuit).\nLeft side pumps oxygenated blood to body (systemic circuit).\nLeft ventricle has thickest wall."},
  {cat:"human-systems", q:"Name the 3 types of blood vessels", a:"1. Arteries: thick muscular walls, carry blood away from heart, high pressure\n2. Veins: thinner walls, carry blood to heart, have valves, low pressure\n3. Capillaries: one cell thick walls, site of exchange, connect arteries to veins"},
  {cat:"human-systems", q:"Name the components of Blood", a:"1. Red blood cells (erythrocytes) — carry O₂ (haemoglobin), no nucleus\n2. White blood cells (leucocytes) — immune defence\n3. Platelets (thrombocytes) — blood clotting\n4. Plasma — liquid; transports nutrients, hormones, CO₂, waste"},
  {cat:"human-systems", q:"What is the role of the Kidneys?", a:"1. Excretion of waste (urea, excess salts)\n2. Osmoregulation (control water balance)\n3. pH regulation of blood\nProcess: filtration in Bowman's capsule → selective reabsorption in tubules → urine formed"},
  {cat:"human-systems", q:"Describe Gas Exchange in the Lungs", a:"Occurs in alveoli. O₂ diffuses from alveolar air into blood (binds to haemoglobin). CO₂ diffuses from blood into alveolar air.\nAdaptations: large surface area, thin walls (one cell thick), moist surface, rich blood supply."},
  {cat:"human-systems", q:"Name 3 hormones and their functions", a:"1. Insulin — lowers blood glucose (released by pancreas)\n2. Adrenaline — fight or flight response (released by adrenal glands)\n3. Oestrogen — female sex hormone, controls menstrual cycle (released by ovaries)"},
  {cat:"human-systems", q:"Describe the structure of a Neuron", a:"Cell body: contains nucleus\nDendrites: receive impulses\nAxon: carries impulse away from cell body\nMyelin sheath: insulates axon, speeds up impulse\nSynapse: gap between neurons; impulse transmitted by neurotransmitters (e.g., acetylcholine)"},
  {cat:"human-systems", q:"Describe the Digestive System", a:"Mouth (mechanical + amylase) → Oesophagus (peristalsis) → Stomach (HCl + pepsin) → Small intestine (bile, lipase, trypsin; absorption via villi) → Large intestine (water absorption) → Rectum → Anus"},
  {cat:"human-systems", q:"What is the Immune Response?", a:"1. Non-specific: skin barrier, phagocytosis (white blood cells engulf pathogens)\n2. Specific: lymphocytes produce antibodies targeting specific antigens.\nMemory cells remain for future immunity (basis of vaccination)."},

  // ===== PLANT BIOLOGY =====
  {cat:"plant-biology", q:"Describe Transpiration", a:"The loss of water vapour from the leaves of a plant through stomata. Creates a transpiration pull that draws water up through xylem. Factors: temperature, humidity, wind, light."},
  {cat:"plant-biology", q:"What is the role of Xylem?", a:"Transports water and dissolved minerals from roots to leaves. Dead, hollow cells reinforced with lignin. Transport is one-way (up). Driven by transpiration pull, root pressure, and capillary action."},
  {cat:"plant-biology", q:"What is the role of Phloem?", a:"Transports sucrose and amino acids (organic nutrients) from leaves (source) to other parts of the plant (sink). Living cells with sieve plates and companion cells. Transport is bidirectional (translocation)."},
  {cat:"plant-biology", q:"What are Tropisms?", a:"Directional growth responses to external stimuli.\nPhototropism: growth towards/away from light (auxin)\nGeotropism: growth towards/away from gravity\nHydrotropism: growth towards water\nPositive tropism = towards; negative = away"},
  {cat:"plant-biology", q:"What is the role of Auxin?", a:"A plant growth hormone. Promotes cell elongation. Causes phototropism (moves to shaded side → elongation → bending towards light). High concentrations inhibit growth in roots but promote it in stems."},

  // ===== EXPERIMENTS =====
  {cat:"experiments", q:"Describe the experiment to investigate Osmosis in plant tissue", a:"1. Cut equal-sized potato cylinders\n2. Place in solutions of different sucrose concentrations\n3. Leave for 24 hours\n4. Remove, blot dry, measure mass/length\n5. In hypotonic solution: gains mass (water enters by osmosis)\n6. In hypertonic solution: loses mass (water leaves by osmosis)"},
  {cat:"experiments", q:"Describe the experiment to show the effect of temperature on enzyme activity", a:"1. Prepare test tubes of starch solution + amylase at different temperatures\n2. At intervals, test for starch using iodine\n3. Record time for starch to be fully digested (iodine stays brown)\n4. Fastest digestion at optimum temp (~37°C)\n5. No digestion at very high temps (enzyme denatured)"},
  {cat:"experiments", q:"Describe the experiment to investigate the rate of Photosynthesis", a:"1. Place aquatic plant (Elodea) in water under a light source\n2. Count bubbles of O₂ released per minute\n3. Vary distance of light source (light intensity)\n4. Result: more light → more bubbles (up to a plateau)\nControl: temperature, CO₂ concentration"},
  {cat:"experiments", q:"How would you prepare a slide to view cells under a microscope?", a:"1. Place a thin section of tissue on a glass slide\n2. Add a drop of water\n3. Add a drop of stain (e.g., iodine for plant cells, methylene blue for animal cells)\n4. Lower a coverslip at an angle to avoid air bubbles\n5. View under low power first, then high power"},
  {cat:"experiments", q:"Describe the experiment to investigate factors affecting Transpiration", a:"1. Set up a potometer with a leafy shoot\n2. Measure rate of water uptake (distance bubble moves per minute)\n3. Vary conditions: wind (fan), humidity (polythene bag), light (lamp)\n4. Result: increased wind/light/temperature → increased transpiration rate"},

  // ===== MICROBIOLOGY =====
  {cat:"microbiology", q:"Name 3 types of microorganisms", a:"1. Bacteria (prokaryotes — unicellular, no nucleus)\n2. Fungi (eukaryotes — includes yeast, moulds, mushrooms)\n3. Viruses (non-living, contain DNA/RNA in protein coat, need host to reproduce)"},
  {cat:"microbiology", q:"Define Antibiotic", a:"A substance produced by a microorganism that kills or inhibits the growth of other microorganisms (bacteria). Example: penicillin from Penicillium fungus. Does NOT work against viruses."},
  {cat:"microbiology", q:"What is Aseptic Technique?", a:"Precautions taken to prevent contamination by unwanted microorganisms.\n1. Sterilise equipment (autoclave)\n2. Flame inoculating loop\n3. Work near Bunsen burner (updraft)\n4. Seal Petri dishes after inoculation\n5. Wash hands thoroughly"},
  {cat:"microbiology", q:"What is Pasteurisation?", a:"A heat treatment that kills harmful microorganisms in food/drink without destroying flavour. Milk is heated to 72°C for 15 seconds, then rapidly cooled. Named after Louis Pasteur."},
  {cat:"microbiology", q:"What is Biotechnology?", a:"The use of living organisms or their products in industrial processes. Examples:\n1. Fermentation (bread, beer, wine — yeast)\n2. Antibiotic production\n3. Genetic engineering (insulin production)\n4. Bioremediation (cleaning up pollution)"},

  // ===== ADDITIONAL KEY CONCEPTS =====
  {cat:"genetics", q:"Describe Mitosis", a:"Cell division producing 2 genetically identical diploid daughter cells.\nStages: Prophase (chromosomes condense) → Metaphase (line up at equator) → Anaphase (chromatids pulled apart) → Telophase (nuclear membranes reform) → Cytokinesis (cell divides).\nFor growth and repair."},
  {cat:"genetics", q:"Describe Meiosis", a:"Cell division producing 4 genetically different haploid daughter cells (gametes).\nTwo divisions: Meiosis I (homologous pairs separate — reduction division) and Meiosis II (sister chromatids separate).\nCrossing over in Prophase I → genetic variation."},
  {cat:"genetics", q:"Distinguish between Mitosis and Meiosis", a:"Mitosis: 2 cells, diploid, identical, for growth/repair\nMeiosis: 4 cells, haploid, genetically different, for gamete production\nMitosis: 1 division; Meiosis: 2 divisions\nMitosis: no crossing over; Meiosis: crossing over occurs"},
  {cat:"cell-biology", q:"What is the Fluid Mosaic Model?", a:"The accepted model of cell membrane structure. Phospholipid bilayer with proteins 'floating' in it like a mosaic. Fluid because molecules can move laterally. Includes: channel proteins, carrier proteins, glycoproteins, cholesterol."},
  {cat:"biomolecules", q:"What is ATP?", a:"Adenosine Triphosphate — the energy currency of the cell. When a phosphate group is removed (ATP → ADP + Pi), energy is released for cellular processes. Produced mainly in mitochondria during respiration."},
  {cat:"respiration", q:"What is an Oxygen Debt?", a:"The amount of extra oxygen needed after exercise to break down the lactic acid that accumulated during anaerobic respiration. Lactic acid is converted back to glucose in the liver."},
  {cat:"ecology", q:"What is Pollution?", a:"The harmful addition of substances or energy to the environment by human activity.\nAir: CO₂, SO₂, NO₂ (acid rain, greenhouse effect)\nWater: sewage, fertilisers (eutrophication)\nSoil: pesticides, heavy metals"},
  {cat:"ecology", q:"What is Eutrophication?", a:"1. Excess nutrients (nitrates/phosphates from fertilisers) enter water\n2. Algal bloom on surface\n3. Light blocked → aquatic plants die\n4. Decomposing bacteria multiply → use up oxygen\n5. Fish and other organisms die (BOD increases)"},
  {cat:"human-systems", q:"What is Homeostasis?", a:"The maintenance of a constant internal environment in the body. Examples: body temperature (37°C), blood glucose level, water balance, pH. Involves negative feedback mechanisms."},
  {cat:"genetics", q:"What is the Human Genome Project?", a:"An international research project (1990-2003) that mapped all ~20,000-25,000 human genes. Applications: identifying disease-causing genes, pharmacogenomics (personalised medicine), gene therapy."},
  {cat:"experiments", q:"How do you use a Capture-Recapture method?", a:"1. Capture a sample of organisms, count them (M)\n2. Mark them (harmlessly) and release\n3. After time, capture second sample (n)\n4. Count marked individuals in second sample (m)\n5. Population estimate = (M × n) / m\nAssumptions: no births/deaths/migration, marks don't affect survival"}
];
